do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'minstrel-build');
  delete from public.guides where game_id = v_game and slug = 'minstrel-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'minstrel-build', 'Minstrel: build para PvP y GvG', 'Build de Minstrel para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de los tres árboles de habilidades, la rotación de buffs y debuffs, las cartas y la mascota recomendadas, y trucos concretos para PvP 5v5 y GvG.', 13, false, 'El soporte con el golpe más duro del kit', 'El Tyr Cup sigue en marcha, y si vas a subir un Archer hasta Minstrel esta guía te ahorra la parte más pesada: qué habilidades priorizar en tus tres árboles, cómo encadenarlas en una pelea real, y qué cartas y mascota completan el build. Antes de repartir un solo punto, hay un dato que conviene tener claro: dentro de todo el kit de Minstrel, el golpe más duro no lo lleva ninguna clase de daño puro del juego — lo lleva un soporte. Arrow Vulcan, tu habilidad de firma en el árbol de Minstrel, inflige 1200% + 300 de daño físico a un único objetivo en su nivel máximo.

Minstrel está clasificada oficialmente como Ranged DPS, pero en la práctica juega como un híbrido de soporte y daño: buena parte de tu árbol de Bard y de Minstrel son canciones de área (las llamadas Solo) que suben el ASPD, el PATK/MATK, la defensa o la resistencia a alteraciones de estado de todo tu grupo — y a la vez bajan la defensa o las estadísticas del equipo rival — mientras un puñado de golpes concretos concentra el daño real. Eso también explica por qué favorece DEX, AGI e INT, en ese orden: DEX porque conecta tus golpes con más consistencia y ya arranca reforzada por la pasiva Owl''s Eye (+10 DEX permanente solo por invertir en ella); AGI porque sube tu ASPD y tu FLEE — aquí no vas a acumular HP como un Paladin, así que esquivar pesa más que aguantar; e INT porque sostiene tu reserva de SP, el recurso que de verdad limita cuánto rato puedes mantener las canciones activas.

Lo que sigue es el orden recomendado para tus tres árboles (Archer, Bard y Minstrel), la rotación de buffs y debuffs que de verdad decide una pelea, el equipo de cartas, la mascota que mejor encaja con este rol, y trucos concretos para 5v5 y GvG.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_27.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué Minstrel', 'Antes de repartir un solo punto, fíjate en el dato que define a esta clase: dentro de todo el kit de Minstrel, el golpe con más daño no lo lleva ninguna de las clases de daño puro del juego — lo lleva un soporte. Arrow Vulcan, tu habilidad de firma en el árbol de Minstrel, inflige 1200% + 300 de daño físico a un único objetivo en su nivel máximo. Ninguna otra habilidad de todo tu recorrido (Archer, Bard o Minstrel) se acerca a esa cifra.

Y sin embargo, la ficha oficial de la clase la describe como Ranged DPS mientras en la práctica funciona como un híbrido de soporte y daño: buena parte de tu árbol de Bard y de Minstrel son canciones de área (Solo) que suben el ASPD, el PATK/MATK, la defensa o la resistencia a alteraciones de estado de todo tu grupo — y a la vez bajan la defensa o las estadísticas del equipo rival. Esa doble identidad es la que condiciona el reparto de tus puntos de estadística.

Minstrel favorece DEX, AGI e INT, en ese orden de prioridad. DEX porque conecta tus golpes con más consistencia, y de hecho ya arranca reforzada por la pasiva Owl''s Eye (+10 DEX permanente solo por subirla). AGI porque sube tu ASPD (relevante en todo el tramo de ataques normales entre habilidad y habilidad) y tu FLEE — y como no vas a acumular HP como un tanque, esquivar pesa más que aguantar. E INT porque sostiene tu reserva de SP: con habilidades como Lullaby consumiendo 2 SP por segundo mientras está activa, y varias canciones de área más compitiendo por ese mismo recurso, quedarte sin SP a mitad de pelea es el fallo que más veces te va a costar una ronda.', 'https://www.roochub.com/classes/minstrel', false, array[]::text[]),
    (v_guide, 2, 'Árbol Archer (1er trabajo)', 'El árbol de Archer es donde sientas las bases de todo el build: aquí consigues tu primer daño a distancia de verdad y las pasivas de puntería y velocidad que vas a arrastrar durante el resto de la build, antes de pasar a Bard y, después, a Minstrel. Este es el orden de prioridad que te recomendamos.

• Owl''s Eye al máximo — la primera pasiva que deberías subir: +10 de DEX permanente y +15% de ASPD, sin coste de mantenimiento. Además desbloquea Steady Focus en cuanto llega a nivel 5.
• Double Strafe al máximo — tu primer golpe fuerte de verdad: en nivel 10 inflige un total de 350% + 200 de daño físico Neutral a un único objetivo.
• Vulture''s Eye al máximo — otra pasiva permanente: +14 de alcance de ataque por nivel. Barata y sin ninguna razón para dejarla a medias.
• Steady Focus (una vez tengas Owl''s Eye en nivel 5) — +10 de AGI y +10 de DEX durante 240 segundos. Actívala antes de un combate largo, no a mitad.
• Arrow Shower (con unos pocos puntos alcanza) — en nivel 10 inflige 300% + 100 de daño físico Neutral en el área designada y empuja a los objetivos golpeados; rinde más en 5v5 y GvG que en duelos 1v1.
• Fetter Arrow (1 punto) — 150% de daño físico a un objetivo designado e Inmoviliza 3 segundos. Un solo punto y tienes un control de objetivo que te va a sacar de más de un apuro.', 'https://www.roochub.com/classes/minstrel', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Archer_EXiaoZhiYan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_ErLianShi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_CangYingZhiYan.webp']::text[]),
    (v_guide, 3, 'Árbol Bard (2do trabajo)', 'Bard es tu segundo trabajo, y es donde tu kit empieza a definirse como el híbrido de soporte y daño que es Minstrel. Sigue este orden.

• Instrument Mastery al máximo — pasivo y barato: en nivel 5 te da +30 de PATK permanente. No hay motivo para retrasarlo.
• Impressive Riff al máximo — tu primer buff de área de verdad: +10% de ASPD a los aliados cercanos, con la versión Solo durando 60 segundos.
• Magic Strings al máximo — reduce el Global CD (tiempo de reutilización general) de los aliados cercanos un 20%, también 60 segundos en Solo. Es de los buffs que más rinden en peleas largas, porque deja a todo tu grupo soltando habilidades con más frecuencia.
• Song of Lutie al máximo — en nivel 10 restaura cada segundo el HP de tus aliados cercanos en un (180% de tu PATK + 600), con el efecto de curación variando según el tamaño del grupo. Tu principal herramienta de sostenimiento antes de llegar a Minstrel.
• Fantasy Music al máximo — pasiva: cada stack de Fantasy Chord te da +5% de daño físico y +5% de bono de curación, acumulable hasta 5 veces. Súbela a fondo aunque no veas el beneficio inmediato: sin 5 stacks de esto, más adelante ni siquiera vas a poder usar Final Rhapsody en tu árbol de Minstrel.
• Blow Whistle al máximo — en nivel 10 sube la PDEF base de tus compañeros de grupo un 95%, durante 600 segundos (10 minutos). Es esencialmente un buff de antes-de-pelea, no algo que reactives a mitad de combate.

Si te sobran puntos después de todo esto, repártelos en Melody Strike (en nivel 10 inflige 350% + 200 de daño físico a un objetivo designado — útil mientras subes, pero queda por detrás de Arrow Vulcan en cuanto llegas a Minstrel), en Amp y Encore (Amp añade un efecto extra cada vez que usas una canción en Solo, y Encore, que requiere Amp en nivel 3, vuelve a soltar gratis tu última canción Solo de nivel 5 durante 10 segundos más — rentable, pero solo una vez cubierto lo anterior), y por último en Cold Joke y Lullaby (dan control por probabilidad — 20% de Congelar y 10% de Dormir respectivamente — pero Lullaby además te cuesta 2 SP por segundo mientras esté activa, así que no la mantengas encendida sin necesidad).', 'https://www.roochub.com/classes/minstrel', false, array['https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_caokongyueqi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_cikedehuanghun.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_bulaiqizhishi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_yidengdeapple.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huanxiangyuezhang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_chuikoushao.webp']::text[]),
    (v_guide, 4, 'Árbol Minstrel (Trans. 2nd) — el núcleo del build', 'Esta es la joya de la corona: tu tercera clase (Trans. 2nd), donde se junta todo lo anterior en el Minstrel que vas a llevar al Tyr Cup. Sigue este orden.

• Arrow Vulcan al máximo — obligatorio: el golpe más duro de todo tu kit, 1200% + 300 de daño físico a un único objetivo en nivel 10. Es tu remate cuando de verdad necesitas bajar HP.
• Battle Theme al máximo — obligatorio: el buff de grupo más grande que tienes. En nivel 10 sube el PATK base de tus compañeros en 100, el MATK base en 100, y la PDEF y MDEF de equipo en un 10%.
• Music Mastery al máximo — pasiva y barata, pero muy rentable: +20% a tu propio daño físico y -10% a tu propio Global CD.
• Eternal Chaos (con sus 3 niveles alcanza) — resta un 30% a la defensa de todos los enemigos dentro del área, durante 20 segundos. Suéltalo justo antes de que tu equipo descargue sus golpes más fuertes, no después.
• Joyful Notes (1 punto) — no te lo saltes: te limpia los efectos de control que tengas encima y te da inmunidad a control durante 3 segundos. Es lo que te permite terminar una canción o un combo sin que te corten a mitad.
• Final Rhapsody al máximo — tu bomba de área: en nivel 5 inflige 1500% de daño físico a los enemigos cercanos, pero solo puedes lanzarla cuando tus stacks de Fantasy Music (de tu árbol de Bard) llegan a 5. Sin esa pasiva maximizada, esta habilidad no te sirve de nada.
• Nibelungan''s Ring (con sus 3 niveles alcanza) — sube el daño de Fuego, Agua, Viento y Tierra de tus aliados cercanos un 20%. Ayuda sobre todo a los compañeros de tu grupo que sí dependen de daño elemental.
• Siegfried the Undead God (con sus 3 niveles alcanza) — sube la resistencia a alteraciones de estado anómalas de tus aliados cercanos un 20%. Barato y rentable en cualquier GvG donde el rival juegue con estados alterados.
• Puppet Master''s Trick (situacional) — resta 10 a todas las estadísticas de los enemigos en el área y suma +10 a las de tus aliados, durante 180 segundos. Un empujón de estadísticas para toda la pelea, no solo daño.
• Loki''s Lament (situacional, 1 punto) — bloquea el uso de habilidades y objetos a todos los objetivos cercanos durante 5 segundos (los ataques normales siguen funcionando). Resérvalo para el instante exacto en que necesites cortarle el combo a un grupo entero, no lo gastes contra un único objetivo.
• Death Valley (situacional, 1 punto) — revive a un aliado caído devolviéndole un 20% de su HP máximo. Solo tiene sentido si tu grupo no lleva ya otra fuente de resurrección.

Si te sobran puntos, Don''t Hold Me Back reduce a la mitad la penalización de velocidad de movimiento mientras interpretas Duo Performance (solo relevante si vas a tocar en pareja con un Dancer/Gypsy), y Puppet Dance (te cuesta un 20% de tu HP actual para invocar un títere en el área objetivo durante 15 segundos) y Curtain Call (un desplazamiento rápido hacia delante) quedan para el final.', 'https://www.roochub.com/classes/minstrel', false, array['https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_aoyijianluanwu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_zhanguzhengtian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_qinmo.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_yongyuandehundun.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_MaestroWanderer_huishengzhige.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huanxiangkuangwuqu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_nibeilonggendejiezhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_kuileishidebaxi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_luoqidebeiming.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huiguizhige.webp']::text[]),
    (v_guide, 5, 'Tu rotación de buffs y debuffs', 'Minstrel no gana peleas con un combo de daño puro, sino con el orden en el que reparte sus canciones. Esta es la secuencia que de verdad marca la diferencia.

1. Antes de que empiece el choque, activa tus canciones de área de larga duración sobre tu grupo: Impressive Riff (ASPD), Magic Strings (reducción de Global CD) y Battle Theme (PATK/MATK/PDEF/MDEF). Todas dependen de que te quedes razonablemente cerca del grupo mientras suenan, así que no las actives y luego te alejes.
2. En cuanto se inicia el enfrentamiento, suelta Eternal Chaos sobre el grupo rival — el -30% de defensa que deja abre la ventana en la que todo tu equipo pega más fuerte. Este debuff sale ANTES de que tu equipo descargue sus golpes más fuertes, nunca después.
3. Con el enemigo ya debilitado en defensa, abre tu daño con Arrow Vulcan sobre el objetivo prioritario que marque tu equipo — es el golpe más duro de tu kit y aprovecha justo la ventana que acabas de abrir.
4. Si tus stacks de Fantasy Music ya están en 5, remata con Final Rhapsody para barrer a los enemigos agrupados a tu alrededor.
5. Guarda Joyful Notes para el instante exacto en que intenten controlarte a ti — te limpia el efecto y te da 3 segundos de inmunidad, lo justo para que termines lo que estabas haciendo sin que te corten.', 'https://www.roochub.com/classes/minstrel', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Aquí tienes el equipo de cartas que completa el build. Por la convención de dos décadas que arrastra esta franquicia, cada carta suele caer del monstruo o jefe que comparte su nombre — tómalo como una referencia orientativa y no como un dato de drop confirmado por un parche concreto de ROOC.

• Doppelganger (Épica, Arma) — ASPD +10%, AGI +5, CRIT +5, Daño de CRIT +12%; en set, +2% de ASPD adicional. Encaja de forma directa con tu prioridad de estadísticas (AGI) y con el ritmo de tu rotación.
• Phreeoni (Épica, Arma) — HIT +100, y cada punto de HIT aumenta el daño físico un 0,05%, hasta un máximo de 20% (el bono se acumula con varias cartas, pero el límite máximo no sube); en set, +3% de daño físico. Encaja bien porque casi todas tus habilidades de daño (Double Strafe, Arrow Vulcan, Melody Strike) escalan sobre daño físico plano.
• Marduk (Rara, Cabeza superior) — INT +3, y cada 6 segundos te da 1 segundo de inmunidad a Silencio además de eliminar el Silencio activo; en set, +12 de ATK de arma. Protege justo el punto débil de una clase que vive de canalizar canciones: si te silencian, se apaga todo tu kit de soporte.
• Nightmare (Rara, Cabeza superior) — AGI +3, y cada 6 segundos te da 1 segundo de inmunidad a Sueño además de eliminar el Sueño activo; en set, +12 de MATK de arma. Igual que Marduk, pero contra Dormir — un estado que suelen repartir precisamente otros Bard/Dancer rivales.
• Sohee (Poco común, Calzado) — Recuperación de SP +8%, HP máx. +4%; en set, +50 de HP máx. Ayuda directamente a tu mayor problema práctico: sostener el gasto de SP de tantas canciones activas.
• Verit (Poco común, Calzado) — HP máx. +3%, SP máx. +4%; en set, +2 de CRIT. Otra pieza que amplía tu colchón de SP sin sacrificar nada de HP.
• Toad (Común, Prenda) — FLEE +5, DEX +3 (con Refinamiento +10 llega a +5 de DEX); en set, +12 de MATK de arma. Barata y accesible desde el principio, y cubre dos de tus estadísticas prioritarias a la vez (DEX y FLEE).
• Zerom (Común, Accesorio) — DEX +3, CRIT +2; en set, +5 de MATK de arma. Otra pieza de relleno económica mientras subes, con DEX directo.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Siling.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Pilien.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Maerduke.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Mengyan.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Guinv.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Munaiyiquan.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Wawang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Jieluomi.webp']::text[]),
    (v_guide, 7, 'Mascota recomendada', 'De las 9 mascotas ya montadas en nuestra sección de Mascotas, la que mejor encaja con este rol es Squidgitte (Soporte · Pez). Su habilidad exclusiva, Dance of the Sea Monster, da +15% de daño físico/mágico a los aliados cercanos durante 10 segundos (sube a +25% en el Tier 10) — es decir, apila exactamente el mismo tipo de buff de daño de grupo que ya reparte tu propio kit de Minstrel (Battle Theme, Nibelungan''s Ring), en lugar de competir con él. Para una clase que ya se define por multiplicar el daño de su equipo, tener una mascota que hace lo mismo es la elección más coherente.

Si tu problema real en combate es la reserva de SP y no el daño de grupo, Teacup Rabbit (Soporte · Bruto) es la alternativa a considerar: su habilidad Drinks on Me rocía té causando 350% de daño mágico de agua a 6 enemigos frontales y devuelve SP al dueño al lanzar habilidades (el daño sube a 550% en el Tier 10).', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_saidula.webp', 'https://roocdb.com/pets/Pokemon_chabeitu.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y Minstrel tiene un truco concreto para cada uno.

• Blood and Gold — cuando los rivales se agrupen junto al Goblin King, suelta ahí tu Eternal Chaos antes de que tu equipo empiece a golpearlo: el -30% de defensa hace que la pelea por los recursos se resuelva mucho antes.
• Shapeshift Ops — si te marcan a ti como objetivo a controlar mientras tu compañero recoge el orbe de transformación, Joyful Notes te limpia el control y te da 3 segundos de inmunidad, justo lo que necesitas para no perder esa ventana.
• Cart Contest — tu kit no está pensado para cargar el carro tú mismo (no acumulas HP como un tanque); rinde más escoltando: mantén Impressive Riff y Magic Strings activas sobre quien sí lo lleva, y reserva Fetter Arrow para inmovilizar a cualquiera que se acerque a interceptarlo.
• Team Deathmatch — activa tus canciones de área antes de que empiece la ronda, no a mitad, y guarda Arrow Vulcan para el objetivo que marque tu equipo en vez de gastarlo contra el primer rival que se cruce.', 'https://www.roochub.com/classes/minstrel', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios premia decisiones distintas a las del 5v5. Estos son los trucos que marcan la diferencia.

• Vigrid Avenge (cargar el Cuerno) — no eres tú quien debería cargarlo: sin el HP de un tanque o un Paladin, esa mecánica te desangra demasiado rápido. Tu aportación real ahí es mantener Battle Theme y Blow Whistle activas sobre quien sí lo lleva, y soltar Eternal Chaos sobre cualquiera que intente interceptarlo.
• Vale of Clash (defender un Crystal Pillar) — Eternal Chaos primero, Arrow Vulcan después: baja la defensa del grupo que intenta arrebatarte el punto y luego castígalo con tu golpe más duro, todo desde una posición a distancia en vez de meterte cuerpo a cuerpo.
• Stellar Clash (cambios de objetivo) — en el instante en que tu equipo decide saltar a un nuevo objetivo, Fetter Arrow o Loki''s Lament son tu forma de cortarle cualquier intento de huida o de respuesta al jugador clave del bando rival.
• Canciones de área en combate masivo — con tantos aliados cerca en un choque de GvG, tus canciones Solo rinden al máximo; evita alejarte del grueso del grupo solo por perseguir una baja individual, porque en cuanto sales de rango todo tu equipo pierde el buff.', 'https://www.roochub.com/classes/minstrel', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan.

• Meterte cuerpo a cuerpo a intercambiar golpes en vez de mantener distancia. Minstrel no acumula HP como un tanque; tu supervivencia depende de FLEE y de mantenerte fuera del rango de los rivales cuerpo a cuerpo, no de aguantar impactos.
• Lanzar Final Rhapsody sin haber comprobado antes que tus stacks de Fantasy Music llegan a 5 — sin ellos, la habilidad ni siquiera se activa.
• Activar tus canciones de área y alejarte demasiado del grupo: en cuanto sales de rango, tus aliados pierden el buff sin que tú lo notes.
• Gastar Joyful Notes de forma reactiva, ya con la pelea perdida, en lugar de guardarlo para el control que sabes que viene (por ejemplo, justo cuando se acercan enemigos con habilidades de aturdimiento o silencio).
• Quedarte sin SP a mitad de pelea por mantener encendida Lullaby (2 SP por segundo) más tiempo del necesario, y no tener ya reserva para las canciones que sí deciden el combate.', 'https://www.roochub.com/classes/minstrel', false, array[]::text[]);
end
$IMPERIUM$;
