do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'high-wizard-build');
  delete from public.guides where game_id = v_game and slug = 'high-wizard-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'high-wizard-build', 'High Wizard: build para PvP y GvG', 'Build de High Wizard para Ragnarok Origin Classic pensada para el Tyr Cup: cubre el orden de los tres árboles de habilidades, el combo de congelación y burst, las cartas y la mascota recomendadas, y trucos concretos para PvP 5v5 y GvG.', 6, false, 'De clase floja a máquina de zonas de daño', 'El Tyr Cup sigue marcando el ritmo de todo servidor de PvP y GvG en Ragnarok Origin Classic, y no todas las clases llegan con la misma fama. High Wizard es de las que peor prensa arrastra: varias tier lists de la comunidad la sitúan en el escalón bajo, señalando sus tiempos de conjuro y cooldowns largos como el motivo — te pasas más tiempo preparando el golpe que golpeando de verdad.

Esta guía no está para negar esa crítica, sino para enseñarte a superarla. Reúne en un solo sitio el orden de habilidades de tus tres árboles (Mage, Wizard y High Wizard), el combo de congelación y burst que abre cualquier pelea, y el equipo de cartas y mascota que completa el build.

Porque el mismo análisis que la castiga reconoce por qué remonta en cuanto subes de nivel: hechizos como Meteor Storm y Gravitation Field, bien posicionados y con el cooldown adecuado, convierten a High Wizard en una clase capaz de levantar zonas de daño de las que casi nadie sale con vida — tanto en el 5v5 de Dimension Drill como en la guerra de gremios. El resto de esta guía, paso a paso, es cómo llegar a ese punto.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_15.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué High Wizard', 'Antes de repartir el primer punto, conviene ser honestos con la fama que arrastra esta clase: varias tier lists de la comunidad sitúan a High Wizard en el escalón bajo, entre las clases que cuesta mantener competitivas, porque la mayoría de sus hechizos grandes tienen tiempos de lanzamiento y cooldowns largos — te pasas más tiempo preparando el golpe que golpeando de verdad, sobre todo en las primeras etapas del personaje.

Pero ese mismo análisis reconoce que la clase cambia de cara en cuanto entran en juego Meteor Storm y Gravitation Field: con la reducción de cooldown adecuada y la posición correcta, High Wizard deja de sufrir su propio ritmo lento y empieza a levantar zonas de daño de las que casi nadie sale con vida. Esta guía está pensada exactamente para llegar a ese punto — no para spamear hechizos básicos sin criterio, sino para construir el burst y el control de zona que hacen que valga la pena esperar el cast.

High Wizard avanza como Magic DPS con preferencia clara por INT, DEX y VIT, y esa combinación no es casual: el INT es tu daño mágico en bruto, la VIT es el colchón de HP que necesitas para aguantar la larga ventana en la que tus hechizos grandes están a medio lanzar, y el DEX es justo lo que ataca la debilidad que señalan las tier lists, porque acorta tu tiempo de cast y el cooldown entre un hechizo y el siguiente. Reparte tus puntos en ese orden — INT primero, sin discusión, y luego DEX y VIT según lo que note más tu build.', 'https://www.roochub.com/classes/high_wizard', false, array[]::text[]),
    (v_guide, 2, 'Árbol Mage (1er trabajo)', 'El árbol de Mage es donde sientas la base de todo el build antes de pasar a Wizard y, después, a High Wizard. Aquí no hace falta apostarlo todo a hacer daño: varios de tus hechizos básicos tienen un techo mucho más bajo en PvP que en PvE, así que la prioridad real es abrir los caminos que necesitas para los árboles siguientes y no gastar de más en lo que no rinde igual contra jugadores. Este es el orden que te recomendamos.

• Fire Bolt hasta nivel 5 (mínimo) — inflige hasta 1500% + 800 de daño mágico (MDMG) de Fuego contra monstruos, pero ese número se queda fijo en 975% en cualquier enfrentamiento contra otro jugador. Con nivel 5 desbloqueas tanto Fire Ball como Fire Wall, así que no hace falta subirlo más solo por el daño en PvP.
• Cold Bolt hasta nivel 5 (mínimo) — mismo patrón que Fire Bolt (975% fijo en PvP, hasta 1500% + 800 en PvE) pero de elemento Agua. Solo lo necesitas para desbloquear Frost Diver en nivel 5.
• Frost Diver al máximo — este sí sube de verdad tu daño en cualquier enfrentamiento: 200% + 200 de MDMG de Agua a un único objetivo, con un 65% de probabilidad de dejarlo Frozen. Es tu freeze lock: el hechizo con el que abres cualquier pelea 1 contra 1, porque un rival congelado no puede moverse ni interrumpirte mientras preparas el resto del combo.
• Increase SP Recovery al máximo — restaura 30 puntos fijos más un 2% de tu SP máximo cada 10 segundos, y sube al 150% lo que recuperas con pociones de SP. Con el gasto que tiene el kit de Wizard y High Wizard más adelante, no te puedes permitir ignorar esto.
• Energy Coat (1 punto, nivel máximo 1) — por solo 25 de SP, genera un escudo que reduce el daño recibido un 15% si tu SP está por encima de la mitad de tu máximo (10% si está por debajo), durante 7 segundos. Es tu única herramienta defensiva de esta etapa y cuesta tan poco que no tiene sentido saltárselo.
• Fire Wall (con los puntos que te sobren, no hace falta al máximo todavía) — un muro que inflige 80% + 100 de MDMG de Fuego cada vez que un enemigo lo cruza, hasta 17 bloqueos durante 16 segundos. Aquí solo lo dejamos apuntado; en GvG es donde de verdad rinde, y lo retomamos en el paso de trucos para guerra de gremios.

Lightning Bolt, Stone Curse y Soul Strike quedan de relleno si te sobran puntos: ninguno de los árboles siguientes depende de ellos, y su daño no aporta nada que Frost Diver o tus futuros hechizos de área no cubran ya mejor.', 'https://www.roochub.com/classes/high_wizard', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoJianShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BingJianShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BingDongShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ChanXin.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_NengLiangWaiTao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoYanZhiBi.webp']::text[]),
    (v_guide, 3, 'Árbol Wizard (2do trabajo)', 'Wizard es donde empiezas a construir de verdad el arsenal de área que define a un High Wizard. Sigue este orden: varias de estas habilidades dependen unas de otras, así que no te saltes los requisitos.

• Water Ball hasta nivel 5 (mínimo) — 5 proyectiles de agua que suman hasta 1500% + 1005 de MDMG contra un único objetivo. Con nivel 5 desbloqueas Storm Gust, así que no lo dejes para el final.
• Storm Gust al máximo (requiere Water Ball nivel 5) — tu hechizo de área insignia: hasta 4200% de MDMG de Agua (5000% + 750 en PvE) repartido en 10 golpes contra hasta 10 objetivos, y encima empuja hacia atrás a todo el que golpea. Es la habilidad con la que abres cualquier pelea de grupo.
• Jupitel Thunder al máximo — 12 golpes consecutivos contra un único objetivo que suman hasta 1300% + 800 de MDMG de Viento. No depende de nada previo, y en nivel 3 desbloquea Lord of Vermilion.
• Lord of Vermilion al máximo (requiere Jupitel Thunder nivel 3) — hasta 3300% + 580 de MDMG de Viento (3600% en PvE) contra hasta 10 objetivos, con un 15% de probabilidad de dejar Ciego al objetivo. Un Ciego encima no es solo daño: es peor puntería para cualquier rival cuerpo a cuerpo que te esté persiguiendo.
• Fire Pillar hasta nivel 5 (mínimo) y Sight + Sightrasher hasta nivel 3 (mínimo) — la cadena de tres habilidades que necesitas como peaje para desbloquear Meteor Storm. Fire Pillar planta una trampa de fuego que golpea hasta 7 veces a quien la cruce (el daño escala con tu propio MATK), y Sightrasher lanza bolas de fuego en 8 direcciones a tu alrededor (240 + 100 de MDMG de Fuego, con empuje) — más útil como salida de emergencia que como tu daño principal.
• Meteor Storm al máximo (requiere Fire Pillar nivel 5 y Sightrasher nivel 3) — invoca 9 meteoros al azar sobre la zona marcada; cada uno inflige 700% de MDMG de Fuego en enfrentamientos PvP (875% + 154 en PvE) contra hasta 10 objetivos, con un 30% de probabilidad de Aturdir. Es, junto con Storm Gust, la habilidad que de verdad convierte tu posición en una zona de la que nadie sale caminando.
• Quagmire al máximo — reduce en 50 la AGI y en 50 el DEX de todos los enemigos en la zona, además de un 25% de su velocidad de movimiento, durante 50 segundos. No hace daño, pero frenar en seco a quien te está cargando encima vale tanto como cualquier hechizo ofensivo.
• Tetra Vortex (los 3 niveles, es barato) — durante 6 segundos, o hasta tus próximos 3 hechizos, lanzas sin tiempo de conjuro. Es la respuesta directa al mayor problema de la clase: actívalo justo antes de soltar tu combo de área y nada de lo que lances en esa ventana puede ser interrumpido ni telegrafiado.

Earth Spike y Heaven''s Drive quedan opcionales: forman un segundo combo de área con daño respetable, pero no aportan nada que Storm Gust, Lord of Vermilion o Meteor Storm no cubran ya mejor — solo mételes puntos si te sobran.', 'https://www.roochub.com/classes/high_wizard', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Magician_ShuiQiuShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BaoFengXue.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_LeiMingShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_NuLeiQiangJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoZhuGongJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoZhiLieSha.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_YunShiShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_NiZhaoDi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Warlock_YuanSuXuanWo.webp']::text[]),
    (v_guide, 4, 'Árbol High Wizard — el núcleo del build', 'Esta es la clase de verdad: tu tercera transcendencia (Trans. 2nd), donde por fin tienes las herramientas para convertir todo lo anterior en las zonas de daño de las que hablábamos en el primer paso. Sigue este orden.

• Mystical Amplification al máximo — la primera habilidad que subes, sin discusión: +30% de daño mágico (MDMG) y +20% de MATK, permanentes, sin ningún requisito previo. Es pasiva, no cuesta SP y multiplica todo lo demás que hagas.
• Soul Drain al máximo — absorbe SP equivalente al 245% del nivel del monstruo que matas y sube tu SP máximo un 20% de forma permanente. Es lo que te permite encadenar hechizo tras hechizo sin quedarte seco a media pelea.
• Napalm Vulcan al máximo (nivel 5) — 700% + 50 de MDMG de Fantasma a un único objetivo, con al menos un 30% de probabilidad de aplicar el estado Curse. Súbelo al máximo porque en nivel 5 desbloquea tanto Ganbantein como Gravitation Field.
• Gravitation Field al máximo (requiere Napalm Vulcan nivel 5) — esta es la habilidad que le da la vuelta a la fama de clase floja: inflige 400% + 30 de MDMG de Fantasma contra hasta 10 objetivos cada 0,5 segundos, durante 10 segundos completos (otro +300% de daño extra en PvE al nivel máximo). Plantada en el sitio correcto — la entrada de una sala, un pasillo de guerra de gremios — se convierte en una zona de la que nadie sale ileso si se queda dentro.
• Stonehenge al máximo — hasta 2530% de MDMG de Tierra contra hasta 10 objetivos, con un 21% de probabilidad de Inmovilizar. Tu segunda gran zona de daño, y el Inmovilizar combina perfectamente con Gravitation Field: nadie sale caminando de ninguna de las dos.
• Frost Nova al máximo — golpea a hasta 10 enemigos a tu alrededor con +200% de MDMG de Agua y un 70% de probabilidad de Congelar. Es tu botón de pánico cuando alguien te alcanza cuerpo a cuerpo: congelas a todo el que te rodea y ganas los segundos que necesitas para reposicionarte o rematar.
• Elemental Awareness al máximo — sube un 25% permanente el daño de tus hechizos de Viento, Tierra, Fuego, Agua y Fantasma (otro +15% extra contra monstruos), y al nivel máximo tus ataques de Viento, Tierra, Agua y Fuego tienen un 15% de probabilidad de tratar la defensa elemental del objetivo como si fuera débil frente a ese elemento. Desbloquea, además, Elemental Resistance.
• Elemental Resistance al máximo (requiere Elemental Awareness nivel 5) — un 30% permanente de resistencia al daño de hechizos de Viento, Tierra, Agua y Fuego. Con lo squishy que es esta clase contra otros lanzadores, no es ningún lujo.
• Element Control (1 punto, nivel máximo 1) — elimina todos los efectos de control activos y te da inmunidad a control más un 20% de velocidad de movimiento durante 3 segundos. Guárdalo como el botón de pánico contra un aturdimiento o una inmovilización que te esté costando la pelea; no lo gastes de forma preventiva.

Magic Crasher, Ganbantein y Teleport quedan opcionales si te sobran puntos: Magic Crasher pega poco (150% + 50 de MDMG Neutral, y solo 100% en PvP), Ganbantein sirve para desarmar trampas y hechizos enemigos que llevan mucho tiempo en el suelo, y Teleport es solo una reubicación rápida — útiles, pero ninguno decide una pelea como el resto de esta lista.', 'https://www.roochub.com/classes/high_wizard', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Magician_MoLiZengFu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_XiHunShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_NianLiLianJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ZhongLiYuanYe.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_JuShiChongJiZhen.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ShuangDongZhiShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_YuanSuGanZhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_YuanSuDiKangNew.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Warlock_YuanSuZhangKongNew.webp']::text[]),
    (v_guide, 5, 'Tu combo principal', 'Tener los puntos bien repartidos no sirve de nada si sueltas los hechizos en el orden equivocado. Esta es la secuencia que aprovecha de verdad el kit que acabas de montar.

1. Abre con Frost Diver sobre tu objetivo prioritario. Si se activa el 65% de probabilidad de Frozen, ese rival no puede moverse ni interrumpir lo que viene a continuación.
2. Activa Tetra Vortex justo después. Durante los siguientes 6 segundos, o tus próximos 3 hechizos, lanzas sin tiempo de conjuro: es la ventana en la que tu combo de área deja de ser telegrafiado.
3. Dentro de esa ventana, suelta Storm Gust sobre el grupo — agrupa y empuja — y encadena Meteor Storm o Gravitation Field sobre el mismo punto para amontonar daño mientras nadie puede huir con facilidad.
4. Si alguien te alcanza cuerpo a cuerpo antes de que termines, Frost Nova a tu alrededor: congelas a quien te está pegando y ganas los segundos que necesitas para reposicionarte.
5. Guarda Element Control para el momento en que un aturdimiento o una inmovilización enemiga te esté costando la pelea; no lo actives por precaución, porque solo tienes uno.', 'https://www.roochub.com/classes/high_wizard', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Este es el equipo de cartas que completa el build, elegido para atacar justo los puntos débiles de la clase: el gasto de SP y la vulnerabilidad a que te interrumpan el cast.

• Dracula (Épica, Arma) — +100 de MATK de arma y +15% de daño mágico, más un efecto único clave para esta clase: el tiempo de lanzamiento no se interrumpe al recibir daño; en set con otra pieza Épica, +3% de daño mágico extra. Es, con diferencia, la carta que más ataca la debilidad de cast largo que arrastra High Wizard.
• Pharaoh (Épica, Cabeza superior) — reduce el costo de SP un 50% y suma un 8% de daño mágico; en set, otro +3% de daño mágico. Con el gasto que tiene tu kit de área, esta carta por sí sola te alarga muchísimo cada pelea.
• Mistress (Épica, Cabeza superior — alternativa a Pharaoh) — +8% de daño mágico e Inmunidad a Hechizo; en set, +3% de daño mágico adicional. Si ya tienes resuelto el sostenimiento de SP con otro equipo, esta versión te da más daño puro a cambio.
• Maya (Épica, Mano secundaria) — al recibir daño mágico, refleja un 20% de ese daño al enemigo (+0,2% adicional por cada punto de VIT, hasta 40%), con 4 segundos de reutilización; en set, +3% de reducción de daño mágico recibido. Un contador directo contra otros lanzadores que intenten quemarte a distancia.
• Angeling (Épica, Armadura) — +5% de Max HP y cambia el elemento de tu armadura a Sagrado; en set, otro +3% de Max HP. Colchón extra de vida para sobrevivir la ventana en la que tus hechizos grandes están a medio lanzar.
• Moonlight Flower (Épica, Calzado) — +5% de Max HP y un efecto único de +20% de velocidad de movimiento; en set, +2% adicional de velocidad de movimiento. High Wizard vive de reposicionarse entre hechizo y hechizo, y esta carta es la que te lo permite.
• Mimic (Común, Accesorio) — +10 de MATK de arma y -2% de tiempo de lanzamiento variable; en set, +5 de ATK de arma. No es una carta rara ni cara, pero ataca exactamente el mismo problema que Dracula mientras consigues algo mejor.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Degulananjue.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Falaowang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Fenghou.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Yihou.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Tianshiboli.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Yueyemao.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Xieexiang.webp']::text[]),
    (v_guide, 7, 'Mascota recomendada', 'De las 9 mascotas disponibles en este juego, la que mejor encaja con un High Wizard es Teacup Rabbit. Su habilidad exclusiva, Drinks on Me, rocía té causando 350% de daño mágico de Agua a 6 enemigos frontales (sube a 550% en el Tier 10) y, más importante todavía, devuelve SP al dueño cada vez que lanza un hechizo — justo lo que necesita una clase que vive quedándose sin SP a mitad de pelea. Como premio extra, su daño es de elemento Agua, el mismo que comparten Cold Bolt, Frost Diver, Water Ball, Storm Gust y Frost Nova, así que no vas a tener fricciones con tu propio kit.

Si prefieres priorizar el apoyo a tu equipo de GvG por encima de tu propio sostenimiento de SP, Squidgitte es la alternativa: su habilidad Dance of the Sea Monster da un +15% de daño físico y mágico a los aliados cercanos durante 10 segundos (+25% en el Tier 10), lo que también sube tu propio daño de zona sin depender de que tú remates para activarlo.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_chabeitu.webp', 'https://roocdb.com/pets/Pokemon_saidula.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y High Wizard tiene un papel muy distinto al de un tanque en cada uno de ellos.

• Blood and Gold — espera a que los rivales se agrupen junto al Goblin King y suelta ahí Meteor Storm o Storm Gust: es exactamente el tipo de blanco agrupado para el que están pensadas esas habilidades.
• Shapeshift Ops — cuando el bando rival se lance a por el orbe de transformación, Frost Diver o Frost Nova sobre quien lo esté recogiendo lo deja congelado el tiempo suficiente para que tu equipo se lo quite.
• Cart Contest — no eres tú quien debería cargar el carro, pero Quagmire sobre quien intente cerrarte el paso le resta AGI, DEX y un 25% de velocidad de movimiento: suficiente para que tu portador pase de largo.
• Team Deathmatch — activa Tetra Vortex antes de que empiece la ronda y no sueltes tu combo de área contra el primer rival que aparezca: espera a que el equipo contrario se agrupe para que Storm Gust y Gravitation Field rindan al máximo.', 'https://www.roochub.com/classes/high_wizard', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios es donde High Wizard rinde de verdad, porque aquí el problema de sus tiempos de conjuro largos importa mucho menos: nadie se mueve tan rápido como en un 5v5, y una zona de daño bien plantada se queda ahí para castigar a cualquiera que insista en pasar.

• Defender un Crystal Pillar en Vale of Clash — plántate cerca del punto y deja caer Gravitation Field o Stonehenge justo encima. Cualquier equipo que intente forzar el punto entra directo en una zona de la que no sale sin sangrar, mientras Quagmire frena a los primeros que se acerquen.
• Vigrid Avenge — no eres tú quien debería cargar el Cuerno (esa mecánica está pensada para clases con mucha HP), pero sí puedes escoltar a quien lo lleva: Frost Nova y Storm Gust sobre cualquiera que se acerque a tu portador lo frena o lo congela antes de que llegue a tocarlo.
• Cambios de objetivo en Stellar Clash — aprovecha justo el momento en que tu equipo decide saltar a un nuevo objetivo para activar Tetra Vortex y descargar tu combo de área sin telegrafiarlo: el rival no tiene el aviso de un conjuro largo para reaccionar y escapar.
• Ganbantein contra trampas rivales — si otro Wizard o un Hunter/Ranger enemigo llena el punto de disputa de trampas o hechizos que se quedan en el suelo, Ganbantein te limpia el terreno antes de que tu equipo intente cargar a través de él.', 'https://www.roochub.com/classes/high_wizard', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan.

• Abrir con tus hechizos grandes sin haber congelado antes al objetivo con Frost Diver: sin eso, cualquier rival con media reacción te interrumpe el cast antes de que termine.
• Gastar Tetra Vortex de forma preventiva, lejos de la pelea, en lugar de guardarlo para el instante exacto en el que vas a soltar tu combo de área.
• Quedarte sin SP a mitad de guerra de gremios por no haber invertido en Soul Drain, Increase SP Recovery o la carta Pharaoh: un High Wizard seco es un DPS que no dispara.
• Activar Element Control de forma preventiva en lugar de reservarlo para cuando un control real —aturdimiento, inmovilización— te esté costando la pelea: solo tienes uno, y gastarlo demasiado pronto te deja sin salida cuando de verdad lo necesitas.
• Ignorar el posicionamiento: Gravitation Field, Stonehenge y Meteor Storm valen lo que vale el sitio donde los plantas. Soltarlos sobre un objetivo disperso, en vez de un grupo, es desperdiciar la razón de ser de esta clase.', 'https://www.roochub.com/classes/high_wizard', false, array[]::text[]);
end
$IMPERIUM$;
