do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'high-priest-build');
  delete from public.guides where game_id = v_game and slug = 'high-priest-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'high-priest-build', 'High Priest: build para PvP y GvG', 'Build de High Priest para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de los tres árboles de habilidades, la rotación de soporte y curación, las cartas y la mascota recomendadas, y trucos concretos para PvP 5v5 y GvG.', 4, false, 'La clase que ninguna guerra de gremios gana sin ella', 'El Tyr Cup ya está en marcha, y con $1,000,000 en juego el gremio que se planta en Vale of Clash o Stellar Clash sin un healer de verdad no aguanta ni el primer asalto. Si vas a subir High Priest, esta guía reúne en un solo sitio el orden de tus tres árboles de habilidades, tu rotación de soporte y curación en combate, y el equipo de cartas y la mascota que completan el build.

High Priest es la rama Acolyte → Priest → High Priest, la clase Support/Healer por excelencia de ROOC, con prioridad de estadísticas INT > VIT > DEX. Su identidad va mucho más allá de curar: Sanctuary cubre a hasta 13 aliados a la vez con más de 1,700 HP por segundo mientras castiga con más de 850 de daño mágico Sagrado por segundo a quien se quede dentro, y Assumptio dobla la defensa de equipo de todo tu grupo durante 5 minutos. Ningún Paladin aguanta una guerra de gremios sin alguien sosteniéndolo así por detrás.

A diferencia del Paladin, aquí no vas a encontrar una estadística de bajas que abra la guía — no la tenemos verificada para esta clase, y esta guía no inventa números que no puede respaldar. Lo que sí tienes, paso a paso, son los números reales de cada habilidad de tus tres árboles, para que sepas exactamente qué estás activando y por qué.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_17.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué High Priest', 'A diferencia de Paladin, esta guía no abre con una estadística de bajas de torneo — no la tenemos verificada para High Priest, y preferimos no inventar un dato que no podemos respaldar. Lo que sí puedes comprobar es el motivo estructural por el que ningún gremio serio se planta en el Tyr Cup sin uno: mira lo que hace Sanctuary, la habilidad que define tu segundo trabajo. Cubre a hasta 13 aliados a la vez con al menos 1,700 HP de curación por segundo, mientras castiga a cualquier enemigo que se quede dentro del área con al menos 850 de daño mágico Sagrado por segundo, durante 12 segundos seguidos. Ningún Paladin, ni ningún otro tanque, aguanta una línea de batalla sin ese respaldo detrás.

High Priest es la rama Acolyte → Priest → High Priest: la clase Support/Healer por definición de ROOC, con prioridad de estadísticas INT > VIT > DEX. INT va primero porque entra literalmente en la fórmula de tu Heal — se calcula como (Nivel base + INT) × 0.72 × nivel de habilidad + (0.5 + nivel de habilidad/20) × MATK + 70 — y también empuja el daño Sagrado de Sanctuary, Judex y Magnus Exorcismus. VIT va después: aunque Meditatio te regala un +15% de Max HP permanente más adelante, sigues siendo mucho más frágil que un tanque y necesitas ese colchón para sobrevivir el tiempo suficiente para lanzar tus habilidades. DEX cierra la lista de prioridades — no tenemos un desglose exacto de qué mueve en ROOC concretamente, así que trátala como el remate del build una vez cubiertas las dos anteriores.

Tu trabajo en cada pelea no es sumar bajas — es asegurarte de que las bajas las sume tu equipo mientras tú sigues de pie. Esta guía cubre el orden de tus tres árboles de habilidades, la rotación de curación y soporte que sostiene una pelea de principio a fin, y el equipo de cartas y la mascota que completan el build.', 'https://www.roochub.com/classes/high_priest', false, array[]::text[]),
    (v_guide, 2, 'Árbol Acolyte (1er trabajo)', 'Acolyte es tu primer trabajo, y aunque no tiene el brillo de las fases posteriores, aquí sientas la base de todo lo que viene después: tu curación, tu buff de estadísticas y tu primer escudo de verdad. Este es el orden que recomendamos.

• Heal al máximo — tu habilidad más usada, sin comparación. Se calcula como (Nivel base + INT) × 0.72 × nivel de habilidad + (0.5 + nivel de habilidad/20) × MATK + 70, y cada vez que la lanzas sobre alguien (incluido tú mismo) le das también un +10% de reducción de daño durante 2 segundos — un extra defensivo que mucha gente pasa por alto.
• Blessing al máximo — +10 de STR, +10 de DEX y +10 de INT para todo el grupo durante 600 segundos. Con esa duración, lánzala antes de entrar en zona de guerra y olvídate de ella el resto del combate.
• Angelus al máximo — requiere Heal nivel 5. Sube el PDEF base de todo el grupo un 95% durante otros 600 segundos. Junto con Blessing, forma la otra mitad del combo de buffs que activas antes de cualquier pelea seria.
• Increase AGI al máximo — requiere Blessing nivel 5. Es un pasivo que mejora la propia Blessing: al máximo le añade +12 de AGI y +25% de MSPD. Como ya vas a maximizar Blessing, no tiene sentido dejarlo fuera.
• Kyrie Eleison al máximo — requiere Angelus nivel 5. Crea un escudo sobre el aliado que elijas que bloquea daño físico equivalente al 50% de su Max HP, hasta un máximo de 12 golpes o 10 segundos, lo que llegue antes. Resérvalo para el compañero que el equipo rival está a punto de enfocar.
• Demon Bane al máximo — pasivo barato: +20 de PATK y +20 de PDEF permanentes, con otros +50 de PATK extra al atacar a tipo No-Muerto o Demonio, y +50 de PDEF extra al ser atacado por esos mismos tipos. Como con cualquier pasivo gratuito, no hay motivo para retrasarlo.
• Ruwach (1 punto, es su único nivel) — revela a las unidades en Sigilo dentro de un radio de 8 metros durante 30 segundos. Útil de forma puntual contra equipos con clases de sigilo.

Holy Light, Signum Crucis y Teleport quedan para el final si te sobran puntos: el primero es daño directo que no aporta nada a un build pensado para sostener al equipo, el segundo solo rinde contra tipos de monstruo concretos (más pensado para PvE), y el tercero es una utilidad de reposicionamiento de emergencia, no algo que cambie una pelea de PvP.', 'https://www.roochub.com/classes/high_priest', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ZhiYuShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiCiFu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiZhangBi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_BaXieZhiZhen.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiQu.webp']::text[]),
    (v_guide, 3, 'Árbol Priest (2do trabajo)', 'Priest es tu segundo trabajo, y aquí aparece la habilidad que de verdad te convierte en objetivo prioritario para el equipo rival: Sanctuary. Sigue este orden.

• Sanctuary al máximo — tu obligación número uno. Restaura al menos 1,700 HP por segundo a hasta 13 aliados dentro del área, mientras inflige al menos 850 de daño mágico Sagrado por segundo a cualquier enemigo que se quede dentro. Dura 12 segundos, con 15 segundos de reutilización en PvP. Ninguna otra habilidad de tu kit tiene ese impacto en una pelea grupal.
• Increase SP Recovery al máximo — pasivo obligatorio: al nivel máximo restauras [30 + 2% de tu SP máx.] cada 10 segundos de forma permanente, y sube al 150% la cantidad que recuperas de los objetos de recuperación. Con lo que gastas en este build, saltártelo no es una opción.
• Magnificat al máximo — duplica la velocidad de recuperación de SP de todo el grupo durante 90 segundos. Guárdalo para los asedios largos de GvG, cuando el SP empieza a escasear para todo el equipo, no solo para ti.
• Impositio Manus al máximo — sube el PATK y el MATK de todo el grupo en 50 puntos durante 300 segundos, y al nivel máximo añade otros +50 adicionales más un +35% del PATK/MATK de equipo. Es el buff de daño que le regalas al resto del equipo.
• Safety Wall al máximo — el primer aliado (o tú mismo) que entre en la zona recibe un 50% menos de daño cuerpo a cuerpo durante 10 segundos, hasta un máximo de 10 golpes bloqueados. Imprescindible para defender un punto contra equipos cuerpo a cuerpo.
• Pneuma al máximo — la misma idea que Safety Wall pero contra daño a distancia: 50% menos de daño durante 10 segundos, hasta 10 golpes. Actívala según el equipo rival sea más cuerpo a cuerpo o más a distancia — nunca las dos zonas a la vez sobre el mismo punto.
• Resurrection (los puntos que te queden tras lo anterior) — revive a un aliado caído devolviéndole un porcentaje de su Max HP, con solo 6.5 segundos de reutilización en PvP. En un GvG largo, esta habilidad sola puede decidir el resultado final.
• Aspersio y Recovery (con pocos puntos alcanza) — Aspersio da elemento Sagrado al arma de un compañero durante 300 segundos, útil contra ciertos tipos de enemigo; Recovery limpia todos los efectos de estado de tus compañeros de grupo. Ninguna de las dos es prioridad, pero rinden bien con un par de puntos sueltos.

Gloria, Turn Undead y Magnus Exorcismus quedan para el final: Gloria solo sube el LUK del grupo 60 segundos, y las otras dos apuntan sobre todo a monstruos de tipo No-Muerto — más rentables en PvE que en el Tyr Cup.', 'https://www.roochub.com/classes/high_priest', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_GuangYaoZhiTang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ChanXin.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ShengMuZhiSongGe.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ShenWeiQiFu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_AnZhiZhangBi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_FuHuoShu.webp']::text[]),
    (v_guide, 4, 'Árbol High Priest (Trans. 2nd) — el núcleo del build', 'Esta es tu tercera clase (Trans. 2nd): aquí Acolyte y Priest terminan de convertirse en el kit de soporte completo que sostiene al equipo en el Tyr Cup. Sigue el orden con disciplina — varias de estas habilidades dependen unas de otras para rendir al máximo.

• Meditatio al máximo — el pasivo que lo cambia todo: +10% de Max SP, +30% de recuperación de SP y +20% a la cantidad que restaura tu Heal, todo de forma permanente, más otro +20% de reducción de daño, +15% de Max HP y +20% de MSPD. Es, con diferencia, el pasivo más cargado de todo tu kit, y además desbloquea Mana Recharge.
• Mana Recharge al máximo — requiere Meditatio nivel 5. Reduce permanentemente un 20% el coste de SP de tus habilidades. Combinado con Increase SP Recovery y el propio Meditatio, es lo que te permite spamear Sanctuary y Heal sin quedarte seco a mitad de pelea.
• Assumptio al máximo — dobla el PDEF y el MDEF de equipo de todo el grupo durante 300 segundos. Es tu cooldown defensivo más fuerte: actívalo justo antes de que el equipo rival se lance sobre tu línea, nunca a mitad del intercambio.
• Suffragium (solo 3 niveles, cuesta poco) — requiere Assumptio nivel 5. Reduce un 45% el tiempo de lanzamiento durante 10 segundos, pero se consume con un solo uso. Gástalo justo antes de la habilidad que de verdad necesitas que salga ya — un Heal o un Sanctuary de emergencia — no como buff genérico.
• Basilica al máximo — reduce un 50% el daño que reciben los aliados dentro de la barrera, y cuando la barrera desaparece les restaura un 15% de su Max HP, todo durante 13 segundos. Es tu otra gran herramienta de control de zona, más fuerte que Safety Wall o Pneuma pero también más cara en SP.
• Bonded Fate al máximo — te vinculas con un compañero de grupo: le das un 25% extra de daño de habilidad, a ti te sube el MSPD un 17%, y mientras dure el vínculo ambos recuperáis un 135% de tu MATK en HP cada segundo. Úsalo sobre quien más daño esté aportando al combate.
• Lauda Agnus (aunque solo tiene 1 nivel) — limpia todos los efectos de estado y de control de los aliados cercanos y les da inmunidad a control durante 3 segundos. Es tu respuesta directa a cualquier cadena de aturdimientos o silencios que el equipo rival lance sobre tu grupo.
• Epiclesis al máximo — revive a hasta 5 aliados dentro del área devolviéndoles un 40% de su Max HP, y reduce el daño que reciben los aliados en esa zona un 20% durante 5 segundos. Es la jugada que rescata un wipe de equipo casi completo; resérvala para el peor momento del combate, no la gastes pronto.
• Lex Divina (unos pocos puntos) — al menos un 30% de probabilidad de infligir Silencio a un objetivo durante 30 segundos. Apunta al soporte o mago rival, no al primero que se cruce.
• Lex Aeterna (situacional) — requiere Lex Divina nivel 5. Sube el daño final que recibe el objetivo un 100% durante 3 segundos: úsala justo antes de que tu equipo descargue su combo de daño sobre ese mismo objetivo, nunca antes.
• Holy Ward (pasivo barato, si te sobran puntos) — sube un 20% el daño Sagrado que infliges, lo que empuja el propio daño de Sanctuary, Judex y Magnus Exorcismus.
• Judex y Leap of Faith (relleno final) — Judex inflige 700% de daño mágico Sagrado a un objetivo y hasta 10 monstruos cercanos, pero como habilidad de daño puro pesa menos en un build de soporte. Leap of Faith es un único punto barato: te lanza hacia delante y te da un escudo del 15% de tu Max HP durante 5 segundos, útil para reposicionarte rápido sin gastar mucho SP.', 'https://www.roochub.com/classes/high_priest', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_MingXiang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_MoLiJianMian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ShengMuZhiQiFu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_XiShengQiFu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ShenShengDianTang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_ArchBishop_ShengJieDaoGao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_ArchBishop_ChunJingZhiChi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_ArchBishop_ShengLingJiangLin.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ChenMoZhiShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_ArchBishop_CiBeiBiHu.webp']::text[]),
    (v_guide, 5, 'Tu rotación de soporte y curación', 'Tener los puntos bien repartidos no sirve de nada si no aplicas tus buffs y tu curación en el momento correcto. Esta es la secuencia que de verdad sostiene una pelea de principio a fin.

1. Antes de que arranque el choque, cubre a todo tu grupo con Blessing y Angelus — duran 600 segundos, así que puedes lanzarlas con margen de sobra — y añade Assumptio (300 segundos) sobre quienes van a recibir el primer golpe.
2. En el instante en que el equipo rival entra en rango, planta Sanctuary bajo tu propio frente de batalla: cura a hasta 13 aliados a más de 1,700 HP por segundo mientras castiga con más de 850 de daño Sagrado por segundo a quien se quede dentro.
3. Si ves que el rival se prepara para enfocar a tu compañero clave, cúbrelo con Kyrie Eleison antes de que empiecen los golpes; si el golpe ya va a llegar y no te da tiempo, gasta Suffragium para que tu siguiente Heal o Sanctuary salga un 45% más rápido.
4. Reparte Impositio Manus sobre quien más daño esté aportando al combate, y si la pelea se alarga, engánchale también Bonded Fate: el vínculo os cura a los dos un 135% de tu MATK por segundo mientras dure.
5. Si el equipo rival encadena aturdimientos o silencios sobre tu grupo, responde con Lauda Agnus: limpia todos los efectos de estado y control de los aliados cercanos y les da 3 segundos de inmunidad.
6. Si varios compañeros caen a la vez y la pelea se pone crítica, Epiclesis los revive a hasta 5 de golpe con un 40% de su Max HP y reduce el daño que reciben un 20% durante los primeros 5 segundos — la jugada que rescata un wipe.', 'https://www.roochub.com/classes/high_priest', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Aquí tienes el equipo de cartas que completa el build, elegido para lo que de verdad necesita un healer: bajar tu coste de SP, subir tu poder de curación y no perder el kit entero por un Silencio en mitad de la pelea.

• Pharaoh (Épica, Cabeza superior) — Costo de SP -50% y Daño mágico +8%, con set de Daño mágico +3%. Es la carta que más alivia tu economía de SP de toda la lista: combinada con Mana Recharge e Increase SP Recovery, es lo que te permite spamear Sanctuary y Heal sin cortarte a media pelea. Existe también una versión Legendaria (Illusion Pharaoh) con -20% de coste de SP y +2% de daño mágico, pero según los datos que tenemos rinde menos en coste de SP que esta Épica, así que no hay prisa por perseguirla.
• Marduk (Rara, Cabeza superior) — +3 de INT, y cada 6 segundos te da 1 segundo de inmunidad a Silencio además de eliminar el Silencio activo si lo tenías. Un Silencio te desactiva el kit entero, así que esta inmunidad periódica es de las herramientas más valiosas que puedes llevar. Ocupa la misma ranura que Pharaoh, así que en la práctica eliges una de las dos según lo que más te esté matando: falta de SP o Silencios rivales.
• Angeling (Épica, Armadura) — +5% de Max HP y cambia el elemento de tu armadura a Sagrado, con set de otro +3% de Max HP. Más colchón de vida para un healer que, pese a Meditatio, sigue siendo frágil.
• Rose Ornament (Poco común, Cabeza media) — +1% de Max HP, +1% de curación recibida y +1% de poder de curación, las tres directamente en la carta, con set de +50 de Max HP. Pocas cartas tan accesibles dan un bonus de poder de curación así de directo.
• Frilldora (Poco común, Prenda) — +3 de INT y -3% de tiempo de lanzamiento variable, con set de ATK de arma +5. Ese recorte de tiempo de lanzamiento hace que tus habilidades canalizadas salgan más rápido en los momentos críticos.
• Sohee, como carta (Poco común, Calzado) — +8% de recuperación de SP y +4% de Max HP, con set de +50 de Max HP. Ojo: esta es la versión CARTA de Sohee, distinta de la mascota del mismo nombre — aquí es una pieza de equipo más para tu economía de SP, no la mascota del siguiente paso.
• Deviling Puppet II (Rara, Espalda) — Daño PvP +100 y Resistencia PvP +100, con set de Poder de curación +2%. Combina supervivencia específica de PvP con un bonus de curación directo, ideal para el Tyr Cup.

Una aclaración importante: Eddga, Golden Thief Bug e Illusion Mistress —las cartas que sí recomendamos para Paladin en la otra guía— en realidad SUBEN tu coste de SP (entre un 10% y un 50%) en vez de bajarlo. Le sirven a un build físico que apenas depende del SP, pero le harían daño directo a tu economía como healer. Por eso no aparecen en esta lista.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Falaowang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Maerduke.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Tianshiboli.webp', 'https://www.roochub.com/icons/UI_MonsterCard_meiguihuaxi.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Sanxi.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Guinv.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Emoboli.webp']::text[]),
    (v_guide, 7, 'Mascota recomendada', 'De las 9 mascotas ya montadas para este juego, la que mejor encaja con un High Priest es Teacup Rabbit (rol Soporte · Bruto). Su habilidad exclusiva, Drinks on Me, rocía té causando un 350% de daño mágico de agua a 6 enemigos frontales y, lo más importante para ti, devuelve SP al dueño al lanzar habilidades — ese daño sube a 550% si subes sus 10 tiers al máximo (2,430 Pet Shard en total, comprados en la Pet Shop con Poring Coins que se ganan cazando monstruos Mini y MVP). Ningún otro rasgo del catálogo ataca tan directamente el problema real de un healer que spamea Sanctuary y Heal sin parar: quedarte sin SP a mitad de guerra de gremios.

Como alternativa, si tu equipo necesita más daño de grupo que sostenibilidad de SP, Squidgitte (rol Soporte · Pez) también encaja bien: su habilidad Dance of the Sea Monster da un +15% de daño físico y mágico a los aliados cercanos durante 10 segundos, que sube a +25% en el Tier 10 — refuerza el mismo papel de apoyo de daño en grupo que ya cumples con Impositio Manus y Bonded Fate.

Sohee, la mascota recomendada en la guía de Paladin, no la repetimos aquí: su kit (ASPD, velocidad de movimiento y robo de vida en combate cuerpo a cuerpo) está pensado para sostener el desgaste de una habilidad física como Sacrifice, no el de un caster que apenas ataca cuerpo a cuerpo — no tiene sentido forzarla en este build.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_chabeitu.webp', 'https://roocdb.com/pets/Pokemon_saidula.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y tu papel de soporte cambia bastante entre uno y otro.

• Blood and Gold — planta Sanctuary sobre el grupo de aliados que peleen cerca del Goblin King: la curación por segundo suele ser la diferencia entre ganar ese punto de control o perderlo por desgaste.
• Shapeshift Ops — en el momento en que un compañero se disponga a recoger el orbe de transformación, cúbrelo con Kyrie Eleison o Assumptio antes de que lo intenten, no después: ese es el instante exacto en el que el equipo rival se va a volcar en pararlo.
• Cart Contest — tú no eres quien debería cargar el carro (para eso está tu tanque), pero sí puedes mantener con vida a quien lo hace: Safety Wall o Pneuma sobre su ruta, según de dónde vengan los intentos de bloqueo.
• Team Deathmatch — guarda Suffragium para el momento en que tu compañero más débil de vida esté a punto de caer, y usa Lauda Agnus en cuanto veas que el rival encadena aturdimientos o silencios sobre tu grupo — no esperes a que la cadena se complete entera.', 'https://www.roochub.com/classes/high_priest', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios te exige decisiones distintas a las del 5v5, casi todas centradas en dónde te colocas y a quién proteges.

• Cargar el Cuerno en Vigrid Avenge — esa mecánica desangra sin parar a quien lo lleva, así que tu trabajo no es cargarlo tú (tu HP no aguanta ese desgaste ni de lejos), sino mantener con Sanctuary y Kyrie Eleison a quien sí lo hace, normalmente tu Paladin o tanque principal.
• Defender un Crystal Pillar en Vale of Clash — Basilica o Safety Wall sobre el punto es lo que permite a tu equipo quedarse clavado ahí sin ceder terreno; combínalo con Assumptio lanzada de antemano sobre los defensores, antes de que lleguen los primeros golpes.
• Cambios de objetivo en Stellar Clash — cuando tu equipo decide saltar sobre un nuevo objetivo, pon Bonded Fate sobre quien vaya a liderar el salto: el vínculo le da daño extra de habilidad justo cuando más lo necesita, y a ti te cura de paso.
• Posición durante un combate masivo — quédate justo detrás de tu línea, lo bastante cerca para que el radio de Epiclesis llegue a todo tu grupo si algo sale mal, pero lo bastante lejos para no ser el primer objetivo. Un High Priest muerto es una guerra de gremios perdida, aunque el resto del equipo siga en pie.', 'https://www.roochub.com/classes/high_priest', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan a un High Priest.

• No lanzar Blessing, Angelus y Assumptio antes de entrar en zona de guerra. Las tres duran varios minutos — lanzarlas tarde, a mitad de combate, regala la ventana entera en la que más rinden.
• Gastar el único uso de Suffragium en una habilidad cualquiera en vez de guardarlo para el Heal o el Sanctuary que de verdad necesitas que salga instantáneo.
• Plantarte en primera línea como si tuvieras el HP de un tanque. Pese a Meditatio, sigues siendo mucho más frágil que un Paladin — mantén distancia y usa Leap of Faith para reposicionarte, no para meterte en la pelea.
• Gastar todo tu SP en Lex Divina intentando silenciar rivales en vez de reservarlo para sostener a tu equipo. Un High Priest sin SP para curar en el momento decisivo pierde la pelea aunque haya silenciado a medio equipo rival.
• Olvidar el orden de requisitos entre habilidades — Meditatio nivel 5 antes de Mana Recharge, Lex Divina nivel 5 antes de Lex Aeterna, Assumptio nivel 5 antes de Suffragium — porque repartir puntos sin respetar ese orden deja habilidades bloqueadas más tiempo del necesario.', 'https://www.roochub.com/classes/high_priest', false, array[]::text[]);
end
$IMPERIUM$;
