do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'champion-build');
  delete from public.guides where game_id = v_game and slug = 'champion-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'champion-build', 'Champion: build para PvP y GvG', 'Build de Champion para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de los tres árboles de habilidades, el combo que sostiene todo el daño, la carta y mascota recomendadas, y trucos concretos para PvP 5v5 y GvG.', 5, false, 'El "sanador" que en realidad reparte golpes', 'La ficha de Champion lo etiqueta con rol Support / Healer, heredado de su tronco Acolyte — y a primera vista tiene sentido: nace de la misma rama que High Priest. Pero en cuanto miras las 22 habilidades documentadas entre Monk y Champion, esa etiqueta no aguanta: ninguna cura a un aliado. Esta guía trata a Champion por lo que realmente es en su árbol de habilidades: un peleador cuerpo a cuerpo que construye toda su cadena de daño alrededor de las Spirit Spheres.

El mecanismo es sencillo de entender y exigente de ejecutar: Zen o Call Spirit invocan esferas, Triple Attack proca solo con tus ataques normales y abre la puerta a una cadena de golpes —Chain Combo, Combo Finish, Tiger Knuckle Fist— que termina en Chain Crush Combo, capaz de superar el 1500% de daño físico neutral gastando las 5 esferas de golpe sobre un único objetivo. Finger Offensive complementa esa cadena por su cuenta: lanza hasta 5 esferas contra ese mismo objetivo, y si remata, te devuelve esferas al instante para saltar ya armado al siguiente rival.

No encontramos un dato de torneo específico para Champion como el que sí existe para Paladin (el leaderboard de bajas de la Season 1), así que esta guía se apoya en el propio árbol de habilidades: el orden de tus tres trabajos, el combo completo paso a paso, el equipo de carta y mascota que mejor encajan con un kit que vive de concentrar todo su daño en un único objetivo, y trucos concretos para Dimension Drill y GvG.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_21.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué Champion', 'Antes de repartir un solo punto, hay una desconexión que conviene aclarar: la ficha de Champion la cataloga con rol Support / Healer, heredado de su tronco Acolyte. Pero en cuanto miras el árbol de habilidades real de Monk y Champion, esa etiqueta no se sostiene: de las 22 habilidades documentadas entre esas dos ramas, ninguna cura a un aliado. Iron Palm, Triple Attack, Chain Combo, Combo Finish, Tiger Knuckle Fist, Chain Crush Combo, Finger Offensive, Fist Connect... todas suman daño físico neutral o PATK plano. Champion se juega como un peleador cuerpo a cuerpo de combos, no como un sanador — el ADN de soporte que conserva es solo el que arrastra de su paso por Acolyte (Heal, Angelus, Kyrie Eleison), y esta guía lo trata como el complemento útil que es, no como el centro del build.

No encontramos, de momento, un dato de torneo específico de Champion —del estilo del leaderboard de bajas que sí existe para Paladin en la Season 1 del Tyr Cup—, así que la justificación aquí es puramente mecánica: todo el kit gira en torno a las Spirit Spheres. Zen o Call Spirit las invocan (hasta 5 de golpe con Zen), y una cadena de golpes las va gastando y generando: Triple Attack proca sola en tus ataques normales, Chain Combo y Combo Finish encadenan el golpe, Tiger Knuckle Fist lo remata con un 60% de probabilidad de inmovilizar, y Chain Crush Combo cierra la cadena gastando esferas por hasta un 1500% de daño físico neutral a un único objetivo. Finger Offensive hace de as bajo la manga: lanza hasta 5 esferas contra ese mismo objetivo, cada una por un 900% adicional, y si remata al rival, te devuelve 5 esferas de golpe.

Eso condiciona el reparto de estadísticas: tanto la ficha de Champion como el resto de clases del árbol Acolyte coinciden en INT, VIT y DEX. No es INT para pegar con magia —Champion no tiene ni una habilidad de daño mágico en su kit final—, sino para sostener tu reserva de SP durante una cadena de combos larga, y de paso para que tu Heal de emergencia cure algo más, ya que su fórmula depende directamente de tu INT. VIT te deja aguantar los golpes mientras estás pegado al rival a rango de puño, y DEX evita que falles el golpe que abre toda la cadena.', 'https://www.roochub.com/classes/champion', false, array[]::text[]),
    (v_guide, 2, 'Árbol Acolyte (1er trabajo)', 'Aunque el destino final es Monk y luego Champion, tu primer trabajo es Acolyte, y aquí no repartes para curar como haría un High Priest: repartes para sobrevivir y dar un empujón puntual a tu grupo mientras te preparas para el verdadero combo. Este es el orden que recomendamos.

• Demon Bane al máximo — pasivo sin ningún requisito: +20 de PATK y +20 de PDEF permanentes, con otros +50 extra de cada uno si peleas contra monstruos Undead o Demon. Ningún build debería saltárselo.
• Heal, hasta nivel 5 (desbloquea Angelus) — no la vas a usar como fuente principal de curación, pero a nivel 5 restaura (Nivel Base + INT) × 0.72 × 5 + (0.5 + 0.25) × MATK + 70 de HP, y de paso reduce el daño que recibes un 10% durante 2 segundos justo después de lanzarla: un salvavidas de emergencia nada despreciable.
• Angelus, hasta nivel 5 (desbloquea Kyrie Eleison) — +95% de PDEF base a todo tu grupo durante 600 segundos. Un buff casi gratuito y de larga duración.
• Kyrie Eleison al máximo — un escudo para un aliado (o para ti mismo) que bloquea hasta el 50% de tu propia Max HP en daño, con un máximo de 12 golpes bloqueados, durante 10 segundos.
• Blessing, hasta nivel 5 (desbloquea Increase AGI) — +10 de STR, DEX e INT a todo tu grupo durante 600 segundos.
• Increase AGI, con lo que te quede — añade al estado de Blessing +12 de AGI y +25% de velocidad de movimiento: más margen para entrar y salir del rango de combo.

Holy Light (daño mágico) no encaja en un kit que va a rematar todo a puñetazos, y Signum Crucis solo baja la defensa de tipos de monstruo concretos —sin ningún uso en PvP—, así que ambas quedan fuera. Teleport y Ruwach son opcionales: Ruwach, en concreto, puede valer un punto suelto si tu servidor tiene mucha presencia de clases con sigilo como Stalker o Assassin Cross.', 'https://www.roochub.com/classes/champion', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiQu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_ZhiYuShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiZhangBi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_BaXieZhiZhen.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Acolyte_TianShiZhiCiFu.webp']::text[]),
    (v_guide, 3, 'Árbol Monk (2do trabajo)', 'Monk es donde aparece el mecanismo que sostiene todo el build: las Spirit Spheres. Este segundo trabajo ya no reparte en soporte, sino en la base de tu combo cuerpo a cuerpo.

• Call Spirit al máximo — la pieza fundacional: invoca Spirit Spheres (hasta 5 en total) que te siguen, y cada una en tu poder suma +5 de PATK de equipo, hasta +25 con las 5 activas. Sin esferas no hay combo.
• Iron Palm al máximo — pasivo sin requisito: sube tu maestría con Knuckles y te da +30 de PATK permanentes.
• Triple Attack al máximo — tu ataque normal tiene un 30% de probabilidad de encadenar un golpe extra de 3 impactos que suma 450% + 200 de daño físico neutral, y a partir de nivel 5 desbloquea Chain Combo.
• Chain Combo al máximo (desbloquea Combo Finish) — durante el margen que sigue a un Triple Attack, encadena un golpe de 500% + 500 de daño físico neutral.
• Combo Finish al máximo — el siguiente eslabón: otros 650% + 650 de daño físico neutral durante el margen que deja Chain Combo.
• Critical Explosion, hasta nivel 5 (desbloquea Asura Strike) — +20 de CRIT durante 180 segundos. Actívala antes de entrar en pelea.

Si te sobran puntos, repártelos primero en Invasion —no consume esferas si la lanzas en pleno Critical Explosion, y suma 500% + 500 de daño físico neutral más un extra igual a la PDEF de equipo del objetivo ÷ 2%— y después en Steel Body, que te da un botón de emergencia de +60% de reducción de daño físico y mágico durante 20 segundos (a cambio de -10% ASPD y -10% MSPD mientras dura). Asura Strike, Spiritual Cadence y Flee quedan en último lugar: Asura Strike es vistoso —gasta todas tus esferas y tu SP entero por un golpe forzado que puede superar el 1000% + 5000—, pero te deja 10 segundos sin regenerar SP y con un 80% menos de curación recibida, un coste demasiado alto para un build pensado para durar toda la pelea, no para un solo golpe.', 'https://www.roochub.com/classes/champion', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Monk_XuQi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_TieShaZhang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_LiuHeQuan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_LianHuanQuanShenZhang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_MengLongKuaQiang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_BaoQi.webp']::text[]),
    (v_guide, 4, 'Árbol Champion (Trans. 2nd) — el núcleo del build', 'Aquí es donde Champion deja de ser "un Monk más" y se convierte en la máquina de combos que domina el 1v1. Sigue este orden con disciplina: varias de estas habilidades literalmente encadenan una detrás de otra.

• Fist Connect al máximo — pasivo sin requisito: sigue subiendo tu maestría con Knuckles y suma +20% de PATK. El primer punto que inviertes aquí, sin excepción.
• Zen al máximo — te deja invocar las 5 Spirit Spheres de golpe en vez de una a una con Call Spirit, y desde nivel 1 desbloquea Finger Offensive (a nivel 5, además, Fist of Four Symbols).
• Tiger Knuckle Fist al máximo (necesario para Chain Crush Combo) — durante el margen que deja Combo Finish, encadena un golpe de 700% de daño físico neutral con un 60% de probabilidad de inmovilizar al objetivo.
• Chain Crush Combo al máximo — el cierre de toda la cadena Triple Attack → Chain Combo → Combo Finish → Tiger Knuckle Fist: 1500% de daño físico neutral a un único objetivo. Gasta 2 Spirit Spheres como base, y suma +15% de daño de habilidad por cada esfera extra que gastes, hasta +45% si gastas las 5 de golpe. Cuantas más esferas tengas acumuladas al llegar aquí, más duele.
• Finger Offensive al máximo — tu otro gran golpe, y no depende de la cadena anterior: lanza hasta 5 Spirit Spheres contra un único objetivo, cada una por un 900% de daño físico neutral (480% en PvP, según su propia ficha). Si remata al rival, te devuelve 5 esferas de golpe y reduce un 30% el tiempo de reutilización de tu siguiente habilidad — perfecto para encadenar una baja con la siguiente.

Con eso ya llevas invertidos los puntos que sostienen el combo completo. Si te queda margen, repártelo en este orden: Gentle Touch-Cure (cuesta un solo punto y gasta 1 Spirit Sphere para quitarte de encima cualquier control de masas — no lo dejes fuera solo porque parezca poca cosa), Tranquility (restaura 80% de tu HP y 100% de tu SP en apenas 2 segundos, tu botón de "sigo vivo"), y Fist of Four Symbols (consume todas tus esferas para potenciar tu próximo Triple Attack: con 2 esferas baja el AGI del rival en 6 y su MSPD un 60% durante 2 segundos, con 3 te da +20% de ASPD durante 3 segundos, con 4 te cura un 4% de HP, y con las 5 dobla el daño de ese Triple Attack — el conjunto dura 120 segundos). Blade Stop y Raging Palm Strike quedan como opciones situacionales: Blade Stop inmoviliza tanto a ti como al primer atacante cuerpo a cuerpo que te toque durante 20 segundos —útil para negar un punto en GvG, pésima idea contra un equipo con mucho daño a distancia—, y Raging Palm Strike solo aporta 450% de daño más un empujón, por debajo de lo que ya dan tus otras herramientas.', 'https://www.roochub.com/classes/champion', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Monk_QuanYiXiangTong.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_KuangXuQi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_FuHuQuan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_QiJueBengJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_TanZhiShenTong.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Asura_DianXueYu_01.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_BingQiNingShen.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_SiXiangZhiQuan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_ZhenJianBaiPoDao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Monk_MengHuYingPaShan.webp']::text[]),
    (v_guide, 5, 'Tu combo principal', 'Repartir bien los puntos no sirve de nada si no disparas el combo en el orden correcto. Esta es la secuencia que de verdad decide un 1v1.

1. Antes de entrar en pelea, invoca tus 5 Spirit Spheres con Zen y activa Critical Explosion (+20 CRIT durante 180 segundos) — nunca a mitad de combate, cuando ya perdiste la ventana.
2. Golpea con normalidad hasta que Triple Attack proque (30% de probabilidad): ese proc es lo que abre la ventana para encadenar el resto.
3. Dentro de esa ventana, encadena Chain Combo → Combo Finish → Tiger Knuckle Fist sin dejar que el margen se cierre entre uno y otro.
4. Cierra con Chain Crush Combo justo después de Combo Finish o de Tiger Knuckle Fist: si llegas con las 5 esferas intactas, es el momento de gastarlas todas de golpe para el +45% de daño extra sobre el 1500% base.
5. Si el objetivo sigue en pie o intenta huir, remata con Finger Offensive: sus 5 esferas lanzadas a un único objetivo (900% cada una) suelen bastar, y si consigues la baja, te devuelve esferas y acorta tu próxima habilidad para saltar ya armado al siguiente rival.
6. Si te controlan a mitad de secuencia, Gentle Touch-Cure te limpia por solo 1 esfera; si te quedas bajo de vida, Tranquility te devuelve 80% de HP y 100% de SP en 2 segundos. Ninguna de las dos rompe el combo si las metes entre pasos.', 'https://www.roochub.com/classes/champion', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Aquí tienes el equipo de cartas que mejor encaja con un Champion de combos: velocidad de ataque y crítico para que Triple Attack proque más seguido, daño físico plano, y algo de supervivencia para aguantar pegado al rival a rango de puño. Todas son de rareza Épica.

• Doppelganger (Arma) — ASPD +10%, AGI +5, CRIT +5 y +12% de daño crítico; en set, otro +2% de ASPD. Es la carta que más empuja tu ritmo de combo: más ASPD significa más intentos de que Triple Attack proque.
• Drake (Arma) — +12% de daño físico y mágico; en set, +3% de ataque de arma. Daño plano sin condiciones, encaja en cualquier build físico.
• Orc Hero (Cabeza superior) — +8 de VIT, y cada 6 segundos elimina cualquier Aturdimiento activo y te da inmunidad a Aturdimiento durante 4 segundos; en set, +3% de daño físico. Para un build que necesita quedarse pegado al rival sin que lo interrumpan a mitad de cadena, esta es probablemente la carta más importante de la lista.
• Angeling (Armadura) — +5% de Max HP y cambia el elemento de tu armadura a Sagrado; en set, otro +3% de Max HP. Colchón de vida extra para aguantar el intercambio de golpes.
• Eddga (Mano secundaria) — +10% al coste de SP y un efecto especial propio; en set, +3% de reducción de daño físico. Tu cadena de combos y tus esferas cuestan SP real: esta carta ayuda a que no te quedes seco a mitad de pelea.
• Moonlight Flower (Calzado) — +5% de Max HP y un efecto único de +20% de velocidad de movimiento; en set, +2% de velocidad de movimiento. Todo tu daño depende de estar pegado al rival, así que llegar hasta él más rápido no es un lujo.

Todas estas cartas están ya confirmadas en nuestra sección de Cartas — consúltala si quieres ver el catálogo completo por rareza.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Siling.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Haidaozhiwang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Shourenyingxiong.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Tianshiboli.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Huwang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Yueyemao.webp']::text[]),
    (v_guide, 7, 'Mascota recomendada', 'De las 9 mascotas que tenemos catalogadas, la que mejor encaja con Champion es Dr. Owl (rol DPS de Objetivo único). Todo el daño de Champion —Chain Crush Combo, Finger Offensive, Tiger Knuckle Fist— se concentra en un único objetivo por turno, y Gale Wind, la habilidad de Dr. Owl, encaja exactamente con eso: dispara una flecha de viento con 800% de daño físico y aumenta un 20% el daño físico que recibe ese mismo objetivo, subiendo a 1200% de daño propio y +30% de daño físico recibido en su mejora máxima (Tier 10). Dicho de otro modo: mientras tu combo entero apunta a una sola persona, tu mascota hace que esa misma persona encaje todavía más fuerte cada golpe que le metes.

Si prefieres priorizar la velocidad de tu combo por encima del daño amplificado, Kitten Oracle (también DPS de Objetivo único) es la alternativa: su Battle Blessing golpea con 800% de daño físico neutral y te da a ti un +10% de velocidad de ataque, justo lo que necesitas para que Triple Attack proque más seguido.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_maotouyingboshi.webp', 'https://roocdb.com/pets/Pokemon_zhanbumao.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill mete a Champion en un rol muy distinto al de un tanque como Paladin: aquí ganas eliminando a un objetivo cada vez, no aguantando de pie.

• Blood and Gold — aprovecha el reinicio de esferas que te da Finger Offensive al rematar un objetivo: si consigues una baja cerca del Goblin King, sales de esa pelea ya con esferas para la siguiente sin tener que reconstruirlas desde cero.
• Shapeshift Ops — el 60% de probabilidad de inmovilizar de Tiger Knuckle Fist es tu herramienta para frenar al portador del orbe de transformación antes de que escape; no la gastes contra nadie más si el portador está a tu alcance.
• Cart Contest — Champion no es el mejor perfil para cargar el carro (para eso está la HP masiva de Paladin), pero sí un buen escolta: cualquier rival que se acerque cuerpo a cuerpo a interceptarlo es candidato perfecto para una Chain Crush Combo con las 5 esferas completas.
• Team Deathmatch — invoca tus esferas y activa Critical Explosion antes de que empiece la ronda, y espera a que un rival quede aislado del resto antes de soltar Chain Crush Combo: todo tu daño se concentra en un único objetivo, así que elegir mal el blanco desperdicia el combo entero.', 'https://www.roochub.com/classes/champion', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios recompensa decisiones distintas, y varias herramientas de Champion encajan de forma muy específica en sus tres campos de batalla.

• Vigrid Avenge — cargar el Cuerno te va desangrando sin parar; si te toca a ti llevarlo, Tranquility (80% de HP y 100% de SP en 2 segundos) es el recurso más directo que tienes para aguantar el trayecto sin depender de que alguien más te cure.
• Vale of Clash — defender un Crystal Pillar es el escenario perfecto para Blade Stop: si un rival cuerpo a cuerpo te ataca mientras defiendes el punto, los dos quedáis inmovilizados 20 segundos, tiempo de sobra para que el resto de tu equipo llegue a limpiar. Resérvala para rivales cuerpo a cuerpo: si el equipo rival es mayoritariamente a distancia o mágico, quedarte inmóvil solo te convierte en un blanco fácil.
• Stellar Clash — cuando el objetivo cambie de manos, Tiger Knuckle Fist es tu herramienta para cortarle la huida a quien intente escapar con él: el 60% de probabilidad de inmovilizar puede ser la diferencia entre recuperar el objetivo o perderlo.
• Cualquier combate de gremio a gran escala — no actives Chain Crush Combo contra el primer objetivo que se cruce: espera a que quede aislado, porque todo tu daño depende de concentrarlo en una sola persona, y gastarlo contra el objetivo equivocado te deja sin esferas para cuando de verdad las necesites.', 'https://www.roochub.com/classes/champion', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el reparto perfecto sobre el papel, estos son los fallos que más se repiten con Champion.

• Entrar en pelea sin esferas invocadas. Si Zen o Call Spirit no están activos antes del primer intercambio de golpes, tus finishers (Chain Crush Combo, Finger Offensive) se quedan sin munición justo cuando más los necesitas.
• Gastar Chain Crush Combo o Finger Offensive contra un objetivo que está a punto de recibir un escudo, una curación, o que va a retirarse. Todo tu daño depende de concentrarse en una sola persona: si esa persona se escapa del golpe, perdiste el combo entero de un tirón.
• Olvidar que Gentle Touch-Cure existe. Cuesta un solo punto y una sola esfera, y aun así muchos Champion mueren atrapados en una cadena de control que esa misma habilidad habría cortado.
• Activar Blade Stop contra el rival equivocado. Inmoviliza a ambos jugadores durante 20 segundos: es una sentencia de muerte si el resto del equipo rival es de daño a distancia o mágico, porque van a seguir golpeándote mientras tú no puedes moverte.', 'https://www.roochub.com/classes/champion', false, array[]::text[]);
end
$IMPERIUM$;
