[ok] guide 'lord-knight-build' (ragnarok-origin-classic) -> 10 items. SQL en stdout.
do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'lord-knight-build');
  delete from public.guides where game_id = v_game and slug = 'lord-knight-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'lord-knight-build', 'Lord Knight: build para PvP y GvG', 'Build de Lord Knight para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de los tres árboles de habilidades, el combo de combate, y el equipo de cartas y mascota recomendado para PvP 5v5 y GvG.', 3, false, 'El bruiser que no necesita que nadie lo cubra', 'El Tyr Cup sigue en marcha, y si vas a subir un personaje de la rama Swordsman con la mira puesta en PvP y GvG, Lord Knight es la opción para quien prefiere resolver la pelea con sus propias manos. Esta guía reúne el orden de habilidades de tus tres árboles, el combo que decide un enfrentamiento, y el equipo de cartas y mascota que completa el build.

A diferencia del Paladin, aquí no hay escudo, ni Devotion, ni curación que llegue de un compañero: Lord Knight resuelve todo con su propio kit. Aura Blade y Concentration te dan la ventana de daño, Clashing Spiral remata, Berserk cierra la pelea cuando ya la tienes ganada, y Tension Relax e Iron Will son tu única red de seguridad. Es una clase que castiga los errores de timing con dureza — pero que, bien jugada, no depende de nadie más para ganar su propio duelo.

Todo el reparto de estadísticas también sale de tu propio kit: Sturdy Strike, tu golpe principal del árbol Knight, calcula su daño directamente a partir de tu VIT — así que ese stat no es solo aguante, también es parte de tu daño. A partir de ahí, esta guía te lleva paso a paso por los tres árboles, el combo, y el equipo recomendado.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_14.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué Lord Knight', 'Antes de repartir el primer punto, entiende qué tipo de personaje estás construyendo: Lord Knight es el bruiser final de la rama Swordsman → Knight, un melee que reparte daño constante y aguanta en primera línea sin depender del apoyo de nadie más — a diferencia del Paladin, aquí no hay escudo, ni Devotion, ni curación de aliado. Tu supervivencia sale de tu propio kit (Iron Will, Berserk, Tension Relax) y tu daño sale de golpes porcentuales brutales sumados a tu ATK plano.

La ficha oficial de la clase la describe como rol Melee/Tank con stats favorecidos STR, AGI y VIT — pero antes de repartir por ahí a ciegas, mira la fórmula de una de tus propias habilidades: Sturdy Strike, tu golpe base del árbol Knight, calcula su daño como (1 + VIT/300) × 500% + 500. Eso significa que cada punto de VIT no solo te da HP y aguante: también sube directamente el daño de una de tus habilidades más usadas. Por eso VIT va primero en el reparto — multiplica tu daño y tu supervivencia a la vez. Después de VIT, reparte en STR, tu ATK plano base y la munición detrás de cada golpe porcentual, y deja AGI para el final: sube ASPD, CRIT y FLEE, agradable pero no imprescindible cuando tu daño real viene de Aura Blade, Clashing Spiral y Berserk, no de tus ataques básicos sueltos.', 'https://www.roochub.com/classes/lord_knight', false, array[]::text[]),
    (v_guide, 2, 'Árbol Swordsman (1er trabajo)', 'El árbol de Swordsman es el mismo para todo el que empieza por esta rama — Knight, Crusader, y sus evoluciones — así que si ya conoces el build de Paladin, este primer tramo te sonará. Aun así importa: aquí sientas la base de ataque físico antes de pasar a Knight y, después, a Lord Knight. Este es el orden recomendado.

• Sword Mastery al máximo — +30 de PATK permanente mientras llevas espada equipada. Es pasivo y no cuesta nada mantenerlo al día.
• Bash al máximo — tu primer golpe de verdad: 350% + 200 de daño físico (PDMG) a un único objetivo, y suma +15 de HIT para no fallar contra rivales esquivos.
• Fatal Blow al máximo — +25% de probabilidad de aturdir cada vez que conectas ese mismo Bash.
• Increase Recuperative Power al máximo — tu regeneración de HP pasiva pasa a restaurar 50 puntos fijos + 1% de tu HP máx. cada 10 segundos. Nada vistoso, pero lo necesitas antes de que tu HP empiece a escalar en las siguientes fases del build.
• Magnum Break (con unos pocos puntos alcanza) — 250% + 100 de daño físico de elemento Fuego a hasta 10 objetivos a tu alrededor, con empuje incluido. No es prioridad, pero unos pocos puntos rinden mucho en peleas de gremio donde el rival se amontona.
• Berserk, la versión barata de 1er trabajo (1 punto) — solo +10 de PATK permanente, pero por un único punto no hay motivo para saltárselo.

Provoke y Endure quedan para el final si te sobran puntos: los dos rinden casi solo contra monstruos, y en combate contra jugadores apenas se notan.', 'https://www.roochub.com/classes/lord_knight', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Swordman_kuangJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_NuBao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_JianXiShuLianDu.webp']::text[]),
    (v_guide, 3, 'Árbol Knight (2do trabajo)', 'Knight es tu segundo trabajo, y aquí el camino se separa del Crusader/Paladin: no hay escudo, no hay Grand Cross, no hay soporte. Todo lo que ganas aquí es capacidad de aguante y de golpe. Sigue este orden.

• Spear Mastery al máximo — +40 de PATK permanente, +10 adicionales si vas montado. Es la base de daño físico de todo este segundo tramo.
• Sturdy Strike al máximo — tu golpe principal en esta fase: (1 + VIT/300) × 500% + 500 de daño físico Neutral a un único objetivo, y además te otorga un +10% de reducción de daño físico cada vez que lo usas. Cuanto más VIT lleves, más pega y más aguantas — la razón por la que esta clase prioriza VIT desde el primer punto.
• Lion Roar al máximo (requiere Sturdy Strike nivel 5) — tu AoE de esta fase: 750% + 600 de daño físico Neutral a hasta 10 objetivos cercanos, con un 20% de ralentización durante 3 segundos. También lleva una pasiva: 10% de probabilidad de activar un efecto adicional (Lion Howling) cada vez que te golpean, con 4 segundos de reutilización interna.
• Iron Will al máximo (requiere Lion Roar nivel 5) — tu red de seguridad: cuando tu HP cae por debajo del 30%, se activa automáticamente un escudo que absorbe daño equivalente al 20% de tu HP máx. durante 10 segundos, con 45 segundos de reutilización a nivel máximo.

Si te sobran puntos después de este núcleo, repártelos en Riding (1 punto, acceso a montura) y Cavalier Mastery (hasta el máximo, entre +8% y +40% de velocidad de movimiento montado según nivel) para mejorar tu movilidad en GvG, y si aún tienes margen, en Brandish Spear o Spear Stab para sumar más daño en área. Sword Quicken (ASPD +35% durante 240 segundos) y su puerta de entrada a Bowling Bash son una alternativa válida si prefieres un perfil más rápido y menos tanque, pero con el reparto de puntos de esta guía no llegas a ambos caminos a la vez — elige uno.', 'https://www.roochub.com/classes/lord_knight', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Swordman_MaoXiShuLianDu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_JianDingDaJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_ShiZiFenXun.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_GangTieYiZhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_QiChengShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_QiBingXiuLian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_QiChengGongJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_ChangMaoCiJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_JianGongSuZengJia.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_GuaiWuHuJi.webp']::text[]),
    (v_guide, 4, 'Árbol Lord Knight (Trans. 2nd) — el núcleo del build', 'Esta es tu clase final (Trans. 2nd), donde todo lo anterior converge en el Lord Knight que domina la línea de frente. Sigue el orden con disciplina — aquí no hay escudo ni aliado que te cubra: cada habilidad de este árbol existe para que resuelvas la pelea tú solo.

• Aura Blade al máximo — tu buff permanente de combate: durante 120 segundos, cada ataque tuyo suma 700 + (10 × tu Nivel Base) de daño físico que ignora la defensa del rival, aumenta tu daño físico un 10% adicional, y ralentiza un 20% la velocidad de movimiento del objetivo golpeado durante 3 segundos. Actívalo SIEMPRE antes de entrar en la pelea — no sirve de nada a mitad de intercambio.
• Concentration al máximo — tu otro buff de apertura: +50 de HIT y +45% de ATK de arma durante 120 segundos, a cambio de un -25% en tu propia PDEF. Actívalo junto a Aura Blade antes de la pelea, pero ten en cuenta esa bajada de defensa si el equipo rival lleva mucho daño físico encima — no es gratis.
• Clashing Spiral al máximo — tu ejecutor de objetivo único: hasta 2000% de daño físico Neutral (el multiplicador en PvP baja a 500%) e inmoviliza al rival durante 1 segundo al impactar. Resérvalo para rematar a alguien ya dañado o para trabar a quien intenta huir, no lo gastes como un golpe suelto más.
• Berserk, la versión de Trans. 2nd (hasta el máximo con 5 puntos) — tu botón de todo o nada: te cura por completo, sube tu HP máx. al 150%, y te da +100% de PATK base y de arma, más +25% de velocidad de movimiento. El precio es que pierdes un 3% de tu HP máx. cada segundo mientras dura, y se corta sola si bajas del 10% de HP o pasan 15 segundos. Si llevas espada, además ganas +30% de ASPD y +25% de daño crítico durante 15 segundos; si llevas lanza, en su lugar ganas -100% de tiempo de lanzamiento fijo y -50% de reutilización global durante 8 segundos. Actívalo para cerrar una pelea ya decidida, nunca para abrir una que todavía puedes perder.
• Tension Relax (hasta donde te alcancen los puntos, máximo 5) — tu recuperación de emergencia: restaura un 30% de tu HP máx. al instante y otro 12% por segundo durante los siguientes 5 segundos, casi un 90% de tu vida total si lo dejas completarse. Es lo que te permite sobrevivir al desgaste que deja Berserk detrás.
• Rune of Faith (1 punto) — barato y siempre rentable: elimina algunos efectos de estado activos y te da inmunidad a nuevos efectos de estado durante 2 segundos. Un único punto por una salida de emergencia contra aturdimientos o inmovilizaciones.

Si después de todo esto te sobra algún punto, repártelo en Parry (35% de probabilidad de parry de daño físico durante 60 segundos activado, con una versión pasiva más débil del 10% siempre presente) o en Head Crush → Joint Beat, que encadena sangrado y un proc pasivo cada vez que usas otra habilidad.', 'https://www.roochub.com/classes/lord_knight', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Swordman_LingQiJian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_JiZhongGongJi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_LuoXuanJiCi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_KuangNuZhiQiang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_JiSuHuiFu.webp', 'https://www.roochub.com/icons/UI_icon_item_fuwenshi03.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_ShuangJianGeDang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_ShangHaiZengYa.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Swordman_QiaoDa.webp']::text[]),
    (v_guide, 5, 'Tu combo principal', '1. Antes de entrar en combate, activa Concentration y Aura Blade — las dos duran 120 segundos y todo tu combo depende de esa ventana de HIT, ATK de arma y daño extra por golpe. Nunca las actives a mitad de intercambio: para entonces ya perdiste la parte que más rinde.
2. Empieza a golpear con tus ataques básicos, ya reforzados por Aura Blade (que ignora defensa y ralentiza a quien golpeas), mientras buscas el momento de rematar.
3. En cuanto tengas vía libre, suelta Clashing Spiral sobre tu objetivo: el impacto lo inmoviliza 1 segundo, perfecto para trabar a alguien que intenta escapar o para asegurar el resto de tu combo sin que se mueva.
4. Si la pelea se alarga o necesitas resolverla ya, activa Berserk: cura completa, HP al 150% y +100% de PATK durante hasta 15 segundos (se corta antes si bajas del 10% de tu HP). Es tu botón de todo o nada — actívalo solo cuando la pelea ya esté decidida a tu favor, no para abrirla.
5. En cuanto termine el subidón de Berserk (o si tu HP cae demasiado durante él), usa Tension Relax de inmediato para recuperar un 30% de tu HP máx. al instante y otro 12% por segundo durante 5 segundos más.', 'https://www.roochub.com/classes/lord_knight', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Aquí tienes el equipo de cartas que completa el build, elegido por cómo encaja con el kit de Lord Knight: golpes porcentuales constantes, VIT como stat clave, y ninguna red de seguridad externa (a diferencia del Paladin, aquí no hay Devotion que te cubra). Por la convención de dos décadas que arrastra esta franquicia, cada carta suele caer del monstruo o jefe que comparte su nombre — tómalo como referencia orientativa, no como un dato de drop confirmado por un parche concreto de ROOC.

• Gryphon (Rara, Arma) — FLEE +2, CRIT +7, y un 8% de probabilidad en cada ataque físico de lanzar automáticamente un Bowling Bash Nv.5 (CD: 0,5s; la probabilidad se acumula con varias copias). Es la carta más temática de esta lista: Bowling Bash es una de tus propias habilidades del árbol Knight, así que esta carta literalmente te la dispara gratis de vez en cuando.
• Doppelganger (Épica, Arma) — ASPD +10%, AGI +5, CRIT +5 y +12% de daño crítico; en set, +2% de ASPD adicional. Acelera tanto tus ataques básicos, ya reforzados por Aura Blade, como tu ventana de Concentration.
• Drake (Épica, Arma) — +12% de daño físico y mágico; en set, +3% de ATK de arma. Daño plano sin condiciones, siempre rinde.
• Orc Hero (Épica, Cabeza superior) — VIT +8 y, cada 6 segundos, elimina el Aturdimiento activo y te da inmunidad a Aturdimiento durante 4 segundos; en set, +3% de daño físico. La inmunidad a aturdimiento es oro puro para una clase que necesita mantenerse pegada al rival para que Clashing Spiral y Berserk rindan.
• Orc Lord (Épica, Armadura) — al recibir ataques físicos, refleja un 20% de ese daño a quien te golpeó, +0,2% adicional por cada punto de VIT que lleves (máximo 40%), con 4 segundos de reutilización; en set, +3% de reducción de daño físico. Con VIT como tu stat principal, este reflejo escala solo con el resto de tu build.
• Horn (Rara, Mano secundaria) — reduce un 20% el daño físico que recibes; en set, +1% de resistencia a criaturas pequeñas. Cae de un monstruo de campo corriente, así que es de las piezas más accesibles de toda la lista.
• Steel Fur Grizzly (Rara, Cabeza superior) — VIT +5, y cuando tu HP baja del 30%, el daño que recibes fuera de efectos de estado se reduce otro 10% adicional, sin tiempo de reutilización; en set, +1% de HP máx. Encaja directamente con Berserk, que te deja igual de bajo de HP como parte de su propio coste.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_shijiushou.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Siling.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Haidaozhiwang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Shourenyingxiong.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Shourenqiuzhang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Qiaoxingchong.webp', 'https://www.roochub.com/icons/UI_MonsterCard_gangzongjuxiong.webp']::text[]),
    (v_guide, 7, 'Mascota recomendada', 'De las 9 mascotas ya montadas en la sección de Mascotas, la que mejor encaja con Lord Knight es Dr. Owl (DPS de objetivo único, tipo Bruto). Su habilidad exclusiva, Gale Wind, dispara una flecha de viento que inflige 800% de daño físico a tu objetivo y además aumenta un 20% el daño físico que ese objetivo recibe — porcentaje que sube a 1200% de daño y +30% de daño físico recibido en el Tier 10 (2.430 Pet Shard en total repartidos entre las 10 mejoras, comprados con Poring Coins en la Pet Shop). Ese debuff de +20/30% de daño físico recibido se suma directamente sobre tu propio Clashing Spiral y tus ataques básicos reforzados por Aura Blade: es un multiplicador de daño físico sobre el mismo objetivo que ya estás golpeando, no una habilidad que compite con la tuya.

Si prefieres priorizar el aguante sobre el remate, Sohee (Soporte, tipo Semihumano) es la alternativa razonable: su Lucid Dream da +10% de ASPD, +5% de velocidad de movimiento y 2% de robo de vida durante 8 segundos (a cambio de +3 segundos de reutilización de habilidades), subiendo a +30%/+12%/5% en el Tier 10 — el mismo tipo de sustento que recomendamos para Paladin, útil aquí para compensar el desgaste de HP que deja Berserk.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_maotouyingboshi.webp', 'https://roocdb.com/pets/Pokemon_guinv.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y estos son los ajustes para tu kit de Lord Knight en cada uno.

• Blood and Gold — igual que cualquier build de Swordsman, aprovecha el momento en que el bando rival se agrupa junto al Goblin King para soltar tu Magnum Break (250% + 100 de daño Fuego a hasta 10 objetivos) y suma Lion Roar encima si el grupo sigue apelotonado.
• Shapeshift Ops — sin Devotion que cubra a un compañero, tu aporte aquí es directo: usa Clashing Spiral para inmovilizar durante 1 segundo a quien intente recoger el orbe de transformación en el bando rival, o a quien venga a interceptar al tuyo.
• Cart Contest — con Aura Blade activo y la reducción de daño físico que te da Sturdy Strike en cada golpe, aguantas bien como uno de los 3 jugadores que empujan el carro; si alguien te sale al paso cuerpo a cuerpo, Orc Lord se encarga de devolverle parte de ese daño.
• Team Deathmatch — activa Concentration y Aura Blade antes de que empiece la ronda, y guarda Berserk para cuando ya tengas a un rival por debajo de la mitad de vida: con el +100% de PATK y el remate de Clashing Spiral, cierras la ronda antes de que el resto reaccione.', 'https://www.roochub.com/classes/lord_knight', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios te pide decisiones distintas a las del 5v5. Estos son los ajustes para Lord Knight.

• Cargar el Cuerno en Vigrid Avenge — esa mecánica te desangra sin parar mientras lo llevas; entre Iron Will (el escudo que se activa solo si tu HP baja del 30%) y Tension Relax como recuperación de emergencia, aguantas la carga mejor que la mayoría de roles sin depender de que nadie te cure desde fuera.
• Defender un Crystal Pillar en Vale of Clash — Lion Roar (750% + 600 de daño en área, con ralentización) castiga a cualquier grupo que se amontone para intentar sacarte del punto, mientras Aura Blade y la reducción de daño de Sturdy Strike te mantienen plantado ahí sin ceder terreno.
• Cambios de objetivo en Stellar Clash — en el instante en que tu equipo decide saltar a un nuevo objetivo, Clashing Spiral es tu herramienta: la inmovilización de 1 segundo al impactar corta cualquier intento de reposicionarse o huir justo cuando más cuenta.
• El momento de activar Berserk en combate masivo — no lo actives nada más entrar al enfrentamiento: espera a que la pelea esté decidida o cerca de estarlo, porque el 3% de HP máx. que pierdes cada segundo te puede dejar crítico si el combate se alarga más de lo esperado.', 'https://www.roochub.com/classes/lord_knight', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan.

• Activar Berserk como apertura en lugar de cierre. Pierdes un 3% de tu HP máx. cada segundo mientras dura, y si la pelea se alarga más de lo previsto, puedes acabar muerto por tu propia habilidad en pleno subidón.
• Soltar Concentration sin pensar en el -25% de PDEF que trae consigo. Contra un equipo rival cargado de daño físico, esa bajada de defensa se nota tanto como sube tu ATK.
• Gastar Clashing Spiral como un golpe suelto más, en lugar de reservarlo para rematar a alguien ya dañado o para inmovilizar a quien intenta escapar.
• Olvidar Tension Relax después de un Berserk. Si no recuperas esa vida de inmediato, quedas por debajo del 30% de HP y a merced de cualquier segundo golpe — justo lo que Iron Will necesita para activarse, pero no querrás depender de eso como plan A.', 'https://www.roochub.com/classes/lord_knight', false, array[]::text[]);
end
$IMPERIUM$;
