do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'gypsy-build');
  delete from public.guides where game_id = v_game and slug = 'gypsy-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'gypsy-build', 'Gypsy: build para PvP y GvG', 'Build de Gypsy para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de sus tres árboles de habilidades, la rotación de buffs, debuffs y control que la define en la práctica como soporte de daño, las cartas y mascotas recomendadas, y trucos concretos para PvP 5v5 y GvG.', 14, false, 'El buff que también sabe rematar', 'El Tyr Cup sigue en marcha, y en un torneo con $1,000,000 en juego cada gremio necesita algo más que daño bruto: necesita quien reparta las canciones y los bailes que deciden una guerra de gremios antes de que empiece el primer golpe. Esta guía reúne en un solo sitio el orden de tus tres árboles de habilidades, la rotación de buffs, debuffs y control que de verdad define a esta clase, y el equipo de cartas y mascotas que completa el build.

Gypsy figura en la ficha de clases como DPS a distancia que favorece DEX, AGI e INT, y hasta cierto punto lo es: Double Strafe, Throw Arrow, Arrow Vulcan y Final Rhapsody pegan de verdad. Pero basta repasar el resto de su repertorio —Singing Voice, Battle Theme, Lady Luck, Eternal Chaos, Nibelungan''s Ring, Siegfried the Undead God, Lullaby, Loki''s Lament, Death Valley— para entender que su trabajo real en cualquier pelea de grupo es subir las estadísticas de tu equipo, bajar las del rival y controlar a quien haga falta, todo mientras sigue aportando su propio daño. Es, en la práctica, tan buffer y controladora como tiradora.

Es además la hermana directa de Minstrel dentro del mismo dúo Bard/Dancer: comparten casi todo el repertorio de habilidades de conjunto, y solo se diferencian de verdad en la pasiva que cierra cada árbol (Dance Mastery aquí, Music Mastery en Minstrel). A partir de aquí, toda la build de Gypsy explicada punto por punto.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_29.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué Gypsy', 'Antes de repartir tu primer punto, hay que ser sincero sobre lo que es Gypsy: la ficha de clases la etiqueta como DPS a distancia, favoreciendo DEX, AGI e INT, pero en cuanto repasas su repertorio completo la cosa cambia de cara. De los más de veinte hechizos y bailes que reparte entre Dancer y Gypsy, solo un puñado —Double Strafe, Arrow Shower, Throw Arrow, Arrow Vulcan, Final Rhapsody y Hip Shaker— inflige daño de verdad. Todo lo demás es buff, debuff, control o utilidad de grupo: Singing Voice, Battle Theme, Lady Luck y Nibelungan''s Ring suben las estadísticas de tu equipo; Eternal Chaos y Siegfried the Undead God trabajan sobre las del rival; Lullaby, Dazzler y Loki''s Lament son control puro; y Death Valley directamente revive a un compañero caído. Dicho de otro modo: Gypsy es DPS a distancia sobre el papel y buffer/soporte de cabo a rabo en la práctica.

Esa doble cara no es casualidad: Gypsy es la rama femenina del dúo Bard/Dancer dentro de Archer, hermana directa de Minstrel, con quien comparte casi todo el repertorio de habilidades de conjunto —la diferencia de fondo entre las dos es la pasiva que cierra su árbol: Dance Mastery para Gypsy, Music Mastery para Minstrel.

Reparte tus puntos en DEX primero: es tu stat principal de daño y de puntería (HIT). Después en AGI, para el ASPD y el FLEE que necesitas para sobrevivir siendo un rango que no aguanta impactos directos. INT queda de tercero, y no es un relleno: varias de tus habilidades de control y debuff (Eternal Chaos, Nibelungan''s Ring, Siegfried the Undead God, Lullaby, Loki''s Lament) consumen SP por segundo mientras están activas, así que sin un fondo de SP decente te quedas sin poder sostenerlas en medio de la pelea.', 'https://www.roochub.com/classes/gypsy', false, array[]::text[]),
    (v_guide, 2, 'Árbol Archer (1er trabajo)', 'El árbol de Archer es donde sientas las bases de toda tu build de daño a distancia, antes de especializarte en Dancer y, después, en Gypsy. Este es el orden que recomendamos.

• Owl''s Eye al máximo — pasivo permanente: +10 de DEX y +15% de ASPD. No cuesta nada mantenerlo al día y además es requisito para desbloquear Steady Focus (pide Owl''s Eye nivel 5), así que no hay motivo para retrasarlo.
• Double Strafe al máximo — tu primer golpe de daño real a un único objetivo: 350% + 200 de daño físico neutral.
• Arrow Shower al máximo — tu AoE de esta etapa: 300% + 100 de daño físico neutral en el área señalada, que además empuja hacia atrás a los objetivos golpeados.
• Steady Focus al máximo (tras Owl''s Eye Lv.5) — +10 de AGI y DEX durante 240 segundos. Actívalo antes de entrar en combate, igual que cualquier buff de ventana: a mitad de pelea ya has perdido parte de su valor.
• Vulture''s Eye al máximo — pasivo permanente: +14 de alcance de ataque. Como arquera, pelear desde más lejos que el rival es una ventaja que se nota en cada intercambio.
• Fetter Arrow (con 1 punto ya está al máximo) — 150% de daño físico al objetivo señalado y lo inmoviliza 3 segundos. Barato, y ya te da control desde el primer trabajo.', 'https://www.roochub.com/classes/gypsy', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Archer_EXiaoZhiYan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_ErLianShi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_JianYu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_XinShenNingJu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_CangYingZhiYan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Archer_ChongFengJian.webp']::text[]),
    (v_guide, 3, 'Árbol Dancer (2do trabajo)', 'Dancer es tu segundo trabajo, y aquí Gypsy empieza a mostrar su cara real de soporte: buena parte de estas habilidades son canciones y bailes que interpretas en solitario (a diferencia de la Duo Performance, la actuación en pareja con un Bard/Minstrel). Sigue este orden.

• Singing Voice al máximo — tu buff de más largo alcance: +95% de PDEF base para todo el grupo cercano, durante 600 segundos. Actívalo antes de la pelea y te dura prácticamente toda la partida.
• Dance Lessons al máximo — dominio del Whip: +30 de PATK permanente. Barato y sin ninguna razón para saltártelo.
• Throw Arrow al máximo — hereda el papel de Double Strafe como tu golpe principal a un único objetivo: 350% + 200 de daño físico.
• Fantasy Music al máximo — cada vez que usas una habilidad en solitario ganas una carga de Fantasy Chord (hasta 5), y cada carga suma un 1-5% a tu propio daño físico y a tu bonus de curación durante 10 segundos. Es además el requisito para desbloquear Final Rhapsody más adelante: sin 5 cargas activas, no puedes lanzarla.
• Lady Luck al máximo — sube el CRIT +10 y el daño crítico +12% de los aliados cercanos, durante 60 segundos en solitario. De los mejores buffs de daño que puedes dar a tu equipo.
• Gypsy''s Kiss (con varios puntos) — los aliados cercanos recuperan (180% de tu PATK + 600) de HP cada segundo (120% de tu PATK en PvP). Buena sustain de grupo, pero secundaria frente a los buffs de daño de arriba en una build pensada para pelear, no para aguantar.
• Amp (con varios puntos) — cada vez que usas una habilidad en solitario, dispara un efecto adicional que depende de cuál esté activa: cura de área extra si es Gypsy''s Kiss, +1-5% de daño a tus aliados si es Lady Luck, inmovilización si es Slow Grace, o daño en área extra si es Hip Shaker. Multiplica el valor de todo lo anterior, así que rinde más cuanto más desarrolladas tengas esas habilidades.
• Encore (con un par de puntos) — al terminar una habilidad en solitario, repite la última a nivel 5 durante 10 segundos más. Estira la duración de tus mejores buffs sin gastar otro cast; cuanto más hayas invertido en Amp, más vale la pena.
• Slow Grace (con algunos puntos) — reduce un 30% la velocidad de movimiento de los enemigos alrededor, durante 60 segundos en solitario. Muy útil para no dejar escapar a un objetivo marcado.
• Lullaby (con algunos puntos) — 10% de probabilidad de dormir a los enemigos cercanos, con un coste de 2 SP por segundo durante 20 segundos. Un dormido no puede hacer nada: resérvala para bloquear a la amenaza más peligrosa del equipo rival.
• Dazzler (situacional) — 15% de probabilidad de aturdir a los enemigos en su radio. Barato como control adicional, pero no es tu herramienta de CC principal.
• Hip Shaker (situacional, si sobran puntos) — en su versión en solitario golpea a los enemigos en su radio con 400% + 400 de daño físico cada 0,5 segundos, durante 60 segundos. Pega fuerte sobre el papel, pero exige quedarte plantada bailando en medio del combate — no siempre es viable en PvP.', 'https://www.roochub.com/classes/gypsy', false, array['https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_hengchangzhiyin.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_lianxiwudao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_chanjiantouzhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huanxiangyuezhang.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_nvshenzhiwen.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_weinifuwu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_suijiyingbian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_anke.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_wuwangwo.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_yaolanqu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_jingshengjianjiao.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_choulouzhiwu.webp']::text[]),
    (v_guide, 4, 'Árbol Gypsy (Trans. 2nd) — el núcleo del build', 'Esta es la joya de la corona: tu tercer trabajo (Trans. 2nd), donde todo lo anterior converge en la Gypsy que de verdad decide una guerra de gremios. Tienes catorce habilidades en este árbol —más que en cualquier otra etapa—, así que prioriza con cabeza.

• Dance Mastery al máximo — tu pasiva de fondo, obligatoria sin discusión: +20% a tu propio daño físico, -10% a tu Global Cooldown (el tiempo de reutilización compartido entre habilidades), +20% de reducción de daño físico y mágico, +15% de Max HP y +20% de velocidad de movimiento. Es la pasiva que diferencia a Gypsy de Minstrel (que lleva Music Mastery en su lugar) y, en la práctica, un pack de mejoras gratis que toca todo lo que haces.
• Battle Theme al máximo — tu buff de daño en grupo: +100 de PATK base, +100 de MATK base y +10% de PDEF/MDEF de equipo para los miembros del grupo cercanos, durante 100 segundos. Ábrela nada más empezar la pelea.
• Arrow Vulcan al máximo — tu golpe más fuerte a un único objetivo: 1200% + 300 de daño físico.
• Final Rhapsody al máximo — tu AoE de cierre: 1500% de daño físico a los enemigos cercanos, pero solo puedes lanzarla cuando tus cargas de Fantasy Music (del árbol de Dancer) llegan a 5. No la guardes esperando "el momento perfecto": esas cargas caducan a los 10 segundos si dejas de encadenar habilidades en solitario.
• Eternal Chaos (al máximo con solo 3 niveles) — reduce un 30% la defensa de todos los enemigos en su radio, con un coste de 2 SP por segundo, durante 20 segundos. Prepara el terreno para que el resto del grupo remate.
• Nibelungan''s Ring (al máximo con solo 3 niveles) — sube un 20% el daño elemental de Fuego, Agua, Viento y Tierra de los aliados cercanos, con el mismo coste de 2 SP por segundo, durante 20 segundos.
• Siegfried the Undead God (al máximo con solo 3 niveles) — sube un 20% la resistencia a alteraciones de estado de los aliados cercanos, con el mismo coste de 2 SP por segundo, durante 20 segundos. Resérvala para cuando el equipo rival vaya cargado de control.
• Loki''s Lament (con 1 punto ya está al máximo) — bloquea el uso de habilidades e ítems a todos los enemigos alrededor durante 5 segundos (los ataques básicos siguen permitidos), con un coste de 2 SP por segundo. Es una ventana muy corta: gástala en el instante exacto en que el rival vaya a curarse o a rematar a un aliado tuyo, nunca antes.
• Death Valley (1 punto) — revive a un aliado caído devolviéndole un 20% de su HP máxima. Barata y, en una guerra de gremios larga, prácticamente obligatoria tenerla disponible.
• Joyful Notes (1 punto) — te quita cualquier control que tengas encima y te da inmunidad a control durante 3 segundos. Tu único botón de pánico personal.
• Puppet Master''s Trick (con algunos puntos) — reduce todas tus estadísticas en 10 puntos y sube las de los aliados cercanos en 10 puntos, durante 180 segundos. Un sacrificio de grupo: solo tiene sentido cuando puedes permitirte jugar unos segundos más débil a cambio de que todo tu equipo pegue y aguante más.
• Puppet Dance (situacional, con algunos puntos) — te resta un 20% de tu HP actual para invocar un títere de bardo que pelea a tu lado durante 15 segundos. Un cuerpo extra en el campo, pero recuerda que sale directamente de tu propia vida.
• Don''t Hold Me Back (opcional) — reduce a la mitad la penalización de velocidad de movimiento de la Duo Performance. Solo merece puntos si de verdad juegas emparejada con un Bard/Minstrel.
• Curtain Call (1 punto, si te sobra) — se desliza hacia delante. Un pequeño reposicionamiento, nada más.', 'https://www.roochub.com/classes/gypsy', false, array['https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_manmiaoshenzi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_zhanguzhengtian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_aoyijianluanwu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huanxiangkuangwuqu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_yongyuandehundun.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_nibeilonggendejiezhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_busishenqigefolide.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_luoqidebeiming.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_huiguizhige.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_MaestroWanderer_huishengzhige.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_kuileishidebaxi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_kuileizhiwu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_BardandDancer_noyueshuwo.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_MaestroWanderer_weiyi.webp']::text[]),
    (v_guide, 5, 'Tu rotación principal: buffs, debuffs y control', 'Gypsy no tiene un combo de tres o cuatro golpes como una clase de daño puro: tiene una rotación de buffs, debuffs y control que hay que encadenar bien para que rinda. Esta es la secuencia recomendada.

1. Antes de que empiece la pelea, activa Singing Voice sobre tu grupo (dura 600 segundos, así que puedes lanzarla con margen de sobra) y Steady Focus sobre ti misma.
2. En cuanto se produzca el primer contacto, abre con Battle Theme para que todo tu equipo empiece pegando más fuerte.
3. Marca al objetivo prioritario con Eternal Chaos y, si el rival lleva equipo sensible a elementos, añade Nibelungan''s Ring para que tu grupo aproveche ese hueco de defensa con más daño elemental.
4. Ve encadenando tus habilidades en solitario (Lady Luck, Gypsy''s Kiss, Slow Grace...) sin dejar pasar más de unos segundos entre una y otra: cada uso suma una carga de Fantasy Chord, y Amp además dispara un efecto extra con cada una.
5. En cuanto acumules las 5 cargas de Fantasy Chord, dispara Final Rhapsody para rematar en área al grupo rival agrupado.
6. Contra el objetivo que más te preocupe, alterna Arrow Vulcan con Throw Arrow como relleno constante entre habilidades de conjunto.
7. Si el rival intenta reaccionar o curarse, corta con Loki''s Lament o con Lullaby para ganar la ventana que necesitas.
8. Guarda Death Valley y Joyful Notes como red de seguridad: revive a quien caiga y límpiate tus propios controles en cuanto puedas.', 'https://www.roochub.com/classes/gypsy', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Aquí tienes el equipo de cartas que completa el build. Como en el resto de la franquicia, cada carta suele caer del monstruo o jefe que lleva su mismo nombre — tómalo como referencia orientativa, no como un dato de drop confirmado para un parche concreto de ROOC.

• Doppelganger (Épica, Arma) — ASPD +10%, AGI +5, CRIT +5 y +12% de daño crítico; en set, otro +2% de ASPD. Con el ASPD y el CRIT entre tus tres stats principales, es la carta que más rinde de toda la lista. La suelta el MVP Doppelganger.
• Squidgitte (Rara, Arma) — +10% de daño crítico y +2 de CRIT; en set, otro +3 de CRIT. Una alternativa de arma centrada solo en crítico.
• Gryphon (Rara, Arma) — FLEE +2, CRIT +7, y un 8% de probabilidad de lanzar automáticamente Bowling Bash Nv.5 en cada golpe físico (CD 0,5s); en set, +3 de resistencia a CRIT. Otra opción de arma, esta con daño extra pasivo en cada intercambio.
• Zerom (Común, Accesorio) — DEX +3 y CRIT +2; en set, +5 de MATK de arma. Barata, fácil de conseguir, y sube tu stat principal.
• Orc Archer (Poco común, Accesorio) — al infligir daño físico, 3% de probabilidad de lanzar automáticamente Double Strafe al nivel más alto que tengas aprendido (no solo Nv.1); en set, +5 de MATK de arma. Con Double Strafe ya maximizado en tu árbol de Archer, esta carta te regala golpes extra gratis.
• Toad (Común, Prenda) — FLEE +5 y DEX +3, que suben a DEX +5 con Refinamiento +10; en set, +12 de MATK de arma. La pieza de prenda más alineada con tu stat principal.
• Eggyra (Común, Calzado) — +8% de recuperación de SP y +2% de Max HP; en set, +2 de MATK de arma. Con Eternal Chaos, Nibelungan''s Ring, Siegfried y Loki''s Lament consumiendo SP por segundo, esta carta ayuda a que no te quedes seca a media pelea.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Siling.webp', 'https://www.roochub.com/icons/UI_MonsterCard_saidula.webp', 'https://www.roochub.com/icons/UI_MonsterCard_shijiushou.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Jieluomi.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Shourengongjianshou.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Wawang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Zhuanzhuandan.webp']::text[]),
    (v_guide, 7, 'Mascotas recomendadas', 'De las nueve mascotas disponibles, dos encajan especialmente bien con esta build: una para el hueco activo, otra para el de asistente.

• Kitten Oracle (rol DPS de objetivo único, activa) — su habilidad Battle Blessing golpea a tu objetivo con 800% de daño físico neutral y te da a ti un +10% de velocidad de ataque; en el Tier 10 el daño sube a 1200% y suma +5% de daño crítico y +20% de probabilidad de crítico para ti. Con ASPD y CRIT entre tus stats principales, es la mascota que más se nota.
• Squidgitte (rol de soporte, asistente) — su Dance of the Sea Monster da un +15% de daño físico y mágico a los aliados cercanos durante 10 segundos, que sube a +25% en el Tier 10. Refuerza justo la faceta de buffer de daño de grupo que ya tienes con Battle Theme y Lady Luck.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_zhanbumao.webp', 'https://roocdb.com/pets/Pokemon_saidula.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y Gypsy tiene un papel claro en cada uno.

• Blood and Gold — cuando el grupo rival se amontone peleando por el Goblin King, si ya tienes las 5 cargas de Fantasy Chord, ese es el momento de soltar Final Rhapsody sobre el grupo.
• Shapeshift Ops — cuando un compañero esté a punto de recoger el orbe de transformación, usa Slow Grace sobre quien intente perseguirlo o Lullaby para dormir a quien intente interceptarlo.
• Cart Contest — mantente cerca del portador del carro con Steady Focus activo; si alguien se acerca demasiado a cuerpo a cuerpo, Dazzler puede aturdirlo lo justo para que el carro no se detenga.
• Team Deathmatch — activa Battle Theme y Lady Luck antes de que empiece el primer intercambio, y guarda Loki''s Lament para el instante en que el rival intente curarse o usar su habilidad definitiva.', 'https://www.roochub.com/classes/gypsy', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios premia decisiones distintas a las del 5v5. Estos son los trucos que marcan la diferencia.

• Cargar el Cuerno en Vigrid Avenge — no eres tú quien debería llevarlo (te falta el HP bruto de una clase tanque para aguantar el desgaste), pero Singing Voice y Battle Theme sobre quien sí lo cargue son las que le permiten sobrevivir el trayecto.
• Defender un Crystal Pillar en Vale of Clash — Eternal Chaos sobre el grupo que intente arrebatarte el punto reduce su defensa justo cuando el resto de tu equipo remata, y Slow Grace corta cualquier intento de retirada.
• Cambios de objetivo en Stellar Clash — Arrow Vulcan es tu mejor herramienta para abrir daño nada más marcarse el nuevo objetivo, y Loki''s Lament el remate perfecto si ese objetivo intenta curarse o huir con una habilidad.
• Tu posición en un combate masivo — sin el aguante de una clase tanque, mantente detrás de tu línea de batalla y reserva Curtain Call solo para reposicionarte, nunca para meterte en el cuerpo a cuerpo.', 'https://www.roochub.com/classes/gypsy', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan.

• Lanzar Final Rhapsody antes de llegar a las 5 cargas de Fantasy Music. Sin ellas ni siquiera puedes activarla, así que perder el ritmo de tus habilidades en solitario te deja sin tu mejor AoE justo cuando más lo necesitas.
• Dejar pasar demasiado tiempo entre una habilidad en solitario y la siguiente. Las cargas de Fantasy Music caducan a los 10 segundos: si te retrasas, las pierdes y tienes que empezar de cero.
• Usar Puppet Dance sin calcular tu HP restante. Perder un 20% de tu vida de golpe en mitad de un intercambio de daño te puede dejar al borde de la muerte contra cualquier rango o mago rival.
• Guardarte Loki''s Lament para más adelante en vez de usarla en el instante exacto en que el rival va a curarse o a rematar a un aliado tuyo. Es una ventana de solo 5 segundos: gastarla tarde es como no haberla lanzado.', 'https://www.roochub.com/classes/gypsy', false, array[]::text[]);
end
$IMPERIUM$;
