do $IMPERIUM$
declare
  v_game uuid;
  v_guide uuid;
begin
  select id into v_game from public.games where slug = 'ragnarok-origin-classic';
  if v_game is null then
    raise exception 'IMPERIUM: juego no encontrado: %', 'ragnarok-origin-classic';
  end if;

  -- Reemplazo idempotente. OJO: borra los pasos -> reinicia step_progress de esta guía.
  delete from public.guide_steps where guide_id in (
    select id from public.guides where game_id = v_game and slug = 'professor-build');
  delete from public.guides where game_id = v_game and slug = 'professor-build';

  insert into public.guides
    (game_id, slug, title, description, order_index, is_published, intro_title, intro, intro_images)
  values
    (v_game, 'professor-build', 'Professor: build para PvP y GvG', 'Build de Professor para Ragnarok Origin Classic pensada para el Tyr Cup. Cubre el orden de los tres árboles de habilidades (Mage, Sage y Professor), el combo de combate, las cartas y mascotas recomendadas, y trucos concretos para PvP 5v5 y GvG.', 7, false, 'El mago que gana la guerra de SP', 'El Tyr Cup sigue en marcha, y con $1,000,000 sobre la mesa cada clase necesita una build sólida antes de pisar un servidor de PvP o GvG. Si vas a subir Professor, esta guía reúne en un solo sitio el orden de tus tres árboles de habilidades —Mage, Sage y Professor—, el combo que decide un intercambio, y el equipo de cartas y mascota que completa el build.

Professor no es solo la clase de Magic DPS por excelencia: es, además, la que más habilidades reúne en todo Ragnarok Origin Classic. Solo en su tercera clase (Professor propiamente dicho) tiene 16 habilidades documentadas, sin contar las 11 de Mage ni las 14 de Sage que arrastra por el camino. Y ese tamaño no es solo cantidad: buena parte de esas habilidades forman el kit de gestión de SP y de anulación de magos rivales más completo del juego —Health Conversion, Soul Change, Drain Magic, Chant Removal, Dispel, Magic Rod—, lo que convierte a Professor en tan buen verdugo de otros lanzadores como nuke de daño puro.

Es Magic DPS, y su prioridad de estadísticas es INT primero, después DEX y por último VIT: INT alimenta directamente el porcentaje de cada hechizo de esta guía, DEX es la estadística que tradicionalmente ayuda a esta familia de clases a lanzar más rápido y a acertar más, y VIT es el colchón de HP que necesitas porque, más allá de Elemental Shield y Energy Coat, Professor no tiene ningún tanque propio que lo proteja. A partir de aquí, toda la build explicada punto por punto — terminando en el combo que de verdad decide una pelea: dejar sin SP al rival con Soul Change para que tu Weaken Mind golpee todavía más fuerte.', array['https://www.roochub.com/icons/UI_Common_Profession_Icon_31.webp']::text[])
  returning id into v_guide;

  insert into public.guide_steps
    (guide_id, order_index, title, content, source_url, is_verified, images)
  values
    (v_guide, 1, 'Por qué Professor', 'Antes de repartir un solo punto, un dato resume por qué esta build tiene tanto recorrido: solo en su tercera clase (Professor propiamente dicho) esta clase reúne 16 habilidades documentadas — más que ninguna otra clase de Ragnarok Origin Classic en su tramo final. Y eso sin contar las 11 de Mage ni las 14 de Sage que arrastra por el camino hasta llegar aquí.

Professor es Magic DPS, pero no es solo un cañón de daño: reúne el kit de gestión de SP y de anulación de magos rivales más completo del juego. Health Conversion, Soul Change y Drain Magic te mantienen con SP para seguir lanzando; Chant Removal, Dispel y Magic Rod convierten cualquier intercambio contra otro lanzador en una pelea que controlas tú. Es, a partes iguales, un nuke de área y el peor enemigo de cualquier mago rival.

Tu prioridad de estadísticas es INT primero, DEX en segundo lugar y VIT al final. INT alimenta directamente el porcentaje de cada hechizo de esta guía; DEX es la estadística que tradicionalmente ayuda a esta familia de clases a lanzar más rápido y a acertar más; y VIT es el colchón de HP que necesitas porque, más allá de Elemental Shield y Energy Coat, Professor no tiene ningún tanque propio que lo proteja. A partir de aquí, la build completa — terminando en el combo que de verdad decide una pelea: dejar sin SP al rival con Soul Change para que tu Weaken Mind golpee todavía más fuerte.', 'https://www.roochub.com/classes/professor', false, array[]::text[]),
    (v_guide, 2, 'Árbol Mage (1er trabajo)', 'El árbol de Mage es donde sientas las bases de todo el build: aquí defines qué elementos vas a usar antes de avanzar a Sage y, después, a Professor. Este es el orden de prioridad que recomendamos.

• Fire Bolt al máximo — tu bolt de referencia: en su nivel 10 hace 975% de daño mágico (MDMG) en PvP a un único objetivo (1500% + 800 en PvE). Súbelo antes que los otros dos porque, a diferencia de Cold Bolt y Lightning Bolt, con solo nivel 5 desbloqueas DOS habilidades: Fire Ball y Fire Wall.
• Fire Ball al máximo — golpea a un objetivo y salpica a hasta 10 monstruos cercanos, con 280% + 80 de daño mágico de Fuego en su nivel máximo. Tu herramienta de área más barata de mantener.
• Fire Wall (unos cuantos puntos) — crea un muro que inflige 80% + 100 de daño mágico de Fuego a quien lo cruce, dura 16 segundos y puede bloquear hasta 17 golpes. Control de zona excelente para cortar un pasillo en GvG.
• Cold Bolt hasta nivel 5 — no hace falta subirlo más: con nivel 5 desbloqueas Frost Diver, que en su nivel máximo hace 200% + 200 de daño mágico de Agua con un 65% de probabilidad de dejar al objetivo Congelado. Ese control duro vale más que subir Cold Bolt en solitario.
• Lightning Bolt hasta nivel 5 — el mismo razonamiento: te abre paso a Thunderstorm, que en su nivel máximo hace 1000% + 250 de daño mágico de Viento a hasta 10 monstruos. Un nuke de área para peleas de grupo.
• Stone Curse (unos puntos) — no necesita ningún requisito previo. En su nivel máximo hace 200% + 200 de daño mágico de Tierra con un 65% de probabilidad de Petrificar al objetivo — tu segunda opción de control duro, además de Frost Diver.
• Increase SP Recovery (unos puntos) — pasiva que restaura 30 + 2% de tu SP máximo cada 10 segundos, y sube al 150% la recuperación de los objetos de SP. Con lo que vas a gastar en Sage y Professor, conviene tenerla avanzada.
• Energy Coat (1 punto) — cuesta un solo punto y te da un escudo que reduce el daño recibido un 15% mientras tengas más de la mitad de tu SP, o un 10% por debajo de ese umbral, durante 7 segundos. Barato y siempre útil.

Soul Strike queda para el final si te sobran puntos: sus 5 golpes de 110% + 40 de daño mágico Fantasma suman un 50% extra contra No-Muertos, pero ese bonus apenas se nota en PvP.', 'https://www.roochub.com/classes/professor', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoJianShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoQiuShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_HuoYanZhiBi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BingJianShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BingDongShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_LeiJiShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_LeiBaoShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ShiHuaShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_ChanXin.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_NengLiangWaiTao.webp']::text[]),
    (v_guide, 3, 'Árbol Sage (2do trabajo)', 'Sage es tu segundo trabajo, y aquí terminas de definir el motor de daño y de SP que vas a llevar a Professor. Sigue este orden.

• Advanced Book al máximo — pasiva obligatoria: suma +25 de MATK de equipo y +5% de ASPD, y mientras lleves un libro equipado, tus ataques normales se convierten en golpes a distancia que hacen 200% de daño mágico. Es además el primer escalón para llegar a Double Cast.
• Dragonology al máximo (requiere Advanced Book nivel 3) — +10 de INT y +10 de MDEF permanentes, más un 10% de daño extra contra Dragones. El bono contra Dragones es más de PvE, pero el INT y el MDEF planos no sobran nunca, y es el segundo escalón obligatorio hacia Double Cast.
• Double Cast al máximo (requiere Dragonology nivel 3) — cuando tu Autocast dispara un Element Arrow, lo repite una segunda vez, con ese segundo golpe haciendo un 50% (75% en PvE) del daño del primero. En la práctica, el multiplicador de daño más importante de toda tu build de Autocast.
• Earth Spike al máximo — 5 terremotos instantáneos bajo el objetivo que suman 975% de daño mágico de Tierra en PvP (1500% + 800 en PvE). Con nivel 5 desbloqueas además Heaven''s Drive.
• Heaven''s Drive (requiere Earth Spike nivel 5) — golpea hasta 10 monstruos 5 veces, sumando 1000% + 225 de daño mágico de Tierra en total. Tu otro nuke de área, ideal para GvG.
• Void Bolt al máximo — 1200% + 800 de daño mágico Neutral que escala hasta 2000% cuanto más SP tengas acumulado en el momento de lanzarlo. Encaja de forma natural con todo el trabajo que vas a hacer en Professor para mantener tu SP alto.
• Drain Magic (unos puntos) — +10% de SP máximo, y durante el combate restaura un 1% de tu SP máximo cada 5 segundos. Otra pieza de tu economía de SP.
• Free Spellcasting (1 punto) — te deja moverte mientras lanzas hechizos. Un solo punto que en PvP evita que te quedes clavado en el sitio mientras cargas tu próximo golpe.
• Magic Rod (unos puntos) — convierte un 10% del daño mágico que recibes en un efecto que le quita un 50% de su SP a quien te golpeó, hasta que baje de un 10% de su propio SP máximo. Tu castigo pasivo contra cualquier mago que decida centrarse en ti.
• Spider Web (situacional) — 250% + 100 de daño mágico Neutral, inmoviliza al objetivo y dobla el primer golpe de Fuego que reciba mientras dure el efecto (hasta 5 segundos). Combínalo con tu propio Fire Bolt o Fire Ball para rematar a alguien que ya inmovilizaste.

Volcano, Deluge y Violent Gale (los tres Dominios Elementales de Fuego, Agua y Viento) dan un +10% de daño elemental a los aliados dentro de la zona y aplican Quemadura, Ralentización o Ceguera a quien entre o salga de ella — pero los cuatro Dominios (contando Land Protector, ya en el árbol de Professor) no pueden coexistir: solo el último que se lance queda activo. Son más una herramienta de equipo que una prioridad personal; deja Create Element Scroll para el final, ya que solo mejora tu tasa de éxito al crear pergaminos y no aporta nada en combate.', 'https://www.roochub.com/classes/professor', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Sage_jinhuazhishu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_longzhizhishi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_shuangbeitouzhi.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_DiZhenShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Magician_BengLieShu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_xuwuzhijian.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_shequmofa.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_ziyoushifa.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_mofachengfa.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_yiranzhiwang.webp']::text[]),
    (v_guide, 4, 'Árbol Professor (Trans. 2nd) — el núcleo del build', 'Esta es la joya de la corona: tu tercera clase (Trans. 2nd), la que convierte todo lo anterior en el Professor que domina el Tyr Cup. Con 16 habilidades propias —más que cualquier otra clase del juego en este tramo—, sigue el orden con disciplina.

• Spirit Devastation al máximo — pasiva obligatoria y permanente: +10% de daño mágico y +20% de reducción de daño mágico. Es el pilar de toda esta fase del build, así que no hay motivo para retrasarlo.
• Autocast al máximo — tus ataques normales tienen un 24% de probabilidad base de disparar automáticamente el Element Arrow que tengas aprendido, durante 60 segundos. Actívalo SIEMPRE antes de entrar en la pelea, nunca a mitad de combate, porque para entonces ya perdiste buena parte de la ventana.
• Element Insight al máximo — cada vez que haces daño mágico, tu daño de Viento, Tierra, Agua y Fuego sube un 5% durante 10 segundos, acumulable hasta 3 veces. Encadenar hechizos sin parar es lo que te deja aprovechar esta pasiva al máximo.
• Soul Change al máximo — sobre un aliado, le transfieres un 25% de tu propio SP máximo; sobre un enemigo, le drenas un 25% de su SP máximo. Con nivel 5 desbloqueas además Weaken Mind.
• Weaken Mind al máximo (requiere Soul Change nivel 5) — tu habilidad de remate. Hace 1200% + 800 de daño mágico al objetivo y le resta otros 300 de SP; cuanto más bajo esté el SP% del objetivo, más escala el daño, hasta un máximo de 2400%. Si el golpe lo mata, recuperas de inmediato un 5% de tu propio SP máximo. Úsala SIEMPRE después de haberle bajado el SP al rival con Soul Change o Magic Rod — así es como sacas el 2400% en vez de quedarte en el mínimo.
• Chant Removal al máximo — interrumpe al instante el lanzamiento del objetivo y le aplica un 20% de aumento de tiempo de lanzamiento durante 3 segundos; si el corte tiene éxito, ese aumento sube a 40% durante 6 segundos. Con nivel 3 desbloqueas además Dispel.
• Dispel (requiere Chant Removal nivel 3) — magia anuladora con 100% de probabilidad de quitarle al enemigo todos los buffs de su clase. Resérvala para un rival muy reforzado (un Paladin con Fortitude y Devotion activos, por ejemplo) antes de rematarlo.
• Psychic Wave al máximo — 1050% de daño mágico Neutral por segundo en PvP (1280% en PvE) a hasta 10 monstruos en la zona, durante 7 segundos. Tu nuke de área más pesado, perfecto para un teamfight de GvG.
• Health Conversion (unos puntos) — consume un 10% de tu HP máximo y lo convierte en un 20% de tu SP máximo. Es un botón de pánico para cuando te quedas corto de SP a mitad de pelea, no un recurso para usar por rutina: cada vez que lo activas, estás pagando con tu propia vida.
• Elemental Shield (1 punto) — un solo punto y consigues un escudo que te limpia cualquier control encima al instante, te da inmunidad a control durante 5 segundos y, además, +50% de reducción de daño físico y mágico durante esos mismos 5 segundos. Resérvalo para el momento en que de verdad te controlen, no lo malgastes como reducción de daño genérica.
• Land Protector (situacional) — crea un Dominio de Tierra donde no se pueden lanzar habilidades de área, ni tampoco puede lanzarse otro Dominio encima. Dura 40 segundos, pero recuerda que comparte la misma regla que Volcano/Deluge/Violent Gale de Sage: de los cuatro Dominios, solo el último lanzado queda activo.
• Spell Mastery (5 versiones, una por elemento más una versión ''All'') — cada una restringe tu Autocast a un único hechizo concreto (o a cualquiera, en la versión ''All''), y usarlas de forma activa las transforma temporalmente en su versión mejorada, Chant Mastery. Trátalas como una capa de optimización opcional: la propia ficha de habilidades tiene inconsistencias entre el nombre de cada versión y el hechizo al que dice restringir el Autocast, así que comprueba en el propio juego cuál es cuál antes de invertir puntos aquí — no es prioridad de esta guía.', 'https://www.roochub.com/classes/professor', false, array['https://www.roochub.com/icons/UI_Icon_Skill_Sage_jingshenggandong.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_zidongnianzhou.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_yuansulijie.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_xinshenhuhuan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_jingshenghaoruoshu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_nianzhouchaichu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_HPzhuanhuanmofaxiaoguojiechu.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_chaozirenbo.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_HPzhuanhuan.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Element_MoLiHuDun.webp', 'https://www.roochub.com/icons/UI_Icon_Skill_Sage_diyuansulingyu.webp']::text[]),
    (v_guide, 5, 'Tu combo principal', 'Tener los puntos bien repartidos no sirve de nada si no ejecutas el combo en el orden correcto. Esta es la secuencia que de verdad decide una pelea.

1. Antes de entrar en la pelea, activa Autocast — dura 60 segundos, así que actívalo con antelación, nunca a mitad de combate.
2. Abre el intercambio con Soul Change sobre tu objetivo: le drenas un 25% de su SP máximo antes de que la pelea empiece de verdad.
3. Remata con Weaken Mind. Con el rival ya con menos SP, el daño escala hasta 2400% de daño mágico cuanto más bajo esté su SP —y de paso le quitas otros 300 de SP—; si el golpe lo mata, recuperas un 5% de tu propio SP máximo al instante.
4. Si el rival intenta lanzar un hechizo para curarse o escapar, córtaselo con Chant Removal: el lanzamiento se interrumpe en el acto y, si el corte tiene éxito, se queda con un 40% más de tiempo de lanzamiento durante 6 segundos.
5. Contra varios objetivos agrupados, cambia a área: Psychic Wave o Heaven''s Drive, según lo que tengas ya desbloqueado.
6. Si te controlan a ti, Elemental Shield te limpia el control al instante, te da inmunidad 5 segundos y +50% de reducción de daño físico y mágico durante ese mismo tiempo — resérvalo para cuando de verdad lo necesites, no lo gastes como reducción de daño genérica.
7. Si te quedas sin SP a mitad de intercambio, Health Conversion te da un 20% de tu SP máximo a cambio de un 10% de tu HP máximo — solo tiene sentido si te sobra vida para pagarlo.', 'https://www.roochub.com/classes/professor', false, array[]::text[]),
    (v_guide, 6, 'Equipo recomendado — cartas', 'Este es el equipo de cartas que mejor completa un Professor centrado en daño mágico y economía de SP, elegido entre las cartas ya traducidas en la sección de Cartas de esta web.

• Dracula (Épica, ranura Arma) — suma +100 de MATK de arma y +15% de daño mágico, y trae un efecto único clave para un lanzador: el tiempo de lanzamiento no se interrumpe al recibir daño. En set, +3% de daño mágico adicional. Es, con diferencia, la carta de arma más importante de esta lista para Professor.
• Pharaoh (Épica, Cabeza superior) — reduce un 50% el costo de SP de tus habilidades y suma +8% de daño mágico; en set, otro +3% de daño mágico. Con lo mucho que gasta Professor en SP entre Autocast, Weaken Mind y compañía, esta carta es prácticamente obligatoria.
• Marduk (Rara, Cabeza superior) — +3 de INT, y cada 6 segundos consigues 1 segundo de inmunidad a Silencio (que además elimina el Silencio si ya lo tienes activo); en set, +12 de ATK de arma. Compite por la misma ranura que Pharaoh, pero merece la pena si te enfrentas a rivales que dependen de silenciarte para anularte.
• Frilldora (Poco Común, Prenda) — +3 de INT y -3% de tiempo de lanzamiento variable; en set, +5 de ATK de arma. Barata de conseguir y siempre útil para lanzar un poco más rápido.
• Vocal (Común, Prenda) — -5% de daño mágico recibido, y si refinas la prenda a +10 suma otro +3% de daño mágico propio; en set, +12 de ATK de arma. Una alternativa defensiva a Frilldora para cuando el rival lleva mucho daño mágico.
• Wraith (Poco Común, Accesorio) — +5 de MATK de arma y +1% de daño mágico; en set, otros +5 de MATK de arma. Un accesorio modesto pero accesible mientras completas el resto del equipo.
• Boa (Común, Arma) — +20 de MATK de arma y, en set, +50 de HP máximo. La carta de relleno perfecta para subir de nivel antes de conseguir Dracula: común, fácil de encontrar, y ya aporta MATK plano.', 'https://www.roochub.com/cards', false, array['https://www.roochub.com/icons/UI_MonsterCard_Degulananjue.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Falaowang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Maerduke.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Sanxi.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Huangchongzhiwang.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Eling.webp', 'https://www.roochub.com/icons/UI_MonsterCard_Qingshe.webp']::text[]),
    (v_guide, 7, 'Mascotas recomendadas', 'Dos mascotas completan el build, cada una con un rol distinto. Recuerda que cada mascota tiene 10 niveles de mejora (Pet Shard, comprados con Poring Coins en la Pet Shop): los 10 tiers completos de una misma mascota cuestan 2.430 fragmentos en total, y la Habilidad Exclusiva de cada una llega a su versión más fuerte precisamente en el Tier 10.

• Abyss Witch (DPS de Área, Semihumano) — su habilidad exclusiva, Lord of Vermilion, invoca 4 oleadas de rayo (90% de daño mágico de Viento cada una, repartido entre hasta 10 objetivos) que van acumulando un buff de daño; en el Tier 10 llega a 12 oleadas. Es la pareja natural de un Professor: una mascota que también hace daño mágico de área, igual que tu propio Psychic Wave o Heaven''s Drive.
• Teacup Rabbit (Soporte, Bruto) — su habilidad Drinks on Me rocía té causando 350% de daño mágico de Agua a 6 enemigos frontales, y además devuelve SP a su dueño cada vez que lanza una habilidad; en el Tier 10 el daño sube a 550%. Con lo que gasta Professor en SP entre Autocast, Weaken Mind y Health Conversion, esta devolución constante es justo el colchón que necesitas para no quedarte seco a mitad de pelea.', 'https://roocdb.com/en/pets', false, array['https://roocdb.com/pets/Pokemon_zhangyu.webp', 'https://roocdb.com/pets/Pokemon_chabeitu.webp']::text[]),
    (v_guide, 8, 'Trucos para 5v5 (Dimension Drill)', 'Dimension Drill reúne varios minijuegos de 5v5, y Professor tiene un papel claro en cada uno gracias a su daño de área y su capacidad de anular magos rivales.

• Blood and Gold — cuando el bando rival se agrupe junto al Goblin King, ese es el momento de soltar Thunderstorm o Psychic Wave, no de gastar tus bolts en un solo objetivo.
• Shapeshift Ops — si el portador rival del orbe de transformación intenta escapar, Frost Diver o Stone Curse lo inmovilizan (Congelamiento o Petrificación) el tiempo suficiente para que tu equipo lo alcance.
• Cart Contest — Fire Wall corta el paso a quien intente escoltar el carro rival cuerpo a cuerpo, y Land Protector sobre la zona del carro bloquea el AoE que el equipo contrario suele usar para defenderlo.
• Team Deathmatch — abre con Soul Change seguido de Weaken Mind sobre el objetivo que veas con menos recursos, y guarda Elemental Shield para el momento en que te marquen a ti.', 'https://www.roochub.com/classes/professor', false, array[]::text[]),
    (v_guide, 9, 'Trucos para GvG (guerra de gremios)', 'La guerra de gremios premia decisiones distintas a las del 5v5. Estos son los trucos que marcan la diferencia con Professor.

• Vigrid Avenge (cargar el Cuerno) — no eres tú quien debería cargarlo (tu HP no aguanta ese desgaste ni de lejos como el de un tanque), pero sí puedes limpiar el camino: Thunderstorm y Psychic Wave sobre quien intente interceptar a tu portador.
• Vale of Clash (defender un Crystal Pillar) — Land Protector sobre el pilar niega el AoE de los magos rivales que intenten arrasarlo de golpe, y Fire Wall corta el acceso cuerpo a cuerpo.
• Stellar Clash (cambios de objetivo) — usa Dispel primero sobre el objetivo prioritario para quitarle cualquier buff de clase activo, y luego remata con el combo Soul Change + Weaken Mind, que pega más fuerte cuanto más bajo esté ya su SP.
• El papel que nadie más cubre — Chant Removal y Magic Rod convierten a Professor en la pesadilla de cualquier mago o sanador rival que intente lanzar sobre el frente de batalla; ese trabajo de anulación vale tanto como tu propio daño.', 'https://www.roochub.com/classes/professor', false, array[]::text[]),
    (v_guide, 10, 'Errores que cuestan partidas', 'Incluso con el build perfecto sobre el papel, estos son los fallos que más partidas cuestan.

• Lanzar Weaken Mind antes de bajarle el SP al rival con Soul Change o Magic Rod — te pierdes la parte del daño que escala con el SP% bajo del objetivo, hasta 2400% en vez de quedarte en el mínimo de 1200% + 800.
• Activar Autocast a mitad de combate en vez de antes de entrar: pierdes toda la primera parte de la pelea sin la probabilidad de proc del 24%.
• Gastar Elemental Shield como reducción de daño genérica cuando no hay ningún control entrante, en vez de reservarlo para cuando de verdad te inmovilicen o aturdan.
• Ignorar Chant Removal contra un rival a punto de rematarte con su propio hechizo largo — cortarlo a tiempo puede salvarte la pelea entera.
• Abusar de Health Conversion sin necesidad real: ese 10% de HP que le restas a tu propia vida puede ser justo el margen que te falta cuando llega la siguiente ronda de daño.', 'https://www.roochub.com/classes/professor', false, array[]::text[]);
end
$IMPERIUM$;
