do $do$
declare
  gid uuid;
  hid uuid;
begin
  select id into gid from public.games where slug='call-of-dragons';
  -- vardun
  select id into hid from public.heroes where game_id=gid and slug=$hb$vardun$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Vardun es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Vardun en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Mages totalmente aquí para lidiar con la Infantry, ya que necesitas daño mágico con él$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Vardun$hb$, $hb$Cantaman, por sus increíbles debuffs y su sinergia para penetrar la mayoría de la defensa y cumplir el rol de lidiar con el dominio de la Infantry, es la mejor opción (Mira la build completa aquí).

Seluna es increíblemente versátil y además tiene potencial de daño que querrás emparejar aquí (Mira la build completa aquí).

Liliya puede funcionar potencialmente, pero honestamente no veo demasiada razón realista para que alguien ande por ahí con un Vardun al máximo y sin Cantaman (Mira la build completa aquí).

Theia si tienes problemas de supervivencia, pero a estas alturas estoy más teorizando que haciendo algo que tenga sentido real, ya que Cantaman y Seluna son las únicas opciones de verdad (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Doom Bracers sería en realidad mi segunda opción, simplemente por el daño difuso que escalará increíblemente bien con Yun Ming cuando se usa con la war pet Flaming Manticore. Phoenix Eye sería en realidad mi segunda opción, simplemente por el daño difuso que escalará increíblemente bien con Yun Ming cuando se usa con la war pet Flaming Manticore.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Vardun (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Vardun con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Vardun$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Vardun que tienen sentido cuando lo usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. He visto por ahí algunos árboles de talentos de velocidad que creo que son de uso de nicho y aceptables, pero el árbol de habilidades es el que más sentido tiene, ya que de todas formas puedes inmovilizar a los enemigos y la Infantry no es demasiado difícil de perseguir; tu gran dificultad no es alcanzarlos o escapar, tu gran reto es derribarlos$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/05/vardun-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Vardun te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- cantaman
  select id into hid from public.heroes where game_id=gid and slug=$hb$cantaman$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Cantaman es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Cantaman en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Mages totalmente aquí para lidiar con la Infantry, ya que necesitas daño mágico con él$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Cantaman$hb$, $hb$Vardun está diseñado para trabajar tan bien con sus debuffs y saltarse tanta defensa que cualquier marcha de Infantry está en problemas, y debería ser tu opción principal (Mira la build completa aquí).

Velyn, en caso de que separes a Vardun y lo lleves con Seluna, Velyn sería el héroe elegido para emparejar con Cantaman (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Doom Bracers sería en realidad mi segunda opción, simplemente por el daño difuso que escalará increíblemente bien con Yun Ming cuando se usa con la war pet Flaming Manticore. Phoenix Eye sería en realidad mi segunda opción, simplemente por el daño difuso que escalará increíblemente bien con Yun Ming cuando se usa con la war pet Flaming Manticore.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Cantaman (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Cantaman con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Cantaman$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Cantaman que tienen sentido cuando lo usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. A menos que seas uno de los pocos jugadores que realmente hace Rally con él, en campo abierto lo usarías normalmente como comandante secundario con Vardun, así que el árbol de talentos no es importante; pero si los separas en dos marchas y él liderara la otra, el árbol de habilidades es siempre tu elección como se muestra aquí$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/05/cantaman-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Cantaman te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- seluna-legendary
  select id into hid from public.heroes where game_id=gid and slug=$hb$seluna-legendary$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Seluna Legendary es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Seluna Legendary en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Las unidades voladoras (flying) son su especialidad y puede emparejarse prácticamente con todo ahí$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Seluna Legendary$hb$, $hb$Atheus es una pareja absolutamente excelente con ella, ya que ambos escalan a partir de sus ataques básicos y él proporciona la rage para su burst para seguir generando bola de nieve, y juntos tienen bastante buena velocidad de marcha (Mira la build completa aquí).

Bertrand también es una pareja útil con unidades flying mágicas (Mira la build completa aquí).

Thundelyn no es en primer lugar un héroe de unidades flying, pero con unidades terrestres veo algunas sinergias y mecánicas interesantes la verdad (Mira la build completa aquí).

Yun-Ming funciona con todo y ambos juntos formarán una marcha F2P bastante útil (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Phoenix Eye -. – -.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Seluna Legendary (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Seluna Legendary con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Seluna Legendary$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Seluna Legendary que tienen sentido cuando la usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Si la usaras como comandante principal, este es el árbol de talentos que tiene sentido (¡incluso con unidades totalmente mágicas no entrarías en el árbol mágico!)$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/seluna-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Seluna Legendary te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- joren
  select id into hid from public.heroes where game_id=gid and slug=$hb$joren$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Joren es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Joren en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Infantry es la clave con él$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Joren$hb$, $hb$Ellanir, como todos los héroes que salen juntos, es una opción fuerte, aunque si realmente quieres un setup agresivo de campo abierto, Joren se empareja mejor con héroes más ofensivos la verdad (Mira la build completa aquí).

Agnar es una gran elección con cavalry que hará un montón de daño y castigará casi todo lo que se cruce (Mira la build completa aquí).

Kuma es un setup alternativo bueno para mucha acción de campo abierto pero un poco más orientado a la sostenibilidad sin ser demasiado glass-cannon (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Bladeguard siempre encaja bien con Infantry, especialmente cuando quieres ser un poco más resistente. Dragonscale Armor siempre encaja bien con Infantry, especialmente cuando quieres ser un poco más resistente.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Joren (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Joren con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Joren$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Joren que tienen sentido cuando lo usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Esta build de talentos puede verse rara ya que no entramos en la habilidad final de ningún árbol, pero por la forma en que funcionan sus mecánicas centrales, esta es la mejor opción en mi opinión para realmente aprovechar y generar bola de nieve con sus mecánicas de Parry y contraataque con lo que el combate de campo abierto le exige$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/03/call-of-dragons-joren-talent-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Joren te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- ellanir
  select id into hid from public.heroes where game_id=gid and slug=$hb$ellanir$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Ellanir es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Ellanir en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Infantry es la clave con ella, pero como comandante de Garrison funciona bien con lo que tengas ahí (naturalmente)$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Ellanir$hb$, $hb$Joren, como todos los héroes que salen juntos, es una opción fuerte, pero ella también ofrece otras opciones donde puede usar su increíble kit defensivo (Mira la build completa aquí).

Kuma es una buena alternativa y juntos pueden hacer mucho daño, pero no esperes que aguanten lo suficiente, así que elige tu salida o tus batallas con cuidado (Mira la build completa aquí).

Goresh es una pareja muy interesante en mi opinión la verdad, ya que sus kits se complementan excepcionalmente bien (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Dragonrift siempre encaja bien con Infantry, especialmente cuando quieres ser un poco más resistente. Dragonscale Armor siempre encaja bien con Infantry, especialmente cuando quieres ser un poco más resistente.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Ellanir (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Ellanir con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Ellanir$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Ellanir que tienen sentido cuando la usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Este es el setup de talentos que más sentido tiene en mi opinión$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/04/call-of-dragons-ellanir-talent-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Ellanir te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- agnar
  select id into hid from public.heroes where game_id=gid and slug=$hb$agnar$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Agnar es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Agnar en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Cavalry es la clave con él, idealmente con múltiples marchas$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Agnar$hb$, $hb$Freya es la elección obvia aquí con él, ya que están diseñados para escalarse mutuamente (Mira la build completa aquí).

Mardok también es una buena alternativa para aquellos de ustedes que no tienen el presupuesto de un país pequeño en el juego, donde puedes tener a Mardok como principal con Agnar como segundo y aun así tener bastante éxito con un presupuesto reducido (Mira la build completa aquí).

Falgrim funciona si tienes varias marchas de cavalry y usas a tu Freya como comandante en la otra (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Winters Edge es una buena elección por ahora si no tienes Winters Edge a tu disposición. Sorlands Blade es una buena elección por ahora si no tienes Winters Edge a tu disposición.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Agnar (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Agnar con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Agnar$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Agnar que tienen sentido cuando lo usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Los mejores talentos aquí para mí son aquellos en los que vas a por la velocidad de marcha sin descanso para el combate PvP de mapa abierto, donde alcanzarás e inmovilizarás cualquier objetivo que quieras con él$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/02/agnar-talent.jpg$hb$]::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Agnar te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- freya
  select id into hid from public.heroes where game_id=gid and slug=$hb$freya$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Freya es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Freya en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Cavalry es la clave con ella$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Freya$hb$, $hb$Agnar es obviamente la mejor elección aquí y está diseñado para ser tremendamente fuerte junto a Freya. Literalmente acaban con todo al inicio de la G5 a menos que se lancen counters más adelante (Mira la build completa aquí).

Mogro es una pareja menos obvia pero igualmente efectiva, ya que los debuffs funcionan juntos y él puede ayudar a Freya a activar su daño de habilidad varias veces (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Sorlands Blade funciona con el efecto de cobardía para aumentar el daño si tienes uno por ahí. Oath of Stormpeak funciona con el efecto de cobardía para aumentar el daño si tienes uno por ahí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Freya (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Freya con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Freya$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Freya que tienen sentido cuando la usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Este es el árbol de talentos más razonable aquí para ella. Es asombroso cómo los creadores de contenido hacen como 6 setups diferentes y dicen que así es como hay que construirla solo para tener todas las posibilidades cubiertas. Personalmente creo que otras versiones desequilibran demasiado su kit hacia direcciones específicas, pero eso es solo mi opinión.$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/02/freya-talent.jpg$hb$]::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Freya te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- seluna
  select id into hid from public.heroes where game_id=gid and slug=$hb$seluna$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Seluna es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Seluna en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Las unidades voladoras (flying) son su especialidad y puede emparejarse prácticamente con todo ahí$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Seluna$hb$, $hb$Ffraegar sería una gran pareja aquí si quieres una marcha flying fuerte y poderosa con Seluna como secundaria (Mira la build completa aquí).

Kregg es un gran héroe flying y con Seluna tienes una pareja económica (Mira la build completa aquí).

Theia se trata de unidades flying y, aunque no le veo demasiado sentido a emparejarlas entre sí, funcionaría en términos de sinergia (Mira la build completa aquí).

Bertrand con mages flying y ella como secundaria es sin duda también una pareja que podrías considerar (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$En realidad no usarías su versión épica como comandante principal, así que recomendar artefactos aquí no es más que teorizar.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Seluna (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Seluna con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Seluna$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Seluna que tienen sentido cuando la usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. En realidad no la usarías como comandante principal de tu marcha y siempre como secundaria, pero aquí está el árbol de talentos que usarías con ella como comandante principal en su forma legendaria$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/seluna-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Seluna te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- ruby
  select id into hid from public.heroes where game_id=gid and slug=$hb$ruby$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Ruby es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Ruby en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Marksman totalmente con ella$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Ruby$hb$, $hb$Kaelan está diseñado para trabajar junto a Ruby y son el inicio de los héroes de la Generación 5 y funcionan increíblemente bien juntos (Mira la build completa aquí).

Sibyl, como marksman de G4, es una pareja que tiene sentido ya que su kit en su mayor parte funciona junto al de Ruby (Mira la build completa aquí).

Falgrim puede ser un setup más defensivo para que Ruby aguante un poco más, pero honestamente no veo demasiadas ocasiones en las que quieras hacer eso y en las que tengas un Falgrim perfectamente bien construido disponible como héroe secundario pero ninguna de las otras parejas (Mira la build completa aquí).

Mu Hsiang es universalmente un héroe que puede emparejarse literalmente con cualquier héroe y puede ser un buen reemplazo aquí con Ruby (Mira la build completa aquí).

Kinnara es una pareja súper económica pero aplica DEF Break en los ataques normales, lo que sorprendentemente tiene una fuerte sinergia con Ruby (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Echemos un vistazo ahora a los numerosos artefactos que puedes usar. Hemos probado muchos de ellos y algunos tienen una sinergia increíble y otros están más por las stats, pero sin importar qué artefactos tengas disponibles, encontrarás el que mejor funcione. Revisa también la tier list completa de todos los artefactos aquí para ver cuáles valen la inversión en general.

Roaring Rager es un artefacto ofensivamente viable que siempre da en el clavo con marksman y si aún no tienes su artefacto y este bien construido, es más que una opción a considerar. Shadowblades es un artefacto ofensivamente viable que siempre da en el clavo con marksman y si aún no tienes su artefacto y este bien construido, es más que una opción a considerar.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Ruby (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Ruby con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Ruby$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Ruby que tienen sentido cuando la usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Este es el setup de árbol de talentos que más sentido tiene con ella. He visto los más ridículos, como builds de 40% de velocidad de marcha o setups raros de árbol de Precisión, así que ten en cuenta que algunos creadores de contenido los crean solo por crear, no porque tenga sentido (de verdad no me gusta señalar a nadie y prefiero centrarme en mi trabajo aquí, pero si veo contenido ridículo que solo podría guiar mal a los jugadores, necesito decir algo). Así que, en resumen, no compliques de más su kit directo y aprovecha su fuerza con una build de árbol marksman y verás cómo rinde la nueva generación de héroes; lo hacen verdaderamente increíble.$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/ruby-talent-tree-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Ruby te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- kaelan
  select id into hid from public.heroes where game_id=gid and slug=$hb$kaelan$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Ranking actual – ¿Kaelan es tier S, tier A o tier D?!$hb$, $hb$Mira cómo se posiciona Kaelan en los distintos modos de juego de Call of Dragons en mi tier list actual aquí y asegúrate también de estar usando la mejor facción en Call of Dragons o podrías afectar tu progreso de forma muy negativa – tengo una guía actualizada sobre las mejores facciones en Call of Dragons aquí

¡Importante! No te pierdas Gemas, Llaves, Boosters y Aceleradores gratis y revisa con frecuencia mi lista de códigos de regalo activos para Call of Dragons aquí.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Orden de habilidades$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Mejores tipos de tropa$hb$, $hb$Marksman cuando se empareja con Ruby, pero también puede emparejarse con cavalry, así que la pareja dicta las tropas aquí, no al revés$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Mejores parejas de héroe para Kaelan$hb$, $hb$Ruby es la mejor comandante principal para usar con él, simplemente porque Kaelan potencia su kit y su kit activa las habilidades de él demasiado bien como para hacer que cualquier otra pareja sea ni remotamente tan fuerte (Mira la build completa aquí).

Urag es una pareja de nicho con cavalry que se ve por ahí de vez en cuando. Puede ser divertida, puede funcionar, pero al final del día una pareja completa de marksman G5 es por mucho más fuerte que esta (Mira la build completa aquí).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Mejores artefactos$hb$, $hb$Esto depende de con qué héroe lo emparejes, ¡Kaelan no es un héroe para usar como comandante principal!$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Mejores sinergias de mascota para Kaelan (NUEVO)$hb$, $hb$Con el nuevo sistema de war pets en Call of Dragons también es importante emparejar a Kaelan con la mascota correcta para obtener más sinergias. Revisa también la tier list completa de todas las war pets en Call of Dragons aquí para ver cuáles valen la inversión en general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Mejores builds para Kaelan$hb$, $hb$A continuación encontrarás las builds de árbol de talentos para Kaelan que tienen sentido cuando lo usas como comandante principal en cualquier legión en Call of Dragons. Consulta también la descripción debajo de cada árbol de talentos, ya que explico una ruta general sobre cómo deberías gastar tus talentos ahí + algo de contexto adicional para cada build de talentos que muy probablemente apreciarás. Si LO usaras como comandante principal, este es el camino a seguir. Pero honestamente es un comandante secundario de pies a cabeza, así que no te compliques realmente con él como comandante principal y una build de talentos$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/ruby-talent-tree-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusión$hb$, $hb$Espero que esta guía para construir a Kaelan te haya ayudado a invertir sin desperdiciar mucho tiempo y recursos. Si te gustó o tienes más preguntas (o tal vez también anotaciones que crees que deberían añadirse aquí en esta guía), no dudes en publicarlas abajo en la sección de comentarios. Gracias por leer y que tengas un gran día.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
end
$do$;