do $do$
declare
  gid uuid;
  hid uuid;
begin
  select id into gid from public.games where slug='call-of-dragons';
  -- vardun
  select id into hid from public.heroes where game_id=gid and slug=$hb$vardun$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Vardun S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Vardun is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Mages all the way here to dealw tih infantry as you need magic damage with him$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Vardun$hb$, $hb$Cantaman for the amazing debuffing and synergy of penetrating through a majority of defense to fulfil the role of dealing with the infantry dominance is the best choice (See full build here ).

Seluna is incredibly versatile and has also damage-dealing potential that you want to pair up here (See full build here ).

Liliya can potentially also work but honestly I don’t see too much realistic cause for someone running around with a maxed Vardun and no Caraman (See full build here ).

Theia if you struggle with survivability but I am more theorycrafting at this point that actually making sense as Cantaman and Seluna are the only real choices (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Doom Bracers would be my second choice actually just because of the diffused damage that will scale incredibly well through Yun Ming when used with the Flaming Manticore war pet. Phoenix Eye would be my second choice actually just because of the diffused damage that will scale incredibly well through Yun Ming when used with the Flaming Manticore war pet.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Vardun (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Vardun with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Vardun$hb$, $hb$Below you will find the talent tree builds for Vardun that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. I have seen some speed talent trees out there that I think are niche use okay-ish but the skill tree makes just most sense as you are able to lock enemies down anyway and infantry is not too hard to chase anyway and your big struggle is not to catch them or get away, your big catch is taking them down$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/05/vardun-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Vardun helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-vardun-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- cantaman
  select id into hid from public.heroes where game_id=gid and slug=$hb$cantaman$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Cantaman S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Cantaman is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Mages all the way here to dealw tih infantry as you need magic damage with him$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Cantaman$hb$, $hb$Vardun is designed to work with his debuffs so well and bypass so much defense that every infantry march out there is in trouble and should be your primary choice (See full build here ).

Velyn in case you split Vardun up and take him with Seluna, Velyn would be the hero of choice to pair with Cataman (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Doom Bracers would be my second choice actually just because of the diffused damage that will scale incredibly well through Yun Ming when used with the Flaming Manticore war pet. Phoenix Eye would be my second choice actually just because of the diffused damage that will scale incredibly well through Yun Ming when used with the Flaming Manticore war pet.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Cantaman (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Cantaman with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Cantaman$hb$, $hb$Below you will find the talent tree builds for Cantaman that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. Unless you are one of the few players that actually rally with him, in open field you would use him normally as secondary commander with Cardun so the talent tree is not important but if you would split them up into two marches and he would lead the other one, the skill tree is always your choice as shown here$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/05/cantaman-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Cantaman helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-cantaman-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- seluna-legendary
  select id into hid from public.heroes where game_id=gid and slug=$hb$seluna-legendary$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Seluna Legendary S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Seluna Legendary is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Flying units are her speciality and she can be paired with pretty much everything there$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Seluna Legendary$hb$, $hb$Atheus is an absolutely great pairing with her as they both scale off their basic attacks and he provides the rage for her burst to keep snowballing and they both have quite a good amount of march speed together (See full build here ).

Bertrand is also a useful apiring with flying magic units (See full build here ).

Thundelyn is not a flying unit hero in the first place but with ground units I see some interesting synergies and mechanics honestly (See full build here ).

Yun-Ming works with everything and both together will make a rather useful F2P march (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Phoenix Eye -. – -.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Seluna Legendary (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Seluna Legendary with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Seluna Legendary$hb$, $hb$Below you will find the talent tree builds for Seluna Legendary that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. If you would use her as primary commander this is the talent tree that makes sense (even with full magic units you wouldn’t tap into the magic tree!)$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/seluna-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Seluna Legendary helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-legendary-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- joren
  select id into hid from public.heroes where game_id=gid and slug=$hb$joren$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Joren S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Joren is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Infantry is the name of the game with him$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Joren$hb$, $hb$Ellanir is like all heroes that are relased together a strong choice although if you really want a aggressive open field setup, Joren is better paired with more offensive heroes honestly (See full build here ).

Agnar is a great pick with cavalry that will deal a ton of damage and punish almost everything they cross (See full build here ).

Kuma is a good alternative setup for a lot of open field action but a little bit more on the sustain side of things without glass-canon too much (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Bladeguard is always a good fit with infantry espcially when you want to get a little more sturdy. Dragonscale Armor is always a good fit with infantry espcially when you want to get a little more sturdy.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Joren (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Joren with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Joren$hb$, $hb$Below you will find the talent tree builds for Joren that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. This talent build might look weird since we’re not going into any tree final skill, but the way his core mechanics work, this is the better option in my opinion to really leverage and snowball his Parry and counterattack mechanics with what open field combat requires from him$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/03/call-of-dragons-joren-talent-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Joren helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-joren-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- ellanir
  select id into hid from public.heroes where game_id=gid and slug=$hb$ellanir$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Ellanir S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Ellanir is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Infantry is the name of the game with her but as garrison commander she works well with what you got there (naturally)$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Ellanir$hb$, $hb$Joren is like all heroes that are relased together a strong choice but she offers other options as well where she can use her incredible defensive kit (See full build here ).

Kuma is a good alternative and they can both together do a lot of damage but do not expenct them to hold up long enough so pick your exit or battles carefully (See full build here ).

Goresh a very interesting pairing in my opinion hoenstly as their kits complement each other exceptionally well (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Dragonrift is always a good fit with infantry espcially when you want to get a little more sturdy. Dragonscale Armor is always a good fit with infantry espcially when you want to get a little more sturdy.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Ellanir (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Ellanir with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Ellanir$hb$, $hb$Below you will find the talent tree builds for Ellanir that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. This is the talent setup that makes most sense in my opinion$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/04/call-of-dragons-ellanir-talent-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Ellanir helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ellanir-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- agnar
  select id into hid from public.heroes where game_id=gid and slug=$hb$agnar$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Agnar S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Agnar is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Cavalry is the name of the game with him, ideally multi marches$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Agnar$hb$, $hb$Freya is the obvious choice here with him as they are designed to scale each other (See full build here ).

Mardok is also a good alternative for those of you who don’t hae the bankroll of small countries in the game where you can have Mardok as primary with Agnar as deputy and still have quite some success for a small budget (See full build here ).

Falgrim works if you have multiple cavalry marches and you use your Freya as commander in the other one (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Winters Edge is a good pick for the time being if you don’t have Winters Edge at your disposal. Sorlands Blade is a good pick for the time being if you don’t have Winters Edge at your disposal.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Agnar (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Agnar with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Agnar$hb$, $hb$Below you will find the talent tree builds for Agnar that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. Best talents here for me is the ones where you go after march speed relentlessly for open map PvP combat where you will catch and lock in every target you want with him$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/02/agnar-talent.jpg$hb$]::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Agnar helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-agnar-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- freya
  select id into hid from public.heroes where game_id=gid and slug=$hb$freya$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Freya S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Freya is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Cavalry is the name of the game with her$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Freya$hb$, $hb$Agnar is obviously the best pick here and designed to be so crazy strong alongside Freya. They do take out literally everything start of G5 unless counters get released later (See full build here ).

Mogro is a less obvious but still effective pairing since the debuffs work together and he can hel Freya trigger her skill damage multiple times (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Sorlands Blade works with the cowardice effect to increase damage if you have that laying around somewhere. Oath of Stormpeak works with the cowardice effect to increase damage if you have that laying around somewhere.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Freya (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Freya with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Freya$hb$, $hb$Below you will find the talent tree builds for Freya that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. This is the most reasonable talent tree here for her. It’s amazing how content creators make like 6 different setups and say this is how to build her just to have every possiblility done. I personally think other versions lopside her kit too much into specific directions but that is just my opinion.$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2026/02/freya-talent.jpg$hb$]::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Freya helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-freya-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- seluna
  select id into hid from public.heroes where game_id=gid and slug=$hb$seluna$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Seluna S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Seluna is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Flying units are her speciality and she can be paired with pretty much everything there$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Seluna$hb$, $hb$Ffraegar would make a great pairing here if you want a strong and powerful flying march with Seluna as secondary (See full build here ).

Kregg is a great flying hero and with Seluna a budget pairing you have (See full build here ).

Theia is about flying units and although I don’t see too much of a point to pair them up with each other, it would work in terms of synergy (See full build here ).

Bertrand with flying mages and her as secondary is for sure also a pairing you might think about (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$You wouldn’t really use her epic version as primary commander so recommending artifacts here is nothing else than theorycrafting.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Seluna (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Seluna with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Seluna$hb$, $hb$Below you will find the talent tree builds for Seluna that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. You wouldn’t actually use her as primary commander of your march and always as secondary, but here is the talent tree you would use with her as primary commander in her legendary form$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/seluna-talent-tree.jpg$hb$]::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Seluna helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-seluna-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- ruby
  select id into hid from public.heroes where game_id=gid and slug=$hb$ruby$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Ruby S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Ruby is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Marksman all the way with her$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Ruby$hb$, $hb$Kaelan is designed to work with Ruby together and they are the start of Generation 5 heroes and work incredibly well together (See full build here ).

Sibyl as G4 marksman is a pairing that makes sense since her kit for the most parts works together with Ruby (See full build here ).

Falgrim can be a more defensive setup to make Ruby last a little more but honestly I don’t see too many occasions where you want to do that and where you have a perfectly fine built Falgrim available as secondary hero but none of the other pairings (See full build here ).

Mu Hsiang is universally a hero that can be paired literally with any hero and can be a good swap-in here with Ruby (See full build here ).

Kinnara is a super budget pairing but she applies DEF Break on normal attacks which synergizes surpringly strong with Ruby (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$Let’s now take a look at the numerous artifacts that you can possible use. We have tested many of them and some have amazing synergy and others are more in for the stats but no matter what artifacts you have possibly available, you will find the one that works best. Please also check out the full tier list of all artifacts here to see which ones are worth the invest in general.

Roaring Rager is an offensively viable artifact that always hits the spot with marksman and if you don#t have her artifact yet and this one well-built, this is more than an option to think about. Shadowblades is an offensively viable artifact that always hits the spot with marksman and if you don#t have her artifact yet and this one well-built, this is more than an option to think about.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Ruby (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Ruby with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Ruby$hb$, $hb$Below you will find the talent tree builds for Ruby that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. This is the talent tree setup that makes most sense with her. I have seen the most ridiculous ones, like 40% March Speed Built or weird Precision Tree setups so be aware that some content creators create those just to create, not because it makes sense (I really don’t like calling someone out and rather focus on my work here but if I see ridiculous content being spun that just might set up player wrong I need to say something). So, bottom line, don’t over-complicate her straightforward kit and leverage her strength with a marksman tree build and you will see how the new generation of heroes does, they do truly amazing.$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/ruby-talent-tree-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Ruby helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-ruby-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  -- kaelan
  select id into hid from public.heroes where game_id=gid and slug=$hb$kaelan$hb$;
  delete from public.hero_builds where hero_id=hid;
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 0, $hb$Current Ranking – is Kaelan S-Tier , A-Tier , or D-Tier ?!$hb$, $hb$See how Kaelan is ranking in the different game modes of Call of Dragons in my current tier list here and also make sure that you’re running the best faction in Call of Dragons or you might really affect your progress negatively – I have an updated guide on the best factions in Call of Dragons here

Important! Don’t miss out on free Gems, Keys, Boosters and Speedups and frequently check my list of active gift codes for Call of Dragons here .$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 1, $hb$Skill Order$hb$, $hb$$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 2, $hb$Best Troop Types$hb$, $hb$Marksman when paired with Ruby but he can be paired with cavalry as well so the apiring dictates the troops here not vice versa$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 3, $hb$Best Hero Pairing for Kaelan$hb$, $hb$Ruby is the best primary commander to be used with him, simply as Kaelan will enhance her kit and her kit trigger his skills too well to make any other pairing that is even remotely as strong (See full build here ).

Urag is a niche pairing with cavalry that you see around here and there. Can be fun, can work, but at the end of the day a full G5 Marksman pairing is by far stronger than this (See full build here ).$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 4, $hb$Best Artifacts$hb$, $hb$This depends on what hero you pair him with, Kaelan is not a hero to use as primary commander!$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 5, $hb$Best Pet Synergies For Kaelan (NEW)$hb$, $hb$With the new war pet system in Call of Dragons it’s aso important to pair Kaelan with the right pet to gain more synergies. Please also check out the full tier list of all war pets in Call of Dragons here to see which ones are worth the invest in general.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 6, $hb$Best Builds For Kaelan$hb$, $hb$Below you will find the talent tree builds for Kaelan that make sense when running as the primary commander in any legion in Call of Dragons. Please also refer to the description below each talent tree as I explain a general route on how you should spend your talents there + some additional background for each talent build that I very likely will appreciate. If you WOULD use hima s primary commander, this is the way to go. But honestly he is a secondary commander through and through so don’t really mess with him as a primary commander and a talent built$hb$, array[$hb$https://www.allclash.com/wp-content/uploads/2025/12/ruby-talent-tree-build.jpg$hb$]::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
  insert into public.hero_builds (hero_id, order_index, section, content, images, source_url, is_verified) values (hid, 7, $hb$Conclusion$hb$, $hb$I hope this guide for building Kaelan helped you investing without wasting much time and resources. If you liked it or you further questions (or maybe also annnotations that you believe should be added here in this guide), please don’t hesitate to post them below in the comment section. Thanks for reading and have a great day.$hb$, '{}'::text[], $hb$https://www.allclash.com/best-kaelan-builds-talent-skill-order-pairing-pets-in-call-of-dragons/$hb$, false);
end
$do$;