do $do$
declare
  gid uuid;
  sid uuid;
begin
  select id into gid from public.games where slug='call-of-dragons';
  delete from public.game_sections where game_id=gid and slug='heroes';
  insert into public.game_sections (game_id, slug, title, intro_title, intro, intro_images, is_published) values (gid, 'heroes', $cod$Tier List de Héroes$cod$, $cod$Tier List de Héroes de Call of Dragons$cod$, $cod$Tier list de héroes por generaciones (de la 5, la más reciente, a la 1). Cada héroe indica su tier, clase, facción y mejor rol. Traducida de allclash.com — contenido sin verificar.$cod$, '{}', true) returning id into sid;
  insert into public.section_blocks (section_id, order_index, title, content, source_url, is_verified, images) values
    (sid, 1, $cod$Vardun — NEW$cod$, $cod$Generación 5 · Mago · League of Order · Mejor rol: PvP

Mago de la generación 5 con interesantes mecánicas de rune. Ahora mismo todo el mundo da por muerta a la infantería, pero sinceramente, lo primero de todo es que tienes que despertarlo por completo y, aun así, siguen entrando en juego otros factores. Si estás a mitad de montar tu configuración centrada en infantería, yo no me detendría ni cambiaría solo porque haya un nuevo posible counter duro en escena. Podría llegar a haber un counter duro contra los magos que ignoran defensa en la siguiente tanda de héroes antes de que suficientes jugadores lo hayan construido. Eso sí, si te van los magos, esto es ahora mismo un premio gordo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/04/Screenshot-1413.png$cod$]::text[]),
    (sid, 2, $cod$Cantaman — NEW$cod$, $cod$Generación 5 · Mago · Springwardens · Mejor rol: Rally

Diseñado para funcionar junto a Vardun y debilitar a la infantería. Si quieres apostarlo todo a eso, adelante, pero prepárate para construir por completo a estos dos héroes con un futuro incierto. Si eres un gran pagador lo harás, pero como jugador normal yo preferiría dejar pasar esta ronda.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/04/cantamanicon.jpg$cod$]::text[]),
    (sid, 3, $cod$Seluna Legendary — A+$cod$, $cod$Generación 5 · Universal · Springwardens · Mejor rol: PvP

Tiene un potencial increíble en PvP y no solo es divertida, sino que cuenta con el burst y el árbol de PvP que la harán muy divertida de jugar.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/04/selunaleg.png$cod$]::text[]),
    (sid, 4, $cod$Joren — S$cod$, $cod$Generación 5 · Infantería · League of Order · Mejor rol: PvP

Realmente una bestia de campo abierto para la G5 y, con las mecánicas de parry, en realidad tampoco es el glass cannon que yo esperaba que fuera.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/03/Screenshot-1227.png$cod$]::text[]),
    (sid, 5, $cod$Ellanir — S+$cod$, $cod$Generación 5 · Infantería · Springwardens · Mejor rol: Guarnición

Hace a la infantería más resistente y también funciona bien con la infantería de generaciones anteriores.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/03/Screenshot-1228.png$cod$]::text[]),
    (sid, 6, $cod$Agnar — A$cod$, $cod$Generación 5 · Caballería · League of Order · Mejor rol: PvP

Enorme, con una increíble reducción de defensa, y tiene potencial para arrollar a cualquier otra march que tengamos ahora mismo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/02/Screenshot-1124.png$cod$]::text[]),
    (sid, 7, $cod$Freya — A+$cod$, $cod$Generación 5 · Caballería · League of Order · Mejor rol: Rally

Un poco más contradictoria que Agnar, pero estoy seguro de que, emparejada con él, llevará la voz cantante durante unos cuantos meses.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2026/02/Screenshot-1123.png$cod$]::text[]),
    (sid, 8, $cod$Seluna — A$cod$, $cod$Generación 5 · Universal · Springwardens · Mejor rol: PvP

Héroe épico voladora universal de PvP. No va a cambiar el rumbo del meta en ningún sitio, pero es una gran incorporación a la mayoría de roasters voladores, ya que puedes emparejarla literalmente con cualquier héroe volador y siempre aporta algo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/12/Screenshot-1399.png$cod$]::text[]),
    (sid, 9, $cod$Ruby — S+$cod$, $cod$Generación 5 · Tirador · League of Order · Mejor rol: PvP

Ha llegado una nueva era y, aunque la última generación de tiradores no se ha apoderado del meta de tirador, Ruby llega con una nueva era de daño y utilidad que es mucho más de lo que ningún tirador ha hecho jamás.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/11/Screenshot-921.png$cod$]::text[]),
    (sid, 10, $cod$Kaelan — B+$cod$, $cod$Generación 5 · Tirador · Springwardens · Mejor rol: PvP

No solo junto a Ruby supone una nueva era de daño, sino que además es compatible con algunas configuraciones de caballería, lo que le da la versatilidad que a algunos héroes secundarios les falta al salir. Pero no es un comandante primario y depende mucho de que tengas bien construidos sus emparejamientos fuertes, sobre todo Ruby.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/11/Screenshot-922.png$cod$]::text[]),
    (sid, 11, $cod$Eirlys — B$cod$, $cod$Generación 4 · Universal · Springwardens · Mejor rol: Recolección

Nueva heroína épica de recolección, y tiene varios trucos bajo la manga cuando se disputa un Resource Point. No cambia el juego, pero parece divertida y seguro encontrará un buen hueco en tus marchas de recolección. Tiene 2 Holistic Skills que dan un bonus global de recolección, así que construirla es algo que deberías hacer de verdad.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/09/Screenshot-750.png$cod$]::text[]),
    (sid, 12, $cod$Yun-Ming — S$cod$, $cod$Generación 4 · Mago · League of Order · Mejor rol: PvP

Absolutamente poderoso y, junto a un buen emparejamiento y con el war pet, la magia vuelve a estar sobre la mesa y más fuerte que nunca. El héroe de magia más poderoso de Call of Dragons por la forma en que arrasa con su pasiva.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/09/yun-ming-icon.png$cod$]::text[]),
    (sid, 13, $cod$Gromara — B+$cod$, $cod$Generación 4 · Mago · Wilderburg · Mejor rol: Guarnición

No te confundas demasiado con lo de magic garrison; estoy seguro de que le pusieron esa etiqueta solo para no hacerla demasiado poderosa en cuanto a las opciones del árbol de habilidades. Está muy diseñada para funcionar junto a Yun-Ming, porque lanza ese enorme bonus de habilidad mágica que se reinicia cuando se lanza una rage skill, pero como Yun-Ming no tiene una activa sino una habilidad primaria pasiva, esto está activo todo el tiempo. Sin él no es realmente tan destacable, de ahí esa sinergia, y para garrison directamente no le veo el sentido.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/09/gromara-icon.png$cod$]::text[]),
    (sid, 14, $cod$Flynt — B$cod$, $cod$Generación 4 · Universal · Wilderburg · Mejor rol: Recolección

Hay tanto que decir de este héroe que es difícil resumirlo sin escribir un ensayo completo aquí, así que ten en cuenta que esta es una descripción muy simplificada. El héroe roba Gold y es universal, y aunque muchos jugadores pasan por alto las curiosas opciones de emparejamiento, la parte más interesante del héroe es que tiene 2 habilidades globales (llamadas holistic skills) que aumentan de forma pasiva el resultado de la recolección para todos los héroes, incluso si nunca usas a Flynt activamente. Esto es la Skill 4 y la Awaken Skill. Aparte de eso, puedes usar a Flynt para enredar un poco, pero sinceramente no es un héroe para usar activamente a menos que andes corto de marchas de recolección; eso sí, es uno para llevar al máximo y tener esa pasiva.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/09/flynt-icon.png$cod$]::text[]),
    (sid, 15, $cod$Lei Kuan — B+$cod$, $cod$Generación 4 · Infantería · League of Order · Mejor rol: Rally

Hacía tiempo que no pasaba gran cosa con la infantería y, aunque Lei Kuan tiene cosas geniales en su kit, también es un comandante de rally y parte de su kit hace exactamente eso. Ahora bien, también funciona en combate a campo abierto cuando puedes construir las marchas adecuadas, y este es un punto de inversión que depende mucho de tu roster y de si tienes alguno de los héroes de infantería más recientes.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/07/lei-kuan-icon.png$cod$]::text[]),
    (sid, 16, $cod$Kuma — S$cod$, $cod$Generación 4 · Infantería · Wilderburg · Mejor rol: PvP

Si buscas volver a poner la infantería en forma, él es el héroe que lo logrará, con un montón de cosas geniales en su kit. Necesita emparejamientos de infantería de alto nivel, pero si consigues que se den, tendrás una auténtica bestia en tu escuadrón.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/07/kuma-icon.png$cod$]::text[]),
    (sid, 17, $cod$Mardok — S+$cod$, $cod$Generación 4 · Caballería · Wilderburg · Mejor rol: PvP

Admito que pensé que era una broma que no entendía. Es un nuevo héroe épico de caballería que es increíblemente fuerte, incluso más fuerte que bastantes legendarios del juego, con una utilidad impresionante. Y como probablemente estés sentado sobre recursos de sobra, es un héroe que puedes construir fácilmente ahora. Tiene bastante daño, pero lo increíble es su defense break y la utilidad que aporta. Si quieres una buena incorporación para tu línea de caballería, él es el héroe a construir sin excepción.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/06/Screenshot-400.png$cod$]::text[]),
    (sid, 18, $cod$Neya — S$cod$, $cod$Generación 4 · Caballería · Springwardens · Mejor rol: PvP

Caballería de Generation 4 con camuflaje y locas habilidades para cazar objetivos, ignorando HP y con un motor de rage integrado. Inversión dura, especialmente porque la caballería tiene el papel que tiene en el juego, pero es increíblemente fuerte y divertida si tienes cartera para ella. La mayoría de los jugadores no la tendrá, por eso el ranking debe tomarse con pinzas; pero como solo clasifico en base a lo que hace un héroe y no a lo que cuesta construirlo, la tenemos en un buen puesto.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/05/neya-icon.png$cod$]::text[]),
    (sid, 19, $cod$Lieh-Shan Yen — B+$cod$, $cod$Generación 4 · Caballería · League of Order · Mejor rol: Guarnición

Hay dos razones por las que lo construirías. La Opción 1 es la más viable para los jugadores que leen esto, y es usarlo junto a Neya para una legión de caballería de emboscada increíblemente fuerte que cace lo que sea que haya en el mapa. La otra opción es la parte de garrison, que solo es viable para un puñado de jugadores en cada servidor, y ellos lo llevarán al máximo y pagarán por todo, así que dudo que alguno de ellos esté leyendo esto. Así que invierte en él solo si piensas construir a Neya hasta el final.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/03/Screenshot-215.png$cod$]::text[]),
    (sid, 20, $cod$Sibyl — S$cod$, $cod$Generación 4 · Tirador · League of Order · Mejor rol: PvP

Absolutamente fuerte. Será la Maggrat más poderosa, y recordarás cómo dominó al salir; y como puedes emparejarla con los potentes tiradores, desde Nico hasta Maggrat, también es viable sin tener que llevar al máximo a Falgrim de inmediato. Incluso puedes emparejarla con Nico y tener una configuración de tiradores sólida y actual si hasta ahora no has invertido demasiado en tiradores. O simplemente usa a la legendaria Mu Hsiang con ella. Vale la pena la inversión.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/sibyl-icon.png$cod$]::text[]),
    (sid, 21, $cod$Falgrim — A$cod$, $cod$Generación 4 · Tirador · League of Order · Mejor rol: Rally

De primera junto a Sibyl si quieres una marcha tope de gama para principios de S3, pero le falta compatibilidad con otros héroes aparte de Kinnara. Si quieres gastar y llevarlo al máximo, súbelo y úsalo con Sibyl y serás una potencia; pero si tienes que decidir entre él y Sibyl a dónde va tu inversión, Sibyl es mucho más flexible por sí sola con otros héroes que Falgrim.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/falgrim-icon.png$cod$]::text[]),
    (sid, 22, $cod$Mu Hsiang — S+$cod$, $cod$Generación 4 · Universal · League of Order · Mejor rol: PvP

Absolutamente buena y digna de construir. Mejora casi todas las marchas y funciona muy bien con muchísimas configuraciones. Al principio de la S3, dará otro gran impulso a las marchas de magia en torno a Thundelyn y Thaleia, así que si quieres dominar al comienzo de la S3, ella es tu objetivo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/call-of-dragons-mu-hsiang-legendary-icon.png$cod$]::text[]),
    (sid, 23, $cod$Thundelyn — S+$cod$, $cod$Generación 3 · Mago · Springwardens · Mejor rol: PvP

Toda una bestia con daño en área, buffs y debuffs increíbles, y la forma en que vuelve a poner a los magos en el centro de la acción la hace extremadamente fuerte. Sacude bastantes cosas con su lanzamiento y, como además puedes emparejarla con Theia para divertirte con el meta, incluso aporta un valor moderado para los que gastan poco.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/thundelyn-icon.png$cod$]::text[]),
    (sid, 24, $cod$Thaleia — B+$cod$, $cod$Generación 3 · Mago · Wilderburg · Mejor rol: Rally

Es realmente fuerte y, cuando está al máximo junto a Thundelyn, marca el meta durante un buen tiempo. Pero hay un detalle que le pone un pelo en la sopa, y es que Thundelyn, como héroe principal del meta, también funciona bien sin estar al máximo junto a Theia, lo que hace que construir a Thaleia sea un poco un powercreep en general. Para la mayoría de los jugadores, una Thundelyn 5111 con Theia al máximo tiene mucho más sentido que una Thundelyn 5555 junto a Thaleia. Sin duda es material para los que gastan.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/thaleia-icon.png$cod$]::text[]),
    (sid, 25, $cod$Danfel — A+$cod$, $cod$Generación 3 · Infantería · League of Order · Mejor rol: PvP

Es una inversión bastante centrada en infantería y vale la pena si quieres hacerlo, pero para la mayoría de los jugadores realmente no lo veo. Aun así, si juegas con infantería y tienes un roster sólido, incluso puedes emparejarlo con Madeline o Garwood y montar una nueva marcha divina con eso.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/danfel-icon.png$cod$]::text[]),
    (sid, 26, $cod$Mogro — B$cod$, $cod$Generación 3 · Infantería · Springwardens · Mejor rol: Guarnición

Puede hacer cosas desagradables con su kit, pero no es un héroe para todos los jugadores y necesita los artefactos específicos, a Danfel al máximo y, en conjunto, es más un powercreep que un héroe universal para usar.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/mogro-icon.png$cod$]::text[]),
    (sid, 27, $cod$Urag — A$cod$, $cod$Generación 3 · Caballería · Wilderburg · Mejor rol: PvP

Un kit increíble en general, cosas realmente de locos. Pero también necesita algo de supervivencia. Aun así, sabemos cómo se introducen los héroes nuevos en el juego, y este es simplemente un monstruo de caballería que reparte daño de forma directa, pero eso mismo hace que para la mayoría de los jugadores no sea viable. No es una inversión duradera, es una supernova brillante: mucho impacto, pero fuera del meta de nuevo lo bastante rápido, a menos que seas un jugador de caballería de corazón.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/urag-icon.png$cod$]::text[]),
    (sid, 28, $cod$Tobin — B$cod$, $cod$Generación 3 · Caballería · League of Order · Mejor rol: Rally

Ten en cuenta que está diseñado para jugar junto a Urag, y es ahí cuando realmente rinde bien. Si no construyes a Urag, ¡no hay ninguna razón real para siquiera pensar en Tobin!$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/tobin-icon.png$cod$]::text[]),
    (sid, 29, $cod$Zayda — S$cod$, $cod$Generación 3 · Tirador · League of Order · Mejor rol: PvP

Destrona a Ffraegar y a Syndrion en cuanto a DPS junto a Maggrat, pero es una héroe de tipo tirador increíble que combina bien con prácticamente todos los héroes tiradores del juego.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/zayda-icon.png$cod$]::text[]),
    (sid, 30, $cod$Maggrat — S$cod$, $cod$Generación 3 · Tirador · Wilderburg · Mejor rol: Guarnición

La nueva héroe que quieres para garrison O que puedes usar junto a Zayda para montar la legión con mayor DPS, lo que obviamente la coloca tan alto en la lista. Una héroe increíble en general.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/maggrat-icon.png$cod$]::text[]),
    (sid, 31, $cod$Bertrand — B+$cod$, $cod$Generación 3 · Mago · League of Order · Mejor rol: PvP

Normalmente los héroes nuevos son superfuertes pero tardan algo de tiempo, y el arquetipo de magia voladora es nuevo. Pero, ahora mismo, no hay nada más que hacer con Bertrand salvo emparejarlo con Tohar, ya que ese es el único emparejamiento real que tiene sentido, y las marchas voladoras y mágicas actuales ya hacen un buen trabajo. Los veo mucho más usados y valiosos dentro de un par de meses, pero en el lanzamiento recomendaría jugarlos despacio. No porque sean débiles, sino porque la inversión frente a lo que obtienes es bastante mala. Estoy seguro de que esto cambiará y, si te sientes aventurero e inviertes el dinero para construirlos, probablemente los tendrás listos para el momento en que rindan de verdad, pero para la mayoría de los jugadores no quiero recomendarlos a base de especulaciones, porque ahora mismo realmente no los necesitas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/bertrand-icon.png$cod$]::text[]),
    (sid, 32, $cod$Tohar — B$cod$, $cod$Generación 3 · Mago · Wilderburg · Mejor rol: Guarnición

Normalmente los héroes nuevos son superfuertes pero tardan algo de tiempo, y el arquetipo de magia voladora es nuevo. Pero, ahora mismo, no hay nada más que hacer con Bertrand salvo emparejarlo con Tohar, ya que ese es el único emparejamiento real que tiene sentido, y las marchas voladoras y mágicas actuales ya hacen un buen trabajo. Los veo mucho más usados y valiosos dentro de un par de meses, pero en el lanzamiento recomendaría jugarlos despacio. No porque sean débiles, sino porque la inversión frente a lo que obtienes es bastante mala. Estoy seguro de que esto cambiará y, si te sientes aventurero e inviertes el dinero para construirlos, probablemente los tendrás listos para el momento en que rindan de verdad, pero para la mayoría de los jugadores no quiero recomendarlos a base de especulaciones, porque ahora mismo realmente no los necesitas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/tohar-icon.png$cod$]::text[]),
    (sid, 33, $cod$Bahorn — S$cod$, $cod$Generación 2 · Universal · League of Order · Mejor rol: PvP

Muy fuerte con un buen emparejamiento y útil ya a 5511. Sin duda vale la pena conseguirlo y desarrollarlo, especialmente si puedes emparejarlo con una Mu Hsiang bien desarrollada.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2025/03/call-of-dragons-bahorn-icon.png$cod$]::text[]),
    (sid, 34, $cod$Skogul — A+$cod$, $cod$Generación 2 · Infantería · Wilderburg · Mejor rol: PvP

Hasta ahora la infantería se usaba como carne de cañón, y ahora tienes a Goresh y Skogul, que pueden forzar a los enemigos a atacarlos y derretirlos con el contraataque, lo que tuvo un gran impacto en el meta; son una march de infantería casi obligatoria en el endgame de Call of Dragons.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/skogul-icon.png$cod$]::text[]),
    (sid, 35, $cod$Goresh — A+$cod$, $cod$Generación 2 · Infantería · Wilderburg · Mejor rol: Rally

Hasta ahora la infantería se usaba como carne de cañón, y ahora tienes a Goresh y Skogul, que pueden forzar a los enemigos a atacarlos y derretirlos con el contraataque, lo que tuvo un gran impacto en el meta; son una march de infantería casi obligatoria en el endgame de Call of Dragons.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2023/10/call-of-dragons-goresh-icon.png$cod$]::text[]),
    (sid, 36, $cod$Forondil — A$cod$, $cod$Generación 2 · Caballería · Springwardens · Mejor rol: PvP

Su kit es súper interesante y extremadamente anti-marksman, así que esto podría realmente elevar a la caballería al meta, y además tiene el árbol de control que acompaña a su habilidad activa muy centrada en el control. También es útil en temporadas posteriores y, si estás pensando en invertir y la caballería es lo tuyo, es un héroe con buen valor.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/forondil-icon.png$cod$]::text[]),
    (sid, 37, $cod$Theodore — B$cod$, $cod$Generación 2 · Caballería · League of Order · Mejor rol: Guarnición

Me gusta la combinación del árbol de habilidades de garrison y caballería, y sus habilidades aportan defensa extra, que es justo lo que la caballería necesita. Creo que, emparejado correctamente, para que puedas aprovechar el daño de habilidad extra mediante un héroe secundario que aplique debuffs, puede convertirse también en una opción fuerte. Lo veo dominando junto a Forondil como emparejamiento hacia el final de la Season 2, pero para el jugador promedio es una inversión difícil de justificar, y además en temporadas posteriores no verás mucho retorno al desarrollarlo. Es un héroe muy fuerte, pero de uso momentáneo y para gastadores en Call of Dragons.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/theodore-icon.png$cod$]::text[]),
    (sid, 38, $cod$Ffraegar — A$cod$, $cod$Generación 2 · Tirador · Springwardens · Mejor rol: Pacificación

Como héroe marksman tiene un alcance muy lejano con su habilidad activa (mientras que todos los demás héroes marksman de Call of Dragons tienen alcance medio, así que ella es el clavo en el ataúd de tu generación de héroes marksman de apertura de servidor). Después de todo, ella junto a Syndrion ostentan el título de la march con mayor DPS hasta que llegan Zayda/Maggrat, así que hay valor a largo plazo aquí si estás dispuesto a desarrollar a ambos.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/ffraegar-icon.png$cod$]::text[]),
    (sid, 39, $cod$Syndrion — A$cod$, $cod$Generación 2 · Tirador · Springwardens · Mejor rol: Rally

Su sinergia y valor en la Season 2 cuando se empareja con Ffraegar como secundaria es bastante bueno, y forman uno de los mejores emparejamientos de Call of Dragons ahora mismo para todo tipo de situaciones, especialmente con los nuevos artefactos y ahora también con las war pets. Después de todo, ella junto a Syndrion ostentan el título de la march con mayor DPS hasta que llegan Zayda/Maggrat, así que hay valor a largo plazo aquí si estás dispuesto a desarrollar a ambos.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/syndrion-icon.png$cod$]::text[]),
    (sid, 40, $cod$Liliya — S+$cod$, $cod$Generación 1 · Mago · League of Order · Mejor rol: Pacificación

Liliya tiene un daño en área muy bueno gracias a su habilidad activa. Una de sus habilidades pasivas solo aumenta el daño contra Darklings y Dark Creatures, y la otra solo potencia a las unidades de magia, pero sobre todo con el lanzamiento del juego y lo (relativamente) barata que resulta conseguirla en comparación con otros héroes legendarios de Call of Dragons. Gran daño y probablemente EL héroe que más verás peleando por ahí ahora mismo, y por una buena razón. Necesitas invertir algo de dinero, pero aún hoy, un año después del lanzamiento, sigue siendo el único héroe que ves en las marchas de magia todo el tiempo, lo que me hace ponerla en lo más alto (todavía), y estoy dispuesto a defenderlo a muerte en 2024.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/lilya-icon.png$cod$]::text[]),
    (sid, 41, $cod$Kinnara — S+$cod$, $cod$Generación 1 · Tirador · Wilderburg · Mejor rol: PvP

Kinnara es un héroe de campo abierto muy fuerte y todas sus habilidades giran en torno a debilitar a la legión enemiga, infligir daño y bloquear al objetivo, lo que la convierte en una de las mejores héroes de PvP de Call of Dragons. Me encanta, pero la forma de conseguirla a través de la ruleta es bastante cara, así que la he colocado un poco más abajo, aunque es una marksman increíble, y con el war pet que inflige daño al romper la DEF, todavía mejor.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/kinnara-icon.png$cod$]::text[]),
    (sid, 42, $cod$Velyn — S$cod$, $cod$Generación 1 · Mago · Springwardens · Mejor rol: PvP

Similar a Liliya, funciona con congelación y daño de magia, pero en general tiene un kit estupendo y es un gran héroe para usar en campo abierto. ¿Por qué no está por encima de Liliya? Me gusta mucho su kit de control, pero Liliya en conjunto puede infligir mucho más daño y, aunque hacen una pareja increíble juntos, Liliya es solo un pelín mejor por el daño que inflige, y además es más fácil de construir con una inversión pequeña en comparación con Velyn. Aun así, Velyn se puede construir bastante bien a través de los Daily Packs y con las Season 1 Stones que conseguiste, y en general es simplemente un héroe increíble en Call of Dragons ahora mismo. Seguirá siendo meta en la Season 2 para las legiones de mago junto a Liliya.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/velyn-icon.png$cod$]::text[]),
    (sid, 43, $cod$Waldyr — A+$cod$, $cod$Generación 1 · Mago · League of Order · Mejor rol: PvP

Waldyr es el héroe épico mejor valorado de Call of Dragons, ya que su kit es simplemente excelente y arrasará en las primeras etapas. El primer épico que maximizar y usar, ya sea con Liliya o con Velyn. Increíblemente fuerte para empezar, pero luego se volverá irrelevante, así que cuanto más rápido lo construyas, más tiempo podrás disfrutarlo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/waldyr.png$cod$]::text[]),
    (sid, 44, $cod$Madeline — A$cod$, $cod$Generación 1 · Infantería · League of Order · Mejor rol: PvP

Muy al principio del lanzamiento del servidor no encontrarás demasiadas cosas interesantes que hacer con ella (a menos que seas la ballena de tu alianza). Pero es muy versátil a la hora de hacer que la infantería sea más resistente, e incluso los héroes de infantería de temporadas posteriores pueden sacar buen provecho de ir emparejados con ella. Constrúyela despacio pero con constancia y te dará buenos resultados, pero no hace falta apresurarse a construirla nada más empezar el servidor.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/madeline.png$cod$]::text[]),
    (sid, 45, $cod$Kregg — B+$cod$, $cod$Generación 1 · Tirador · Wilderburg · Mejor rol: Ingeniería

Divertido al principio y más adelante funciona en combinación con marchas voladoras para construir. Nunca está en la cima del meta, pero resulta útil durante mucho tiempo en ciertas situaciones.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/kregg.png$cod$]::text[]),
    (sid, 46, $cod$Emrys — B+$cod$, $cod$Generación 1 · Caballería · Springwardens · Mejor rol: PvP

Emrys tiene una gran habilidad activa que inflige mucho daño al objetivo y, combinada con su acumulación extra de rage al entrar en combate, lo convierte en una amenaza constante cada vez que está en el campo en Call of Dragons. Es ese causante de daño que quieres llevar en las legiones de caballería, pero corre una suerte parecida a la de Bakshi, ya que la caballería simplemente no es tan buena y los nuevos comandantes de caballería no mejoran realmente su situación; creo que la caballería voladora entrará más en el meta en la Season 2 y más allá, pero la caballería se usa cada vez más para conseguir banderas que están lejos, así que aún conserva un sitio sólido aquí.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/emrys-icon.png$cod$]::text[]),
    (sid, 47, $cod$Bakshi — B+$cod$, $cod$Generación 1 · Caballería · Wilderburg · Mejor rol: Pacificación

Los buffs y el daño de habilidad de Bakshi son sencillamente potentes y certeros; su único punto débil es que los objetivos múltiples simplemente no le funcionan bien, ya que todo lo que hace está orientado al daño a un solo objetivo. Puedes conseguirlo a través del Gold Chest, pero construir sus habilidades puede convertirse en todo un cuello de botella; aun así, si te va la caballería deberías tenerlo en la lista. Ya no es el mejor héroe de caballería, pero como la caballería se usa cada vez más para capturar banderas, sigue siendo lo bastante importante.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/bakshi-icon.png$cod$]::text[]),
    (sid, 48, $cod$Theia — B+$cod$, $cod$Generación 1 · Universal · League of Order · Mejor rol: PvP

El escudo y los buffs la convierten en una gran héroe de apoyo para acompañar, pero por sí sola tiene verdaderos problemas, ya que los combates pueden literalmente alargarse eternamente sin que ella inflija daño, aunque tampoco recibe apenas daño. Está bien al principio, también porque es épica y fácil de construir, y hace una pequeña reaparición en el meta justo al final de la Season 2, antes de la Season 3, con Thundelyn. Así que tiene utilidad temprana y utilidad tardía, y puede hacer mucho porque no está atada a un tipo de tropa concreto, lo que la convierte en una buena inversión a largo plazo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/theia-icon.png$cod$]::text[]),
    (sid, 49, $cod$Hosk — B$cod$, $cod$Generación 1 · Universal · Wilderburg · Mejor rol: Rally

Hosk es un héroe absolutamente de pagar-toneladas-de-ballena en un servidor nuevo. Incluso si invirtieras todo el dinero para conseguirlo y construirlo, tendrías que invertir más para hacerlo viable. El 99,99% de los jugadores no lo construirán ni necesitarán construirlo jamás, y quienes lo hagan no leerán esto porque van a maximizarlo todo de todas formas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/hosk-icon.png$cod$]::text[]),
    (sid, 50, $cod$Garwood — B$cod$, $cod$Generación 1 · Infantería · Springwardens · Mejor rol: Guarnición

Gracias a la curación abre emparejamientos de infantería interesantes más adelante, pero no es un héroe que debas construir pronto cuando abre tu servidor; al igual que Madeline, en temporadas posteriores con infantería empieza a hacer cosas buenas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/garwood-icon.png$cod$]::text[]),
    (sid, 51, $cod$Nico — B$cod$, $cod$Generación 1 · Tirador · League of Order · Mejor rol: Ingeniería

Está bien al principio, cuando abre el servidor, pero como los marksman de temporadas posteriores tienden a usar arquetipos distintos y tienen rangos diferentes, ya no se usa después de la Season 1, así que invierte con cuidado aquí si vas a jugar a Call of Dragons a largo plazo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/nico-icon.png$cod$]::text[]),
    (sid, 52, $cod$Nika — B$cod$, $cod$Generación 1 · Infantería · League of Order · Mejor rol: Pacificación

Funciona al principio, pero la forma en que el arquetipo de infantería evoluciona en las siguientes temporadas no encaja para nada con ella, así que construirla por completo tiene muy poco retorno, ya que los servidores nuevos están dominados por la magia y, una vez que le llega el turno a la infantería, Nika no será un héroe para usar con ella, porque todos se decantan por el contraataque o por ser superresistentes.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/nika-icon.png$cod$]::text[]),
    (sid, 53, $cod$Indis — B$cod$, $cod$Generación 1 · Universal · Springwardens · Mejor rol: Recolección

La consigues construida gratis y no es realmente un héroe que enviarías activamente al combate, pero sirve para recolectar y eso lo hace bien, además de encajar en varias funciones de nicho; eso sí, no inviertas universales en ella.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/indis-icon.png$cod$]::text[]),
    (sid, 54, $cod$Atheus — C+$cod$, $cod$Generación 1 · Mago · League of Order · Mejor rol: PvP

Está bien para volar al principio, pero realmente no está en posición, en los servidores nuevos, de hacer demasiado, y para cuando las unidades voladoras entran en juego, otros héroes llevan la batuta. Me gusta mucho, pero en cuanto a relevancia en el meta, nunca llega un momento en el que de verdad puedas usarlo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/atheus-icon.png$cod$]::text[]),
    (sid, 55, $cod$Alwyn — C+$cod$, $cod$Generación 1 · Mago · Springwardens · Mejor rol: PvP

En realidad es un héroe de magia de control muy chulo, pero su gran defecto es que el hielo y los demás héroes de magia que hay justo al inicio del servidor son tan fuertes que luego ya no queda relevancia para él. Como jugador completamente F2P puedes intentar maximizarlo, pero hay tantos jugadores con Liliyas bien construidas por ahí que te enseñarán tus límites enseguida, que no puedo recomendar sinceramente construirlo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/alwyn-icon.png$cod$]::text[]),
    (sid, 56, $cod$Gwanwyn — C$cod$, $cod$Generación 1 · Tirador · Springwardens · Mejor rol: Pacificación

Por desgracia no vale gran cosa. Los marksman, debido a Nico, en los servidores nuevos son básicamente inútiles contra la magia, y una vez que les llega el turno a los marksman hacia el final de la Season 1, estos consiguen mayor rango. Puedes darle mil vueltas y, como es épica, la construyes a largo plazo de todas formas, pero no inviertas activamente en ella.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/gwanwyn-icon.png$cod$]::text[]),
    (sid, 57, $cod$Bakhar — C$cod$, $cod$Generación 1 · Infantería · Wilderburg · Mejor rol: Guarnición

Sinceramente, nunca acaba de despegar, porque si haces caballería de servidor nuevo para hacer raids, llevas a Bakshi y a Emrys, y si no, no hay razón para llevarlo, ya que le dan una paliza. Y después de eso la caballería evoluciona de una forma que lo deja todavía más inútil.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/bakhar-icon.png$cod$]::text[]),
    (sid, 58, $cod$Alistair — C$cod$, $cod$Generación 1 · Caballería · League of Order · Mejor rol: Rally

Buena idea aquí, pero la caballería épica no funciona, ni al principio del servidor ni más adelante. Alistair tiene algunos emparejamientos de nicho más tarde como relleno, pero para entonces ya habrás conseguido de forma orgánica suficiente material de los cofres como para construirlo por completo de todas formas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/alistair-icon.png$cod$]::text[]),
    (sid, 59, $cod$Naernin — C$cod$, $cod$Generación 1 · Infantería · Springwardens · Mejor rol: Recolección

Igual que con Tarra, no intentes hacer nada raro aquí. Es una gran héroe de recolección y eso es lo que hace. Nada de universales para construirla y listo.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/naernin-icon.png$cod$]::text[]),
    (sid, 60, $cod$Tarra — C$cod$, $cod$Generación 1 · Universal · League of Order · Mejor rol: Recolección

Vale, antes de que todo el mundo se emocione demasiado con los nuevos épicos F2P de Call of Dragons. Sí, Tarra cura y tiene el árbol de apoyo, pero al final del día las mecánicas del juego son las que son y no hay ninguna forma secreta real de emparejarla. Es una héroe épica de recolección y para eso debería usarse, y eso lo hace estupendamente.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/tarra-icon.png$cod$]::text[]),
    (sid, 61, $cod$Chakcha — C$cod$, $cod$Generación 1 · Universal · Wilderburg · Mejor rol: Recolección

Chakcha es una héroe de recolección pura y prácticamente la maximizarás con los tokens que consigues de los Silver Chests sin problema.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/chakcha-icon.png$cod$]::text[]),
    (sid, 62, $cod$Kella — C$cod$, $cod$Generación 1 · Universal · Wilderburg · Mejor rol: Recolección

Kella es una héroe de recolección pura y prácticamente la maximizarás con los tokens que consigues de los Silver Chests sin problema.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/kella-icon.png$cod$]::text[]),
    (sid, 63, $cod$Ordo — C$cod$, $cod$Generación 1 · Universal · Wilderburg · Mejor rol: Ingeniería

Probablemente lo maximices y no lo uses después de unos días, así que no hay razón para profundizar demasiado en él. Es bueno para engineering, así que es algo para un servidor muy nuevo o algo no demasiado interesante para la mayoría de los jugadores de todas formas.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/ordo-icon.png$cod$]::text[]),
    (sid, 64, $cod$Eliana — D$cod$, $cod$Generación 1 · Universal · League of Order · Mejor rol: Pacificación

El evento del inicio la hace parecer más fuerte de lo que es; literalmente nunca hay relevancia alguna en construirla y usarla en Call of Dragons.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/eliana-icon.png$cod$]::text[]),
    (sid, 65, $cod$Pan — D$cod$, $cod$Generación 1 · Universal · Wilderburg · Mejor rol: Recolección

Déjame decirlo así... si no la hubieran metido en el juego, nadie habría notado su ausencia. Literalmente no hay ni un solo caso de uso para ella.$cod$, 'https://www.allclash.com/call-of-dragons-best-heroes-tier-list/', false, array[$cod$https://www.allclash.com/wp-content/uploads/2024/12/pan-icon.png$cod$]::text[]);
end
$do$;